### ISSUE TITLE
Compatibility with Tempermonkey on opera browser

### ISSUE THREAD

**Issue by Naivra** [TagoDR/MangaOnlineViewer#10]
is it just me or the script is not working properly with tempermonkey on opera browser? the script load but the image does not.
![image](https://cloud.githubusercontent.com/assets/29028972/26813733/6060b9d4-4aaa-11e7-9bd0-42c7f75f880f.png)

**Comment by TagoDR** [comment]
Opera's Tampermonkey is not as up-to-date as the other browsers, so it have a conflict with the way I remove  key-binds from the original page. I have added a fix, it should be fine now.
I don't test my script on Opera, it should work there thou because of Tampermonkey .
