### ISSUE TITLE
CANT DOWNLOAD AT HENTAI.CAFE

### ISSUE THREAD

**Issue by trueneko** [TagoDR/MangaOnlineViewer#100]
i have good internet but .. why i cant download at hentai.cafe ? before update its work .. and today not work .. LINK : https://hentai.cafe/manga/read/kyockcho-kaede-suzu/en/0/1/page/1#download

**Comment by TagoDR** [comment]
I need more information. Open the console F12 and see the progress, in some sites all pages needs to be download again.

**Comment by trueneko** [comment]
well at in console : VM22:38 Refused to connect to "https://cdn.hentai.cafe/manga/content/comics/kyockcho-kaede-suzu_5ad33d32a9651/1-0_5ad33d466809b/18.jpg": URL was permanently blocked by the user .. how refix that problem ?

**Comment by TagoDR** [comment]
Uninstall and install again the script, next time it asks for permission to connect cross-origin allow it always.
