### ISSUE TITLE
How do I turn off auto-loading?

### ISSUE THREAD

**Issue by 316ko** [TagoDR/MangaOnlineViewer#102]
Whenever a chapter is opened (same tab, or new tab) the manga pages load automatically. Is there a way to turn off this feature and make it load on command?

**Comment by TagoDR** [comment]
1. select a manga chapter
2. mangaviewer popup shows, click ok
3. open up settings, set to never show pop up, only manually
4. refresh page

**Comment by 316ko** [comment]
I'm not getting that option
https://i.imgur.com/HUMqbPF.png
