### ISSUE TITLE
Start MangaViewer doesn't work in mangadex.org

### ISSUE THREAD

**Issue by drogga3** [TagoDR/MangaOnlineViewer#103]
Environment: 
Chromium Version 78.0.3904.70 (Official Build) (64-bit)
Violentmonkey v2.11.2
Steps:
- install script
- open mangadex.org
- select a manga chapter
- mangaviewer popup shows, click ok
- open up settings, set to never show pop up, only manually
- refresh page
What was expected: "Start MangaViewer" button shows up on top of screen
What happened: button doesn't show up.

**Comment by TagoDR** [comment]
Fixed it

**Comment by drogga3** [comment]
Confirmed fixed. Thank you for the work.

**Comment by Riztard** [comment]
um help? mine not showing even after reinstall
