### ISSUE TITLE
Pre-load next chapters.

### ISSUE THREAD

**Issue by drogga3** [TagoDR/MangaOnlineViewer#106]
On manga with very short page counts, MangaOnlineViewer will only pre-load pages within the current manga chapter, thus rendering titles like https://mangadex.org/title/21893/otome-danshi-ni-koisuru-otome useless with this userscript.

**Comment by CoLdAs1cE** [comment]
press next in new tab?

**Comment by drogga3** [comment]
no, the point it the script should load pages from the next chapters too. if you press next, it will only load the first page

**Comment by TagoDR** [comment]
Sorry that would require a full redesign of the script. If I think up some way, I may implement it, but its not gonna be soon.

**Comment by drogga3** [comment]
Yeah, I just want to raise awareness of the issue and hope it will be on your next milestone.
