### ISSUE TITLE
not working in any site

### ISSUE THREAD

**Issue by explore01** [TagoDR/MangaOnlineViewer#107]
hi there again TagoDR!

just today i found that your script didn't work anymore, is it something that got to do with last update? as i see it just got updated recently (14 hours earlier since i post this)..
or is it got something to do with my browser? firefox suddenly update itself just recently as well.. now i'm on firefox 70.0.1
tamper monkey is on current version, show notif that one script for the page is on (this script), but the page didn't load like how it should be, it load normally as if there is no script work on the page..
these are the pages that i just visited and find your script didn't work:
mangadex, hatigarm, jaiminisbox, mangastream...

thanks again! and sorry for keep troubling you for these fixes!
regards
Riz

**Comment by explore01** [comment]
hi TagoDR,

want to update the issue here...
this script still work fine at my office's PC, running on win 10 and firefox 69.0.0 with Tampermonkey

so the issue only happen with my own PC, still got no idea why it didn't work..

thanks

**Comment by TagoDR** [comment]
It should work just fine,open the console with F12 and see what errors shows up.

**Comment by explore01** [comment]
hey TagoDR, sorry for late reply

here what i got from F12, console tab

Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/sweetalert2@8.18.0/dist/sweetalert2.min.js userscript.html:23:9
MangaOnlineViewer: Starting Manga OnlineViewer 15.03.0 on Firefox 70 with Tampermonkey 4.9.6095 userscript.html:1032:13
MangaOnlineViewer: 37 Known Manga Sites userscript.html:1032:13
MangaOnlineViewer: Looking for a match... userscript.html:1032:13
MangaOnlineViewer: Site Found: 
Object { name: "Funmanga", url: /https?:\/\/(www.)?funmanga.com\/.+\/[0-9]+/, homepage: "http://funmanga.com/", language: (1) […], category: "manga", run: run()
 }
userscript.html:1032:13
MangaOnlineViewer: Found 21 pages userscript.html:1032:13
ERROR: Execution of script 'Manga OnlineViewer' failed! Swal is not defined userscript.html:4:400
preparePage@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1781:11
waitExec@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1851:18
w@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:36:4123
tms_8d2c79d2_b167_4a42_92ba_36c57a5cc3c7/</z<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:36:7007
y/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:36:3296
e/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:36:482
r@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:36:339
Tt/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:36:13068
o/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:36:897
start@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1855:9
tms_8d2c79d2_b167_4a42_92ba_36c57a5cc3c7/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1858:8
tms_8d2c79d2_b167_4a42_92ba_36c57a5cc3c7@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1860:2
h</<@eval:3:75
anonymous/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:4:7
anonymous/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:5:3
anonymous@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1861:6
h</<@eval:3:75
E_c@eval:3:391
la@eval line 1 > Function:65:272
create@eval line 1 > Function:77:118
e@eval line 1 > Function:17:355

can you get something from that? i don't understand those language XD

tahnk you

**Comment by explore01** [comment]
console report earlier taken from funmanga.com

**Comment by explore01** [comment]
and this is from console taken at sensescans

Request to access cookie or storage on “<URL>” was blocked because it came from a tracker and content blocking is enabled. 41
Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/sweetalert2@8.18.0/dist/sweetalert2.min.js userscript.html:23:9
MangaOnlineViewer: Starting Manga OnlineViewer 15.03.0 on Firefox 70 with Tampermonkey 4.9.6095 userscript.html:1032:13
MangaOnlineViewer: 37 Known Manga Sites userscript.html:1032:13
MangaOnlineViewer: Looking for a match... userscript.html:1032:13
MangaOnlineViewer: Site Found: 
Object { name: "FoOlSlide", url: /^(?!.*jaiminisbox).*\/read\/.+/, homepage: "", language: (1) […], obs: "Any Scanlator site that uses FoOLSlide", category: "manga", run: run()
 }
userscript.html:1032:13
MangaOnlineViewer: Found 21 pages userscript.html:1032:13
ERROR: Execution of script 'Manga OnlineViewer' failed! Swal is not defined userscript.html:4:400
preparePage@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1781:11
waitExec@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1851:18
w@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:36:4123
tms_8d2c79d2_b167_4a42_92ba_36c57a5cc3c7/</z<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:36:7007
y/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:36:3296
e/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:36:482
r@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:36:339
Tt/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:36:13068
o/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:36:897
start@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1855:9
tms_8d2c79d2_b167_4a42_92ba_36c57a5cc3c7/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1858:8
tms_8d2c79d2_b167_4a42_92ba_36c57a5cc3c7@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1860:2
h</<@eval:3:75
anonymous/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:4:7
anonymous/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:5:3
anonymous@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1861:6
h</<@eval:3:75
E_c@eval:3:391
la@eval line 1 > Function:64:272
create@eval line 1 > Function:76:118
e@eval line 1 > Function:16:355
userscript.html:4:486
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified

**Comment by TagoDR** [comment]
Your browser failed to load one of the required scripts (https://cdn.jsdelivr.net/npm/sweetalert2@8.18.0/dist/sweetalert2.min.js).
Check you connection, adblock and antivirus/firewall.

**Comment by explore01** [comment]
adblock - off
windows defender - off
firewall - off

accessing funmanga
here is the console

Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/sweetalert2@8.18.0/dist/sweetalert2.min.js userscript.html:23:9
MangaOnlineViewer: Starting Manga OnlineViewer 15.03.0 on Firefox 70 with Tampermonkey 4.9.6095 userscript.html:1032:13
MangaOnlineViewer: 37 Known Manga Sites userscript.html:1032:13
MangaOnlineViewer: Looking for a match... userscript.html:1032:13
MangaOnlineViewer: Site Found: 
Object { name: "Funmanga", url: /https?:\/\/(www.)?funmanga.com\/.+\/[0-9]+/, homepage: "http://funmanga.com/", language: (1) […], category: "manga", run: run()
 }
userscript.html:1032:13
MangaOnlineViewer: Found 9 pages userscript.html:1032:13
ERROR: Execution of script 'Manga OnlineViewer' failed! Swal is not defined userscript.html:4:400
preparePage@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1781:11
waitExec@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1851:18
w@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:36:4123
tms_8d2c79d2_b167_4a42_92ba_36c57a5cc3c7/</z<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:36:7007
y/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:36:3296
e/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:36:482
r@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:36:339
Tt/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:36:13068
o/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:36:897
start@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1855:9
tms_8d2c79d2_b167_4a42_92ba_36c57a5cc3c7/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1858:8
tms_8d2c79d2_b167_4a42_92ba_36c57a5cc3c7@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1860:2
h</<@eval:3:75
anonymous/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:4:7
anonymous/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:5:3
anonymous@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscript.html?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1861:6
h</<@eval:3:75
E_c@eval:3:391
la@eval line 1 > Function:65:272
create@eval line 1 > Function:77:118
e@eval line 1 > Function:17:355
userscript.html:4:486
Request to access cookie or storage on “<URL>” was blocked because it came from a tracker and content blocking is enabled. 25
Request to access cookie or storage on “https://w.sharethis.com/button/buttons.js” was blocked because it came from a tracker and content blocking is enabled.
125
Request to access cookie or storage on “https://ws.sharethis.com/button/async-buttons.js” was blocked because it came from a tracker and content blocking is enabled.
125
Request to access cookie or storage on “https://ws.sharethis.com/button/css/buttons-secure.css” was blocked because it came from a tracker and content blocking is enabled.
125
Request to access cookie or storage on “https://ws.sharethis.com/images/2017/facebook_16.png” was blocked because it came from a tracker and content blocking is enabled.
1
Request to access cookie or storage on “https://ws.sharethis.com/images/2017/googleplus_16.png” was blocked because it came from a tracker and content blocking is enabled.
1
Request to access cookie or storage on “https://ws.sharethis.com/images/2017/tumblr_16.png” was blocked because it came from a tracker and content blocking is enabled.
1
Request to access cookie or storage on “https://ws.sharethis.com/images/2017/twitter_16.png” was blocked because it came from a tracker and content blocking is enabled.
1
Request to access cookie or storage on “https://ws.sharethis.com/images/2017/pinterest_16.png” was blocked because it came from a tracker and content blocking is enabled.
1
Request to access cookie or storage on “https://ws.sharethis.com/images/2017/email_16.png” was blocked because it came from a tracker and content blocking is enabled.
1
Request to access cookie or storage on “https://l.sharethis.com/pview?event=pview&version=buttons.js…ight%20Sculptor%20Chapter%20125&ts1575487055073.0=&sop=false” was blocked because it came from a tracker and content blocking is enabled.
2 1
Request to access cookie or storage on “https://l.sharethis.com/sc?cm=ZGgAAl3oBlAAAAASYSb9Aw%3D%3D&u…Bol&publisher=65f299a0-bf85-4ea3-ac23-08134a018cba&sop=false” was blocked because it came from a tracker and content blocking is enabled.
1
Request to access cookie or storage on “https://ws.sharethis.com/secure5x/index.html” was blocked because it came from a tracker and content blocking is enabled.
2 1
Request to access cookie or storage on “https://ws.sharethis.com/secure5x/index.html” was blocked because it came from a tracker and content blocking is enabled.
1:25:133
Request to access cookie or storage on “https://ws.sharethis.com/secure5x/js/stcommon.1f60705adac788a51a8240cf535237b0.js” was blocked because it came from a tracker and content blocking is enabled.
1
Request to access cookie or storage on “https://ws.sharethis.com/secure5x/js/st.e9bdabe010179964815c31077bb3095b.js” was blocked because it came from a tracker and content blocking is enabled.
1
Request to access cookie or storage on “https://ws.sharethis.com/secure5x/index.html” was blocked because it came from a tracker and content blocking is enabled.
1:63:423939
Request to access cookie or storage on “https://ws.sharethis.com/secure5x/index.html” was blocked because it came from a tracker and content blocking is enabled.
1:1:4561
Request to access cookie or storage on “https://l.sharethis.com/sc?cm=ZGgAAl3oBlAAAAASYSb9Aw%3D%3D&u…Bol&publisher=65f299a0-bf85-4ea3-ac23-08134a018cba&sop=false” was blocked because it came from a tracker and content blocking is enabled.
1
Request to access cookie or storage on “https://t.sharethis.com/1/d/t.dhj?rnd=1575487057178&cid=c010…9__3z3_9phP78k89r7337Ew-v-3o8LzBAI&gdpr_domain=.consensu.org” was blocked because it came from a tracker and content blocking is enabled.
2 1
Request to access cookie or storage on “https://t.sharethis.com/a/t_.htm?ver=0.321.15995&cid=c010#rn…8qUKwIkSeAQkpoN1tR1gDtgjL_RcnjvSnabLZg&cc=ID&cont=AS&ipaddr=” was blocked because it came from a tracker and content blocking is enabled.
2 1
Request to access cookie or storage on “https://t.sharethis.com/a/t_.htm?ver=0.321.15995&cid=c010#rn…8qUKwIkSeAQkpoN1tR1gDtgjL_RcnjvSnabLZg&cc=ID&cont=AS&ipaddr=” was blocked because it came from a tracker and content blocking is enabled.
1:25:133
Request to access cookie or storage on “https://t.sharethis.com/a/t_.htm?ver=0.321.15995&cid=c010#rn…8qUKwIkSeAQkpoN1tR1gDtgjL_RcnjvSnabLZg&cc=ID&cont=AS&ipaddr=” was blocked because it came from a tracker and content blocking is enabled.
1:63:423939
Request to access cookie or storage on “https://t.sharethis.com/a/t_.htm?ver=0.321.15995&cid=c010#rn…8qUKwIkSeAQkpoN1tR1gDtgjL_RcnjvSnabLZg&cc=ID&cont=AS&ipaddr=” was blocked because it came from a tracker and content blocking is enabled.
2 1:2:73
Request to access cookie or storage on “https://t.sharethis.com/a/t_.htm?ver=0.321.15995&cid=c010#rn…8qUKwIkSeAQkpoN1tR1gDtgjL_RcnjvSnabLZg&cc=ID&cont=AS&ipaddr=” was blocked because it came from a tracker and content blocking is enabled.
1:2:754
Request to access cookie or storage on “https://t.sharethis.com/d/a.gif?aqet=priv_block_3pcookie&r=1575487058293&cid=c010” was blocked because it came from a tracker and content blocking is enabled.

**Comment by explore01** [comment]
trying to open the link from this line

Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/sweetalert2@8.18.0/dist/sweetalert2.min.js userscript.html:23:9

this is what i get

Content Encoding Error

An error occurred during a connection to cdn.jsdelivr.net.

    Please contact the website owners to inform them of this problem.

**Comment by explore01** [comment]
hi TagoDR
i don't know what happen and what changed..
i didn't set anything manually
but it seems just now, the script is working again..
i hope it will last long XD, thanks for being with us over the trouble!
