### ISSUE TITLE
Images won’t load on tmofans.com

### ISSUE THREAD

**Issue by wernser412** [TagoDR/MangaOnlineViewer#109]
Solo cargan hasta la imagen 23.

https://tmofans.com/viewer/5de01b5f63e04/paginated

![Sin título](https://user-images.githubusercontent.com/53667212/71313982-ec404b00-240e-11ea-9c21-b9bdad9dc3eb.png)

https://tmofans.com/viewer/5dfd46c05a2c9/paginated

![Sin título](https://user-images.githubusercontent.com/53667212/71313992-01b57500-240f-11ea-97f2-2d43d2dd8f79.png)

**Comment by TagoDR** [comment]
Should be fixed, I had to add delay between pages.
