### ISSUE TITLE
MOV adult is not working.

### ISSUE THREAD

**Issue by Naivra** [TagoDR/MangaOnlineViewer#11]
it didn't load on nhentai or hentai2read, maybe i'm missing something?

**Comment by TagoDR** [comment]
Please try removing the script and installing again, It should work fine now.

**Comment by Naivra** [comment]
still not working, i try it on both tempermonkey stable and beta. does using vpn could cause it?

**Comment by TagoDR** [comment]
It shouldn't.
Open the console with F12(most browsers) and post me what it says. It should look like this:

> Starting Manga OnlineViewer
> 23 Known Manga Sites
> Identifying Site
> Loading Batoto
> Found 30 pages
> Progress: 0%
> Site rebuild done
> Loading Images
> Method automatic
> Intervals: 1000
> Page 1
> Page 2
> [...]

**Comment by Naivra** [comment]
like this?
![image](https://user-images.githubusercontent.com/29028972/26907709-b7287b78-4c1f-11e7-8ccb-8d5688d5a700.png)

**Comment by TagoDR** [comment]
Ok, I just found a typo, and corrected it, please update and try again. Maybe reinstall the script if it does not work at once.

**Comment by Naivra** [comment]
it's working now, thanks.
