### ISSUE TITLE
Images won’t load on tmohentai.com

### ISSUE THREAD

**Issue by wernser412** [TagoDR/MangaOnlineViewer#110]
Solo cargan hasta la imagen 10

https://tmohentai.com/reader/5dfc6791deffb/paginated/1

![Sin título](https://user-images.githubusercontent.com/53667212/71314037-a041d600-240f-11ea-9231-5f0517f4ce79.png)

**Comment by TagoDR** [comment]
Should be fixed, I had to add delay between pages.

**Comment by wernser412** [comment]
the delay doesn't work for me. Check it out, please.

**Comment by TagoDR** [comment]
try increasing the delay on the settings, see if it works.
Otherwise post the script execution log, by pressing F12 before opening the page.

**Comment by wernser412** [comment]
I don't understand!

**Comment by TagoDR** [comment]
Should be Fixed now

**Comment by wernser412** [comment]
Yes, work
