### ISSUE TITLE
22hr ago update

### ISSUE THREAD

**Issue by explore01** [TagoDR/MangaOnlineViewer#111]
Hi TagoDR,
before update, the script come back working, but after last update (22 hr ago)
it won't run again on any manga site i visit..

checking console, here is what i got
Loading mixed (insecure) display content “http://hatigarmscans.net/uploads/logo.png” on a secure page
254
Loading mixed (insecure) display content “http://hatigarmscans.net/uploads/manga/tales-of-demons-and-gods/chapters/254/01.jpg” on a secure page
254
Request to access cookie or storage on “<URL>” was blocked because it came from a tracker and content blocking is enabled. 42
Loading mixed (insecure) display content “http://hatigarmscans.net/uploads/favicon.png” on a secure page
FaviconLoader.jsm:174:19
Loading mixed (insecure) display content “http://hatigarmscans.net/uploads/logo.png” on a secure page
2 254
Loading mixed (insecure) display content “http://hatigarmscans.net/uploads/manga/tales-of-demons-and-gods/chapters/254/01.jpg” on a secure page
2 254
Loading mixed (insecure) display content “http://hatigarmscans.net/uploads/manga/tales-of-demons-and-gods/chapters/254/01.jpg” on a secure page
2 jquery.plugins.js:59:2
Loading mixed (insecure) display content “http://hatigarmscans.net/uploads/manga/tales-of-demons-and-gods/chapters/254/02.jpg” on a secure page
jquery.plugins.js:59:2
Loading mixed (insecure) display content “http://hatigarmscans.net/uploads/manga/tales-of-demons-and-gods/chapters/254/03.jpg” on a secure page
jquery.plugins.js:59:2
Loading mixed (insecure) display content “http://hatigarmscans.net/uploads/manga/tales-of-demons-and-gods/chapters/254/04.jpg” on a secure page
jquery.plugins.js:59:2
Loading mixed (insecure) display content “http://hatigarmscans.net/uploads/manga/tales-of-demons-and-gods/chapters/254/01.jpg” on a secure page
2 jquery-1.11.0.min.js:4:10700
Loading failed for the <script> with source “https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js”. 1:502:1
Loading failed for the <script> with source “https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js”. 1:538:1
Loading failed for the <script> with source “https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js”. 1:558:1
Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/sweetalert2@8.18.0/dist/sweetalert2.min.js Manga OnlineViewer.user.js:19:9
MangaOnlineViewer: Starting Manga OnlineViewer 16.00.0 on Firefox 70 with Tampermonkey 4.10.6105 Manga OnlineViewer.user.js:1049:13
MangaOnlineViewer: 38 Known Manga Sites Manga OnlineViewer.user.js:1049:13
MangaOnlineViewer: Looking for a match... Manga OnlineViewer.user.js:1049:13
MangaOnlineViewer: Site Found: 
Object { name: "HatigarmScans", url: /https?:\/\/(www.)?hatigarmscans.net\/manga\/.+\/.+(\/[0-9]*)?/, homepage: "https://www.hatigarmscans.net//", language: (1) […], category: "manga", run: run()
 }
Manga OnlineViewer.user.js:1049:13
MangaOnlineViewer: Found 11 pages Manga OnlineViewer.user.js:1049:13
ERROR: Execution of script 'Manga OnlineViewer' failed! Swal is not defined Manga OnlineViewer.user.js:1:494
preparePage@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1798:11
waitExec@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1868:18
w@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:32:4123
tms_8d2c79d2_b167_4a42_92ba_36c57a5cc3c7/</z<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:32:7007
y/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:32:3296
e/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:32:482
r@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:32:339
Tt/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:32:13068
o/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:32:897
start@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1872:9
tms_8d2c79d2_b167_4a42_92ba_36c57a5cc3c7/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1875:8
tms_8d2c79d2_b167_4a42_92ba_36c57a5cc3c7@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1877:2
r</<@eval:2:491
@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1:101
@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1:701
@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1878:6
@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1880:3
r</<@eval:2:491
c@eval:2:54
E_u@eval:3:150
ja@eval line 1 > Function:59:374
create@eval line 1 > Function:70:416
d@eval line 1 > Function:13:89
Manga OnlineViewer.user.js:1:580
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).
Loading mixed (insecure) display content “http://hatigarmscans.net/uploads/manga/tales-of-demons-and-gods/chapters/254/01.jpg” on a secure page
2 jquery-1.11.0.min.js:4:10700
Loading mixed (insecure) display content “http://hatigarmscans.net/uploads/manga/tales-of-demons-and-gods/chapters/254/02.jpg” on a secure page
2 jquery-1.11.0.min.js:4:10700
Loading mixed (insecure) display content “http://hatigarmscans.net/uploads/manga/tales-of-demons-and-gods/chapters/254/04.jpg” on a secure page
2 jquery-1.11.0.min.js:4:10700
Loading mixed (insecure) display content “http://hatigarmscans.net/uploads/manga/tales-of-demons-and-gods/chapters/254/03.jpg” on a secure page
2 jquery-1.11.0.min.js:4:10700
Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/sweetalert2@8.18.0/dist/sweetalert2.min.js Manga OnlineViewer.user.js:19:9
MangaOnlineViewer: Starting Manga OnlineViewer 16.00.0 on Firefox 70 with Tampermonkey 4.10.6105 Manga OnlineViewer.user.js:1049:13
MangaOnlineViewer: 38 Known Manga Sites Manga OnlineViewer.user.js:1049:13
MangaOnlineViewer: Looking for a match... Manga OnlineViewer.user.js:1049:13
MangaOnlineViewer: Site Found: 
Object { name: "HatigarmScans", url: /https?:\/\/(www.)?hatigarmscans.net\/manga\/.+\/.+(\/[0-9]*)?/, homepage: "https://www.hatigarmscans.net//", language: (1) […], category: "manga", run: run()
 }
Manga OnlineViewer.user.js:1049:13
ERROR: Execution of script 'Manga OnlineViewer' failed! src is undefined Manga OnlineViewer.user.js:1:494
run@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:268:19
waitExec@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1868:24
w@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:32:4123
tms_8d2c79d2_b167_4a42_92ba_36c57a5cc3c7/</z<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:32:7007
y/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:32:3296
e/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:32:482
r@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:32:339
Tt/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:32:13068
o/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:32:897
start@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1872:9
tms_8d2c79d2_b167_4a42_92ba_36c57a5cc3c7/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1875:8
tms_8d2c79d2_b167_4a42_92ba_36c57a5cc3c7@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1877:2
r</<@https://hatigarmscans.disqus.com/embed.js line 39 > eval:2:491
@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1:101
@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1:701
@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1878:6
@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1880:3
r</<@https://hatigarmscans.disqus.com/embed.js line 39 > eval:2:491
c@https://hatigarmscans.disqus.com/embed.js line 39 > eval:2:54
E_u@https://hatigarmscans.disqus.com/embed.js line 39 > eval:3:150
ja@https://hatigarmscans.disqus.com/embed.js line 39 > eval line 1 > Function:59:374
create@https://hatigarmscans.disqus.com/embed.js line 39 > eval line 1 > Function:70:416
d@https://hatigarmscans.disqus.com/embed.js line 39 > eval line 1 > Function:13:89
Manga OnlineViewer.user.js:1:580
Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/sweetalert2@8.18.0/dist/sweetalert2.min.js Manga OnlineViewer.user.js:19:9
MangaOnlineViewer: Starting Manga OnlineViewer 16.00.0 on Firefox 70 with Tampermonkey 4.10.6105 Manga OnlineViewer.user.js:1049:13
MangaOnlineViewer: 38 Known Manga Sites Manga OnlineViewer.user.js:1049:13
MangaOnlineViewer: Looking for a match... Manga OnlineViewer.user.js:1049:13
MangaOnlineViewer: Site Found: 
Object { name: "HatigarmScans", url: /https?:\/\/(www.)?hatigarmscans.net\/manga\/.+\/.+(\/[0-9]*)?/, homepage: "https://www.hatigarmscans.net//", language: (1) […], category: "manga", run: run()
 }
Manga OnlineViewer.user.js:1049:13
ERROR: Execution of script 'Manga OnlineViewer' failed! src is undefined Manga OnlineViewer.user.js:1:494
run@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:268:19
waitExec@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1868:24
w@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:32:4123
tms_8d2c79d2_b167_4a42_92ba_36c57a5cc3c7/</z<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:32:7007
y/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:32:3296
e/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:32:482
r@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:32:339
Tt/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:32:13068
o/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:32:897
start@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1872:9
tms_8d2c79d2_b167_4a42_92ba_36c57a5cc3c7/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1875:8
tms_8d2c79d2_b167_4a42_92ba_36c57a5cc3c7@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1877:2
r</<@https://hatigarmscans.disqus.com/embed.js line 39 > eval:2:491
@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1:101
@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1:701
@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1878:6
@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=8d2c79d2-b167-4a42-92ba-36c57a5cc3c7:1880:3
r</<@https://hatigarmscans.disqus.com/embed.js line 39 > eval:2:491
c@https://hatigarmscans.disqus.com/embed.js line 39 > eval:2:54
E_u@https://hatigarmscans.disqus.com/embed.js line 39 > eval:3:150
ja@https://hatigarmscans.disqus.com/embed.js line 39 > eval line 1 > Function:59:374
create@https://hatigarmscans.disqus.com/embed.js line 39 > eval line 1 > Function:70:416
d@https://hatigarmscans.disqus.com/embed.js line 39 > eval line 1 > Function:13:89
Manga OnlineViewer.user.js:1:580
Loading mixed (insecure) display content “http://hatigarmscans.net/uploads/manga/tales-of-demons-and-gods/chapters/254/01.jpg” on a secure page
2 jquery.plugins.js:59:2
Loading mixed (insecure) display content “http://hatigarmscans.net/uploads/manga/tales-of-demons-and-gods/chapters/254/02.jpg” on a secure page
2 jquery.plugins.js:59:2
Loading mixed (insecure) display content “http://hatigarmscans.net/uploads/manga/tales-of-demons-and-gods/chapters/254/03.jpg” on a secure page
2 jquery.plugins.js:59:2
Loading mixed (insecure) display content “http://hatigarmscans.net/uploads/manga/tales-of-demons-and-gods/chapters/254/04.jpg” on a secure page
2 jquery.plugins.js:59:2
Loading mixed (insecure) display content “http://hatigarmscans.net/uploads/manga/tales-of-demons-and-gods/chapters/254/05.jpg” on a secure page
jquery.plugins.js:59:2
Loading mixed (insecure) display content “http://hatigarmscans.net/uploads/manga/tales-of-demons-and-gods/chapters/254/02.jpg” on a secure page
2 jquery-1.11.0.min.js:4:10700
Loading mixed (insecure) display content “http://hatigarmscans.net/uploads/manga/tales-of-demons-and-gods/chapters/254/01.jpg” on a secure page
2 jquery-1.11.0.min.js:4:10700
Loading mixed (insecure) display content “http://hatigarmscans.net/uploads/manga/tales-of-demons-and-gods/chapters/254/02.jpg” on a secure page
2 jquery-1.11.0.min.js:4:10700
Loading mixed (insecure) display content “http://hatigarmscans.net/uploads/manga/tales-of-demons-and-gods/chapters/254/03.jpg” on a secure page
2 jquery-1.11.0.min.js:4:10700
Loading mixed (insecure) display content “http://hatigarmscans.net/uploads/manga/tales-of-demons-and-gods/chapters/254/04.jpg” on a secure page
2 jquery-1.11.0.min.js:4:10700
Loading mixed (insecure) display content “http://hatigarmscans.net/uploads/manga/tales-of-demons-and-gods/chapters/254/05.jpg” on a secure page

**Comment by TagoDR** [comment]
Remove and install  the script again, next time using it allow cross server access

**Comment by explore01** [comment]
removed, and reinstalled, but still not working

just notice that there is this line on console
Request to access cookie or storage on “https://stats.g.doubleclick.net/r/collect?v=1&aip=1&t=dc&_r=…_gid=470949529.1575656169&gjid=914483854&_v=j79&z=1664210596” was blocked because it came from a tracker and content blocking is enabled.
i've tried to disabled it on the manga site that i visit, but script still not working..

here is the last log after i turn off cookie access blocker
Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/sweetalert2@8.18.0/dist/sweetalert2.min.js Manga OnlineViewer.user.js:19:9
MangaOnlineViewer: Starting Manga OnlineViewer 16.01.0 on Firefox 70 with Tampermonkey 4.10.6105 Manga OnlineViewer.user.js:1050:13
MangaOnlineViewer: 38 Known Manga Sites Manga OnlineViewer.user.js:1050:13
MangaOnlineViewer: Looking for a match... Manga OnlineViewer.user.js:1050:13
MangaOnlineViewer: Site Found: 
Object { name: "MangaDex", url: /https?:\/\/(www.)?mangadex.org\/chapter\/.+(\/.+)?/, homepage: "https://mangadex.org/", language: (1) […], category: "manga", waitEle: ".total-pages", waitAttr: (2) […], run: run()
 }
Manga OnlineViewer.user.js:1050:13
MangaOnlineViewer: Wating for src of .reader-image-wrapper img = undefined Manga OnlineViewer.user.js:1050:13
MangaOnlineViewer: Wating for src of .reader-image-wrapper img = undefined Manga OnlineViewer.user.js:1050:13
MangaOnlineViewer: Wating for src of .reader-image-wrapper img = undefined Manga OnlineViewer.user.js:1050:13
MangaOnlineViewer: Wating for src of .reader-image-wrapper img = https://s0.mangadex.org/data/ac298232d7db1c3e21eb1b9d8611c1f8/T1.jpg Manga OnlineViewer.user.js:1050:13
MangaOnlineViewer: Waiting for .total-pages = [object HTMLSpanElement] Manga OnlineViewer.user.js:1050:13
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ eval line 2 > eval:3:80629
MangaOnlineViewer: Found 25 pages Manga OnlineViewer.user.js:1050:13
ReferenceError: Swal is not defined

**Comment by TagoDR** [comment]
> Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/sweetalert2@8.18.0/dist/sweetalert2.min.js
> ReferenceError: Swal is not defined

Yes, clear your browser cache, check you firewall and adblock, your browser is failing to fetch one of the requires scripts.
Sometime ago it happened with another person here, it was his connection, one day it suddenly solved itself.
