### ISSUE TITLE
manganelo.com not opening MangaOnlineViewer

### ISSUE THREAD

**Issue by mini890** [TagoDR/MangaOnlineViewer#112]
As the title says, the UserScript does not work on manganelo.com

While checking the Developer Tools, on the Console it prints

MangaOnlineViewer: Starting Manga OnlineViewer 16.01.0 on Chrome 79 with Tampermonkey 4.9
MangaOnlineViewer: 38 Known Manga Sites
MangaOnlineViewer: Looking for a match...
MangaOnlineViewer: Site Found:
{
name: Array(2),
url: /https?:\/\/(www.)?(manganelo|mangakakalot).com\/chapter\/.+\/.+/,
homepage: ["https://mangakakalot.com/page", "http://www.manganelo.com/"],
language: ["English"],
category: "manga",
run: run() { const images = $('#vungdoc img').get(); return { title: $('.info-top-chapter h2').text().trim(), series: $('.rdfa-breadcrumb a span[itemprop="title"]').eq(1).parent().attr('href'), quant: images.length, prev: $('.btn-navigation-chap a:eq(0)').attr('href'), next: $('.btn-navigation-chap a:eq(1)').attr('href'), listImages: images.map(i => {…}
}

MangaOnlineViewer: Found 0 pages

At the end. It says it doesn't found any pages. What I noticed is that some mangakalot mangas are redirecting to manganelo so people can't read on mangakalot where the extension works.

Tested using Chrome and Firefox

Specs:
Windows 10 Pro X64
Google Chrome 79.0.3945.88 using Tampermonkey v4.9
Firefox 68 68.3.0esr using Tampermonkey and Greasemonkey

**Comment by TagoDR** [comment]
Fixed it
