### ISSUE TITLE
hentainexus does not work using violentmonkey on chrome

### ISSUE THREAD

**Issue by ramenchef** [TagoDR/MangaOnlineViewer#115]
Browser: Version 79.0.3945.88 (Official Build) (64-bit)
OS: Windows 10
extension: ViolentMonkey 2.12.4
Issue: I cannot get your script to work on hentainexus using violentmonkey. Switching to tampermonkey works. Some debugging steps I have tried include adding console log messages to the script. Logging "W" (window variable) shows its properties fine, but I get undefined when doing console.log(W.baseTitle), which matches the console error. I can run the same command in the browser console and get the correct title. I tried appending "$( document ).ready" to the base function, but ran into the same issue.

This is the error I am receiving. 

"Uncaught TypeError: Cannot read property 'replace' of undefined
    at Object.run (Manga OnlineViewer Adult.user.js:375)"

I tried other websites which your script utilizes window properties to populate the data, such as hentai2read, but those work fine. It is odd that hentainexus does not work the same way using violentmonkey and I cannot figure out why.

Using the bookmarklet does work.

**Comment by TagoDR** [comment]
The only thing I can imagine is violentmonkey  triggering too fast, even before "baseTitle" gets created.
Try manually starting the script after the page looks complete, just to be sure.
If it is the case there may be a setting to run the script delayed I don't know.
