### ISSUE TITLE
webcomic reader bug?

### ISSUE THREAD

**Issue by CoLdAs1cE** [TagoDR/MangaOnlineViewer#123]
seen this a few times be4 not sure if its a bug or just something wrong with images.
[webcomic reader bug?](https://imgur.com/a/e6dCUQz)
https://www.mngdoom.com/wu-dao-du-zun/136/1

**Comment by TagoDR** [comment]
that image is really 3px in height, someone crazy cut the pages that way.
It looks weird because it is too small, All I can do is make it look less weird
