### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by explore01** [TagoDR/MangaOnlineViewer#125]
Hi Tago still same issue with last time i posted, not solved by itself
the one you told me that the issue solved itself might be me, and then it happen again, and got no fix till now..

it was like this..

Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/sweetalert2@8.18.0/dist/sweetalert2.min.js Manga OnlineViewer.user.js:19:9
MangaOnlineViewer: Starting Manga OnlineViewer 16.12.0 on Firefox 70 with Tampermonkey 4.10.6105 Manga OnlineViewer.user.js:1070:13
MangaOnlineViewer: 39 Known Manga Sites Manga OnlineViewer.user.js:1070:13
MangaOnlineViewer: Looking for a match... Manga OnlineViewer.user.js:1070:13
MangaOnlineViewer: Site Found: 
Object { name: "Funmanga", url: /https?:\/\/(www.)?funmanga.com\/.+\/[0-9]+/, homepage: "http://funmanga.com/", language: (1) […], category: "manga", run: run()
 }
Manga OnlineViewer.user.js:1070:13
MangaOnlineViewer: Found 11 pages Manga OnlineViewer.user.js:1070:13
ERROR: Execution of script 'Manga OnlineViewer' failed! Swal is not defined Manga OnlineViewer.user.js:1:494
preparePage@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=c2471cc4-ef33-47ec-8c8d-506daeb418d9:1811:11
waitExec@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=c2471cc4-ef33-47ec-8c8d-506daeb418d9:1881:18
w@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=c2471cc4-ef33-47ec-8c8d-506daeb418d9:32:4123
tms_c2471cc4_ef33_47ec_8c8d_506daeb418d9/</z<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=c2471cc4-ef33-47ec-8c8d-506daeb418d9:32:7007
y/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=c2471cc4-ef33-47ec-8c8d-506daeb418d9:32:3296
e/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=c2471cc4-ef33-47ec-8c8d-506daeb418d9:32:482
r@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=c2471cc4-ef33-47ec-8c8d-506daeb418d9:32:339
Tt/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=c2471cc4-ef33-47ec-8c8d-506daeb418d9:32:13068
o/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=c2471cc4-ef33-47ec-8c8d-506daeb418d9:32:897
start@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=c2471cc4-ef33-47ec-8c8d-506daeb418d9:1885:9
tms_c2471cc4_ef33_47ec_8c8d_506daeb418d9/<@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=c2471cc4-ef33-47ec-8c8d-506daeb418d9:1888:8
tms_c2471cc4_ef33_47ec_8c8d_506daeb418d9@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=c2471cc4-ef33-47ec-8c8d-506daeb418d9:1890:2
r</<@eval:2:491
@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=c2471cc4-ef33-47ec-8c8d-506daeb418d9:1:101
@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=c2471cc4-ef33-47ec-8c8d-506daeb418d9:1:701
@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=c2471cc4-ef33-47ec-8c8d-506daeb418d9:1891:6
@moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga%20OnlineViewer.user.js?id=c2471cc4-ef33-47ec-8c8d-506daeb418d9:1893:3
r</<@eval:2:491
c@eval:2:54
E_u@eval:3:150
ja@eval line 1 > Function:59:374
create@eval line 1 > Function:70:416
d@eval line 1 > Function:13:89

**Comment by explore01** [comment]
i tried to visit
https://cdn.jsdelivr.net/npm/sweetalert2@8.18.0/dist/sweetalert2.min.js
can't visit
i tried the link on chrome, it visitable

i;ve tried allowing cookies, tracking content, and even allowing pop up, but nothing happen so far

and red typo is on this line:
ERROR: Execution of script 'Manga OnlineViewer' failed! Swal is not defined Manga OnlineViewer.user.js:1:494
    <anonymous> moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga OnlineViewer.user.js?id=c2471cc4-ef33-47ec-8c8d-506daeb418d9:1
    <anonymous> moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga OnlineViewer.user.js?id=c2471cc4-ef33-47ec-8c8d-506daeb418d9:1
    <anonymous> moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga OnlineViewer.user.js?id=c2471cc4-ef33-47ec-8c8d-506daeb418d9:1891
    <anonymous> moz-extension://92eaa7d6-3979-469d-9171-c330971d4f47/userscripts/Manga OnlineViewer.user.js?id=c2471cc4-ef33-47ec-8c8d-506daeb418d9:1893
    r eval:2
    c eval:2
    E_u eval:3
    ja eval line 1 > Function:59
    create eval line 1 > Function:70
    d eval line 1 > Function:13

**Comment by explore01** [comment]
with mozila, trying to access
 https://cdn.jsdelivr.net/npm/sweetalert2@8.18.0/dist/sweetalert2.min.js

give me this page

Content Encoding Error

An error occurred during a connection to cdn.jsdelivr.net.

    Please contact the website owners to inform them of this problem.

**Comment by explore01** [comment]
i even have tried to disable every add-on i have, but nothing works

**Comment by TagoDR** [comment]
Try this:
Open tampermokey, go to edit the script
Find all ocurrances of
`https://cdn.jsdelivr.net/npm/sweetalert2@8.18.0/dist/`
`https://cdn.jsdelivr.net/npm/sweetalert2@8.16.1/dist/`
and replace for this
`https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/`

**Comment by explore01** [comment]
done...
still not working

this is in console

Tampermonkey: couldn't load @require from URL https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/8.11.8/sweetalert2.min.js Manga OnlineViewer.user.js:19:9
MangaOnlineViewer: Starting Manga OnlineViewer 16.12.0 on Firefox 70 with Tampermonkey 4.10.6105 Manga OnlineViewer.user.js:1070:13
MangaOnlineViewer: 39 Known Manga Sites Manga OnlineViewer.user.js:1070:13
MangaOnlineViewer: Looking for a match... Manga OnlineViewer.user.js:1070:13
MangaOnlineViewer: Site Found: 
Object { name: "Funmanga", url: /https?:\/\/(www.)?funmanga.com\/.+\/[0-9]+/, homepage: "http://funmanga.com/", language: (1) […], category: "manga", run: run()
 }
Manga OnlineViewer.user.js:1070:13
MangaOnlineViewer: Found 18 pages Manga OnlineViewer.user.js:1070:13
ERROR: Execution of script 'Manga OnlineViewer' failed! Swal is not defined Manga OnlineViewer.user.js:1:494
preparePage@moz-extension://29f15d12-40cf-4d93-81d9-154c36b185d7/userscripts/Manga%20OnlineViewer.user.js?id=824f90cb-1803-465c-af79-53a7fa801fdb:1811:11
waitExec@moz-extension://29f15d12-40cf-4d93-81d9-154c36b185d7/userscripts/Manga%20OnlineViewer.user.js?id=824f90cb-1803-465c-af79-53a7fa801fdb:1881:18
w@moz-extension://29f15d12-40cf-4d93-81d9-154c36b185d7/userscripts/Manga%20OnlineViewer.user.js?id=824f90cb-1803-465c-af79-53a7fa801fdb:32:4123
tms_824f90cb_1803_465c_af79_53a7fa801fdb/</z<@moz-extension://29f15d12-40cf-4d93-81d9-154c36b185d7/userscripts/Manga%20OnlineViewer.user.js?id=824f90cb-1803-465c-af79-53a7fa801fdb:32:7007
y/<@moz-extension://29f15d12-40cf-4d93-81d9-154c36b185d7/userscripts/Manga%20OnlineViewer.user.js?id=824f90cb-1803-465c-af79-53a7fa801fdb:32:3296
e/<@moz-extension://29f15d12-40cf-4d93-81d9-154c36b185d7/userscripts/Manga%20OnlineViewer.user.js?id=824f90cb-1803-465c-af79-53a7fa801fdb:32:482
r@moz-extension://29f15d12-40cf-4d93-81d9-154c36b185d7/userscripts/Manga%20OnlineViewer.user.js?id=824f90cb-1803-465c-af79-53a7fa801fdb:32:339
Tt/<@moz-extension://29f15d12-40cf-4d93-81d9-154c36b185d7/userscripts/Manga%20OnlineViewer.user.js?id=824f90cb-1803-465c-af79-53a7fa801fdb:32:13068
o/<@moz-extension://29f15d12-40cf-4d93-81d9-154c36b185d7/userscripts/Manga%20OnlineViewer.user.js?id=824f90cb-1803-465c-af79-53a7fa801fdb:32:897
start@moz-extension://29f15d12-40cf-4d93-81d9-154c36b185d7/userscripts/Manga%20OnlineViewer.user.js?id=824f90cb-1803-465c-af79-53a7fa801fdb:1885:9
tms_824f90cb_1803_465c_af79_53a7fa801fdb/<@moz-extension://29f15d12-40cf-4d93-81d9-154c36b185d7/userscripts/Manga%20OnlineViewer.user.js?id=824f90cb-1803-465c-af79-53a7fa801fdb:1888:8
tms_824f90cb_1803_465c_af79_53a7fa801fdb@moz-extension://29f15d12-40cf-4d93-81d9-154c36b185d7/userscripts/Manga%20OnlineViewer.user.js?id=824f90cb-1803-465c-af79-53a7fa801fdb:1890:2
r</<@eval:2:491
@moz-extension://29f15d12-40cf-4d93-81d9-154c36b185d7/userscripts/Manga%20OnlineViewer.user.js?id=824f90cb-1803-465c-af79-53a7fa801fdb:1:101
@moz-extension://29f15d12-40cf-4d93-81d9-154c36b185d7/userscripts/Manga%20OnlineViewer.user.js?id=824f90cb-1803-465c-af79-53a7fa801fdb:1:701
@moz-extension://29f15d12-40cf-4d93-81d9-154c36b185d7/userscripts/Manga%20OnlineViewer.user.js?id=824f90cb-1803-465c-af79-53a7fa801fdb:1891:6
@moz-extension://29f15d12-40cf-4d93-81d9-154c36b185d7/userscripts/Manga%20OnlineViewer.user.js?id=824f90cb-1803-465c-af79-53a7fa801fdb:1893:3
r</<@eval:2:491
c@eval:2:54
E_u@eval:3:150
ja@eval line 1 > Function:59:374
create@eval line 1 > Function:70:416
d@eval line 1 > Function:13:89
Manga OnlineViewer.user.js:1:580

what could be hindering my firefox to access that address? *confused

**Comment by TagoDR** [comment]
edit the script again.
After the header line 70, before the script proper, insert all the contents of the file below
https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/sweetalert2.min.js 

PS: you replaced it wrong https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/**8.11.8**/sweetalert2.min.js  the bold part shouldn't be there

**Comment by explore01** [comment]
oh wow, i remove double version number, and your script start working again! thanks a lot!

After the header line 70, before the script proper, insert all the contents of the file below
https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/sweetalert2.min.js
so this text will be in line 70
and what used to be line 70 become line 71 ?

**Comment by explore01** [comment]
thanks for always being around patching up the script! i really love your works!
