### ISSUE TITLE
[suggestion/feedback] add option for <-- and --> to take you to the next page instead of next chapter || also a fit to height option would be cool too

### ISSUE THREAD

**Issue by xerance** [TagoDR/MangaOnlineViewer#126]
title, would be really convenient for people to prefer season the whole page but want to preload all the images in a gallery.

-----

fit to height would be useful for some cases too for lowering the amount of scrolling you need to do without changing the zoom level manually.

**Comment by TagoDR** [comment]
Add fit/zoom to height and scroll to pages (W & S)
