### ISSUE TITLE
Error while download

### ISSUE THREAD

**Issue by trueneko** [TagoDR/MangaOnlineViewer#127]
An error occurred while downloading and the downloaded image was corrupt in the .rar format, even though I was using a good signal. This happened when I downloaded on nhen
[(100%) Tasogare no Shou Elf 5.zip](https://github.com/TagoDR/MangaOnlineViewer/files/4447377/100.Tasogare.no.Shou.Elf.5.zip)

**Comment by TagoDR** [comment]
there is little a can do about it. there are other sites you may try
