### ISSUE TITLE
Small issues with ExHentai / E-Hentai autostarting and incomplete gallery

### ISSUE THREAD

**Issue by himouto** [TagoDR/MangaOnlineViewer#132]
Whenever I view a gallery / thumbnails on exhentai.org the script autostarts unlike in other sites where it only starts when I open an image. Also the script only loads the images from gallery page 1.

Please disable autostarting when only viewing thumbs on exhentai/e-hentai, the script should only start when you click on an image. Thanks.

**Comment by TagoDR** [comment]
These sites are a special case, many galleries are over 300 pages, and they will ban you if you load too many images too fast. Its one of the few sites I impose a delay between images.
I use the thumbnails pagination as chapters to buffer, it helps to protect people.
You can just cancel the script start to read the gallery information.

**Comment by TagoDR** [comment]
Just made a breakthrough, should be better now.
