### ISSUE TITLE
Nhentai is not working.

### ISSUE THREAD

**Issue by dudeedud4** [TagoDR/MangaOnlineViewer#133]
As stated in the title, it seems to not load on nhentai anymore. I can see it in the userscript menu as being activated, but it is not showing up at all.

**Comment by TagoDR** [comment]
It is working just fine. Try reinstalling it, check everything for updates.
Press F12 look on the console and post here if you cant make it work.

**Comment by dudeedud4** [comment]
Reinstalled, Chrome, Violent Monkey, and the userscript are all updated to the latest.

Can't send a console log or screenshot because they are constantly spamming console.clear() :/

**Comment by TagoDR** [comment]
Then change to tampermokey
