### ISSUE TITLE
mangadex url to get images should be changed!

### ISSUE THREAD

**Issue by CoLdAs1cE** [TagoDR/MangaOnlineViewer#135]
i sometimes get http://mangadex.org or http://www.mangadex.org and www.mangadex dont work
```
const url = "https://mangadex.org/api/chapter/".concat(W.location.pathname.match(/[0-9]+/)[0]);
```
but if i do this
```
const url = W.location.origin + "/api/chapter/".concat(W.location.pathname.match(/[0-9]+/)[0]);
```
both no www and www works. dunno why this happens i type mangadex.org in address bar :O

to much work changing url on many tabs after i relise this

**Comment by TagoDR** [comment]
location.origin  is redundant, implicit , and unnecessary,
