### ISSUE TITLE
ExHentai problem

### ISSUE THREAD

**Issue by botist** [TagoDR/MangaOnlineViewer#143]
The image loader only loads images from the first gallery page on Exhentai. I don't know why you did this exactly, but if its to protect against bans I'd love if you could make it just load like... 10 pages? and then when the user reaches the last loaded page, it loads 10 more and etc like this older script https://sleazyfork.org/en/scripts/12657-manga-loader-nsfw

**Comment by TagoDR** [comment]
You gave me and Idea, just improved lazy loading , now e-hentai will be better
