### ISSUE TITLE
[Site Meta-request] List of Manga sites to check

### ISSUE THREAD

**Issue by DonaldTsang** [TagoDR/MangaOnlineViewer#149]
Here are some "lists of manga sites" that might be useful to check the coverage of the plugin.
- https://github.com/manga-download/hakuneko/wiki/Comparison
- https://manga-py.com/
- https://github.com/eight04/ComicCrawler#supported-domains
- https://github.com/riderkick/FMD/wiki/Websites

**Comment by DonaldTsang** [comment]
Cross-reference https://github.com/fuzetsu/manga-loader/issues/69

**Comment by TagoDR** [comment]
You are welcome to send Pull request do widen the script coverage.
