### ISSUE TITLE
[nsfw] pururin.us

### ISSUE THREAD

**Issue by grotedraak** [TagoDR/MangaOnlineViewer#15]
Manga OnlineViewer Adult 13.6.0 on Firefox 57 with Tampermonkey 4.4.5484
link: `http://pururin.us/read/30743/01/english-class-with-shinpo-san`
actually it only 4 pages but while reading we see 13 pages total and waiting for download but not downloading.

thanks

**Comment by TagoDR** [comment]
I was not able to reproduce your bug, it might have been a connection instability.
