### ISSUE TITLE
Add support to vermangasporno.com (NSFW)

### ISSUE THREAD

**Issue by wernser412** [TagoDR/MangaOnlineViewer#156]
https://vermangasporno.com/

**Comment by wernser412** [comment]
@TagoDR 
https://vercomicsporno.com/j-max-japan-kono-koukando-nara-sorosoro-harem-ikerun-ja-ne

**Comment by TagoDR** [comment]
added

**Comment by wernser412** [comment]
@TagoDR 
It doesn't work (Return to Chapter List)

https://vercomicsporno.com/mientras-papi-duerme-2-original-vcp

![2021-05-26_154108](https://user-images.githubusercontent.com/53667212/120902123-34076200-c604-11eb-9fde-71bfe5d57c16.png)

**Comment by TagoDR** [comment]
There is no separation for the gallery and pages on this site, It's how it should be, reload the page and don't start the script if you need to see that page
