### ISSUE TITLE
mangadex REexecute script when ch is changed 

### ISSUE THREAD

**Issue by RootAndroid58** [TagoDR/MangaOnlineViewer#158]
when a ch loades and without waiting for 3 sec timer and go to next ch through mangadex controls does not reload the page so the script doesn't change its previously loaded data so is there a possibility when an url change event is added to the script only for mangadex something like it will check if the https://mangadex.org/chapter/7****5/** it will check if 7****5 is same as loaded one when url is changed 

well sry for bad english 🤔

**Comment by TagoDR** [comment]
Should just work now
