### ISSUE TITLE
Script doesn't work on mangasee123.com's first and last chapter

### ISSUE THREAD

**Issue by K-WAN** [TagoDR/MangaOnlineViewer#159]
![chrome_yg8PCtlV2e](https://user-images.githubusercontent.com/9993600/97093725-aa101780-1678-11eb-98c7-e9718e8c8486.png)
![chrome_M0LpBURsv2](https://user-images.githubusercontent.com/9993600/97093765-07a46400-1679-11eb-936f-f8cf1f6dce61.jpg)

**Comment by TagoDR** [comment]
Should be fine now
