### ISSUE TITLE
[nsfw] hentaifox.com

### ISSUE THREAD

**Issue by grotedraak** [TagoDR/MangaOnlineViewer#16]
Manga OnlineViewer Adult 13.6.0 on Firefox 57 with Tampermonkey 4.4.5484
`https://hentaifox.com/g/45691/`
page full complete, but downloading got 8KB zip file all image was corrupt

thanks

**Comment by TagoDR** [comment]
Yes downloading seems to be broken I'll look into it.

**Comment by TagoDR** [comment]
The download button is working again, however not on every site. I'm still looking for why it down corrupts the files in different sites.

**Comment by TagoDR** [comment]
Found the problem, it should be fixed now
