### ISSUE TITLE
Images broken on mangadex.org

### ISSUE THREAD

**Issue by SvenKott** [TagoDR/MangaOnlineViewer#164]
Hello,
my script stopped working on mangadex. I'm currently using the latest FF version but tried the same with Chrome with the same results. I can manually browse and read mangadex without issues.

Here is my console log:
<details>
  <summary>Console Log</summary>
MangaOnlineViewer:  Starting Manga OnlineViewer 18.18.0 on Firefox 84 with Violentmonkey 2.12.8 Manga OnlineViewer.user.js:863:13
MangaOnlineViewer:  31 Known Manga Sites Manga OnlineViewer.user.js:863:13
MangaOnlineViewer:  Looking for a match... Manga OnlineViewer.user.js:863:13
MangaOnlineViewer:  Site Found: 
Object { name: "MangaDex", url: /https?:\/\/(www.)?mangadex.org\/chapter\/.+(\/.+)?/, homepage: "https://mangadex.org/", language: (1) […], category: "manga", waitEle: ".total-pages", waitAttr: (2) […], run: run()
 }
Manga OnlineViewer.user.js:863:13
MangaOnlineViewer:  Wating for src of .reader-image-wrapper img = undefined Manga OnlineViewer.user.js:863:13
MangaOnlineViewer:  Wating for src of .reader-image-wrapper img = undefined Manga OnlineViewer.user.js:863:13
MangaOnlineViewer:  Wating for src of .reader-image-wrapper img = https://dva8yv9xq2dm8.rmhkd98sb0x3y.mangadex.network/9s5g988…WxOVXm3_OKP5vps/data/64dbcc3e22698db545aab08aed953cc5/G1.png Manga OnlineViewer.user.js:863:13
MangaOnlineViewer:  Waiting for .total-pages = [object HTMLSpanElement] Manga OnlineViewer.user.js:863:13
Synchrone XMLHttpRequests am Haupt-Thread sollte nicht mehr verwendet werden, weil es nachteilige Effekte für das Erlebnis der Endbenutzer hat. Für weitere Hilfe siehe http://xhr.spec.whatwg.org/ 1 line 1 > injectedScript:2:81766
MangaOnlineViewer:  Found 19 pages Manga OnlineViewer.user.js:863:13
MangaOnlineViewer:  Rebuilding Site Manga OnlineViewer.user.js:863:13
Uncaught TypeError: can't delete property '"jQuery35109075308837535021"': proxy deleteProperty handler returned false
    remove moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:2
    empty moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:2
    c moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:2
    fireWith moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:2
    fire moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:2
    dequeue moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:2
    complete moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:2
    c moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:2
    fireWith moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:2
    u moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:2
    tick moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:2
    st moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:2
    start moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:2
    timer moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:2
    ft moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:2
    a moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:2
    dequeue moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:2
    queue moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:2
    each moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:2
    each moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:2
    queue moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:2
    animate moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:2
    k moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:29
    scrollTo moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:29
    each moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:2
    each moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:2
    scrollTo moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:29
    formatPage moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:1605
    formatPage moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:1604
    formatPage moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:1600
    preparePage moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:1674
    promise callback*value moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:18
    preparePage moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:1672
    waitExec moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:1735
    waitExec moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:1707
    waitExec moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:1706
    waitExec moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:1707
    waitExec moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:1706
    x moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:21
    D moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:21
    y moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:21
    t moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:21
    t moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:21
    It moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:21
    f moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:21
    start moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:1739
    VMin0c29l2itq moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:1742
    VMin0c29l2itq moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:1744
    VMin0c29l2itq moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:1745
    VMin0c29l2itq moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:1745
    b moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/sandbox/injected-web.js:1
    set moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/sandbox/injected-web.js:1
    <anonymous> moz-extension://7cbddda8-1daf-47fd-948b-6894c8015dfd/ Manga OnlineViewer.user.js#2:1
1 line 1 > injectedScript:2:33524
</details>
Thanks in advance!

**Comment by TagoDR** [comment]
Its working just fine, you could try:
- Cheking your connection,
- Reinstall the script
- use Tampermonkey
