### ISSUE TITLE
Add support for toonily.net

### ISSUE THREAD

**Issue by RootAndroid58** [TagoDR/MangaOnlineViewer#165]
- [ ] https://toonily.net/
this one is one is like kissmanga which maintains all the mangas it shows with timely updates hope it gets added soon there are many ch that are not available in manganelo too like [this in manganelo](https://manganelo.com/manga/bi924026) and [this in toonily.net](https://toonily.net/manga/here-lies-the-wicked/)

**Comment by TagoDR** [comment]
Added
