### ISSUE TITLE
HentaiNexus still doesn't work?

### ISSUE THREAD

**Issue by longxa762** [TagoDR/MangaOnlineViewer#167]
I'm using latest version Adult version (18.19.0), clicking on Start MangaOnlineViewer just show blank images.

![image](https://user-images.githubusercontent.com/14937488/104457609-62a58180-55fe-11eb-9f12-558db0de859c.png)

**Comment by TagoDR** [comment]
It is working, use F12 to see the console log, post it here.
I looks like it's your connection the isn't working.

**Comment by longxa762** [comment]
Cookie “__cf_bm” will be soon treated as cross-site cookie against “https://hentainexus.com/read/9644#001” because the scheme does not match. 2 9644
Cookie “__cf_bm” will be soon treated as cross-site cookie against “https://hentainexus.com/static/js/main.js” because the scheme does not match. main.js
Cookie “__cf_bm” will be soon treated as cross-site cookie against “https://hentainexus.com/static/fonts/ubuntu-sans.css” because the scheme does not match. ubuntu-sans.css
Cookie “__cf_bm” will be soon treated as cross-site cookie against “https://hentainexus.com/static/css/main.css?r=3” because the scheme does not match. main.css
Cookie “__cf_bm” will be soon treated as cross-site cookie against “https://hentainexus.com/static/js/reader.min.js?r=15” because the scheme does not match. reader.min.js
Cookie “__cf_bm” will be soon treated as cross-site cookie against “https://hentainexus.com/static/js/smoothscroll.min.js” because the scheme does not match. smoothscroll.min.js
Cookie “__cf_bm” will be soon treated as cross-site cookie against “https://hentainexus.com/static/css/bulmaswatch.min.css” because the scheme does not match. bulmaswatch.min.css
Cookie “__cf_bm” will be soon treated as cross-site cookie against “https://hentainexus.com/static/js/keyboard.min.js” because the scheme does not match. keyboard.min.js
MangaOnlineViewer:  Starting Manga OnlineViewer Adult 18.19.0 on Firefox 84 with Violentmonkey 2.12.8 Manga OnlineViewer Adult.user.js:691:13
MangaOnlineViewer:  24 Known Manga Sites Manga OnlineViewer Adult.user.js:691:13
MangaOnlineViewer:  Looking for a match... Manga OnlineViewer Adult.user.js:691:13
MangaOnlineViewer:  Site Found: 
Object { name: "HentaiNexus", url: /https?:\/\/(www.)?hentainexus.com\/read\/.+/, homepage: "https://hentainexus.com/", language: (1) […], category: "hentai", waitVar: "baseTitle", run: run() }
Manga OnlineViewer Adult.user.js:691:13
MangaOnlineViewer:  Wating for baseTitle = undefined Manga OnlineViewer Adult.user.js:691:13
Cookie “__cf_bm” will be soon treated as cross-site cookie against “https://hentainexus.com/favicon.ico” because the scheme does not match. favicon.ico
Cookie “__cf_bm” will be soon treated as cross-site cookie against “https://hentainexus.com/static/fonts/ubuntu-sans/ubuntu-v12-latin-ext_latin-regular.woff2” because the scheme does not match. ubuntu-v12-latin-ext_latin-regular.woff2
MangaOnlineViewer:  Wating for baseTitle = The Suffering of Admiral Diaz :: HentaiNexus Manga OnlineViewer Adult.user.js:691:13
MangaOnlineViewer:  Found 20 pages Manga OnlineViewer Adult.user.js:691:13
Cookie “__cf_bm” will be soon treated as cross-site cookie against “https://hentainexus.com/static/fonts/ubuntu-sans/ubuntu-v12-latin-ext_latin-500.woff2” because the scheme does not match. ubuntu-v12-latin-ext_latin-500.woff2
MangaOnlineViewer:  LateStart Manga OnlineViewer Adult.user.js:691:13
Cookie “__cf_bm” will be soon treated as cross-site cookie against “https://hentainexus.com/static/fonts/ubuntu-sans/ubuntu-v12-latin-ext_latin-700.woff2” because the scheme does not match. ubuntu-v12-latin-ext_latin-700.woff2
MangaOnlineViewer:  Choice: 1 Manga OnlineViewer Adult.user.js:691:13
MangaOnlineViewer:  Rebuilding Site Manga OnlineViewer Adult.user.js:691:13
Uncaught TypeError: can't delete property '"jQuery351070283826787850361"': proxy deleteProperty handler returned false
    remove moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:2
    empty moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:2
    c moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:2
    fireWith moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:2
    fire moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:2
    dequeue moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:2
    complete moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:2
    c moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:2
    fireWith moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:2
    u moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:2
    tick moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:2
    st moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:2
    start moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:2
    timer moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:2
    ft moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:2
    a moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:2
    dequeue moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:2
    queue moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:2
    each moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:2
    each moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:2
    queue moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:2
    animate moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:2
    k moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:29
    scrollTo moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:29
    each moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:2
    each moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:2
    scrollTo moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:29
    formatPage moz-extension://c5efe79f-df0d-4eee-b97b-4ef16762733e/ Manga OnlineViewer Adult.user.js#4:1433
9644:2:33524

**Comment by longxa762** [comment]
I don't think it's my connection since I can still read normally, only broken when open with MangaOnlineViewer

**Comment by longxa762** [comment]
After a bit of testing I think both version is broken for me on all sites, which I have no idea why since nothing was changed on my PC for forever. Manga Loader still work though.

**Comment by TagoDR** [comment]
It looks like one of the dependency scripts is not downloading correctly. 
You are using Violentmonky, change to Tampermonky and try again.

**Comment by longxa762** [comment]
Ah thank you, looked like something is broken with Violentmonkey latest version, installed their beta fixed it.
