### ISSUE TITLE
Please add turn on/off "toggle page controls" button at default setting

### ISSUE THREAD

**Issue by jarsang002** [TagoDR/MangaOnlineViewer#168]
The white line between page is disturb my view.
It's annoying when I have to toggle if off every time when I open a new site and there have no any default option of toggle page controls.
Can you add turn on/off "toggle page controls" default, please.

![toggle](https://user-images.githubusercontent.com/57130931/104838476-b3162b00-58ed-11eb-82d5-cb7e5a889853.PNG)

**Comment by TagoDR** [comment]
Added
