### ISSUE TITLE
Mangadex page_array issue 

### ISSUE THREAD

**Issue by RootAndroid58** [TagoDR/MangaOnlineViewer#171]
Uncaught TypeError: Cannot read property 'page_array' of null
it seems that mangadex has changed their api server json output

first thing first :
the api url is now :https://api.mangadex.org/v2/chapter/{ch-no-here}?saver=0&include=manga

Server may be 0 or 1 plz take that from url since it varies from region to region 

and the api output looks like 

`{"code":200,"status":"OK","data":{"chapter":{"id":1249293,"hash":"7004fd471507bbb01596538c4865c573","mangaId":62757,"mangaTitle":"Movies Are Real","volume":"","chapter":"22","title":"","language":"gb","groups":[{"id":6794,"name":"Tritinia Scans"}],"uploader":158729,"timestamp":1616092376,"threadId":446966,"comments":2,"views":105,"status":"OK","pages":["1-881bb99ec770e38dae68fcfb8f42655945fa3bdfe11d1895b1275cb1b07d7fee.jpg","2-cf406e35405f1e10196d8dab3912039617b5a3b5c1ee4c0234f98e378572e438.jpg","3-4f38788e200339f5eeba792368204b0a857a53651bb908c0c99b2d7fee5cf436.jpg","4-ac4c5bd6412e9b176a1260cabfd38265e2fee3b48a962249eaa28f7e32514a75.jpg","5-1ad22aec4b302a6abb45a31c2bf04ce33cb761327ccf1bb42d423a962d98d35a.jpg","6-a93081d131a5641681eacdc1cbd7ca1b47d9c34c8ef55f3cdee064d7ad550004.jpg","7-bf8de95cd0eada05d74e6d9a8b0a65eb9063c128a118775ca5184ecd8537e56f.jpg"],"server":"https:\/\/dj5jn4gz46ea6.xnvda7fch4zhr.mangadex.network:443\/0ta4JhJlAvW0l8Hur9FqSQmXFr5oqM9Xar8qJx1AoASs-JuL4vGYuDYBZ2VToxyXlrQjcMZlEebNRIFw82GUWDEgbSvBjjbWOrbY_zZ85t54Jfnd5rGzV9gVGAVMkKTeB6ne3oW8ZA3nCv6Fu5Losu4tjlT9I-xmyeXmgHH0QtuQUeBOPJvKuHFVuq9AgMDGGGUZqIWSv9dW7E47l5_Zfv3RxvIq\/data\/","serverFallback":"https:\/\/reh3tgm2rs8sr.xnvda7fch4zhr.mangadex.network\/data\/"},"manga":{"id":62757,"title":"Movies Are Real","altTitles":["\uc601\ud654\ub294 \ub9ac\uc5bc\uc774\ub2e4"],"description":"While working as a small supporting actor in a movie, Ki Man Sung has nothing else going for him.\r\nHowever, that was when ,through mysterious circumstance,  the movie set had become reality during filming.\r\nWith the sound of the director&rsquo;s cut, during that short take, he&rsquo;s not an actor but actually thrown into the events occurring, showing the pain and emotions he faces in that moment.\r\nHe can only come back if he creates that perfect take&hellip;!\r\nCan he grow to become the greatest actor?","artist":["Jaemihalgi"],"author":["AH In Jam"],"publication":{"language":"kr","status":1,"demographic":0},"tags":[2,3,8,10,34,36,78],"lastChapter":null,"lastVolume":null,"isHentai":false,"links":{"ap":"movies-are-real","mu":"178519","raw":"https:\/\/page.kakao.com\/home?seriesId=56609987"},"relations":[],"rating":{"bayesian":8.76,"mean":9.18,"users":186},"views":22932,"follows":2334,"comments":59,"lastUploaded":1616092376,"mainCover":"https:\/\/mangadex.org\/images\/manga\/62757.jpg"}}}`

i tried to do that but i didnt get where the image url is made since its something like : `blob:https://mangadex.org/36912a6f-2eda-4a16-87a0-dedefe679a0e` what is blob idk 

idk where `36912a6f-2eda-4a16-87a0-dedefe679a0e` this part came from either in image  may be they are caching images in mangadex.org server and that is cache image url which is ofcourse temp 

some ideas in mind 
you can pick all images with `data-page` child image url or idk really :(

**Comment by TagoDR** [comment]
You were in the right track, but It's already fixed, just update.
