### ISSUE TITLE
Add Support for comickiba, isekaiscan, manhuaus, asurascans, reaperscans

### ISSUE THREAD

**Issue by RootAndroid58** [TagoDR/MangaOnlineViewer#172]
- [ ] https://comickiba.com/
- [ ] https://isekaiscan.com/
- [ ] https://manhuaus.com/
- [ ] https://www.asurascans.com/
- [ ] https://reaperscans.com/
- [ ] https://flamescans.org/

Thanks in Advance I will also try to help but i got a qus can u tell me how u select all images i tried it lets say can u give me an example from isekaiscans i tried it but i wasent able to get all img scr attr

like i tried by copying the selector of the element and ....
`$('body > div.wrap > div > div > div > div > div > div > div > div.main-col-inner > div.c-blog-post > div.entry-content > div > div > div.reading-content > div > img').attr("data-src")`
here i got for last img since its not each 
but i tired to map it like 
`$('body > div.wrap > div > div > div > div > div > div > div > div.main-col-inner > div.c-blog-post > div.entry-content > div > div > div.reading-content > div ').map(img => console.log(img))`
and its returning only id or number of images

**Comment by TagoDR** [comment]
Added them All
