### ISSUE TITLE
asurascans.com next issue

### ISSUE THREAD

**Issue by RootAndroid58** [TagoDR/MangaOnlineViewer#174]
in https://www.asurascans.com/ when we arrive at last ch there is a disabled btn with url like
`https://www.asurascans.com/chapter-something-something-80/#/next` instead of leaving it blank is it possible to disable the next btn for link like this 
or you can just check if the 1st segment of current url is equal to 1st segment of next btn 
thanks in advance

**Comment by TagoDR** [comment]
shoould be fine now
