### ISSUE TITLE
Problem on multporn.net

### ISSUE THREAD

**Issue by wernser412** [TagoDR/MangaOnlineViewer#177]
https://multporn.net/hentai_manga/aah_aqua_sama

**Comment by TagoDR** [comment]
I dont see any problem

**Comment by wernser412** [comment]
@TagoDR 
![Sin título](https://user-images.githubusercontent.com/53667212/116792707-f012c180-aa87-11eb-90d8-747c0f4184c3.png)

Chrome 90.0.4430.93 / Windows 7

**Comment by TagoDR** [comment]
It is not my script fault, Juicebox the widget the site uses to show its images, It is not loading correctly,
Unfortunately I need it working to pull the images from its API, check your internet connection something is getting blocked, if you have and ad blocker you may need to whitelist this site.
