### ISSUE TITLE
[Feature] Checkbox to remove all the colored borders (Chapter, panel, thumbnail, everything)

### ISSUE THREAD

**Issue by frykauf** [TagoDR/MangaOnlineViewer#178]
It's not just me, many initially discard this User Script as old, ugly and useless because of the borders.

Even in webcomic mode reading a webcomic/manhwa you still have the colored border separating 2 images, it's just unacceptable by any user running into that.

Thankfully it's easy to disable in code (well written userscript), but most users won't do that, they'll GTFO immediately if they encounter that problem. Which is a shame, because it's up there as the best manga reader extension/userscript around. 
I for one enjoy it more than All Mangas Reader.

**Comment by TagoDR** [comment]
Added a fully customizable theme, check it out.
