### ISSUE TITLE
[Feature] User customizable shortcuts.

### ISSUE THREAD

**Issue by frykauf** [TagoDR/MangaOnlineViewer#179]
For example I added vim like j/k scrolling for more ergonomic scrolling.

Also removing up/down key work makes it work better with browser extensions like https://chrome.google.com/webstore/detail/smooth-key-scroll/gphmhpfbknciemgfnfhjapilmcaecljh

There are many reasons why one would want to edit the shortcuts. Even though they are already really well setup already.

**Comment by TagoDR** [comment]
Added
