### ISSUE TITLE
Feature Req: Read from right and read from left mode

### ISSUE THREAD

**Issue by fayumot** [TagoDR/MangaOnlineViewer#18]
Is it possible to adopt the read from right or left mode available in this script?
[Manga OnlineViewer Fluid Mode](https://sleazyfork.org/en/scripts/10000-manga-onlineviewer-fluid-mode)
(I think the above script is a fork of your script)

Thanks

**Comment by TagoDR** [comment]
I thought about about it, When I have time I'll try.

**Comment by TagoDR** [comment]
I have added the Fluid mode, but I believe it could be better, I'll  research some more.
