### ISSUE TITLE
Add support to ver-comics-porno.com (NSFW)

### ISSUE THREAD

**Issue by wernser412** [TagoDR/MangaOnlineViewer#186]
https://ver-comics-porno.com/boruto-erotic-adventure-yutto-prime/

**Comment by wernser412** [comment]
added?

**Comment by TagoDR** [comment]
yes

**Comment by wernser412** [comment]
> yes


check it please

**Comment by TagoDR** [comment]
Exactly "ver-comics-porno.com" does not exist, is dead or is inaccessible, "vercomicsporno.com" however is fine and was added
