### ISSUE TITLE
bato.to url with underscore not loading correctly

### ISSUE THREAD

**Issue by fayumot** [TagoDR/MangaOnlineViewer#19]
As it says on the title it seems like the the script cant load images from bato.to that has and underscore in them.
e.g. https://bato.to/reader#7d5ec828034e08c7_2

Thanks

**Comment by TagoDR** [comment]
The under line should only happen when you try to launch the script in a page other than the first.
My script must assume you let it run on the first page, some sites it may work on any page thou.
The true link for that chapter is https://bato.to/reader#7d5ec828034e08c7  the "_2" means page 2.

That said, I have fix it.
