### ISSUE TITLE
add a site. please. ->  manhuascan.com 

### ISSUE THREAD

**Issue by Pancakes0** [TagoDR/MangaOnlineViewer#195]
please add manhuascan.com
my fav md alt 
thank you. good day.

**Comment by RootAndroid58** [comment]
i have seen this theme which site it was just tell TagoDR that he will just add the website i think this theme is added not the website

**Comment by Pancakes0** [comment]
i wouldnt know what theme this is 😆. sites called  manhuascan.com ' v ' )b

**Comment by TagoDR** [comment]
Added
