### ISSUE TITLE
no [Next] button on asurascan.com 

### ISSUE THREAD

**Issue by Pancakes0** [TagoDR/MangaOnlineViewer#197]
i was reading "https://www.asurascans.com/solo-leveling-chapter-159/" next button isnt on MOV (mangaOnlineViewer) but its there in the site.

**Comment by Pancakes0** [comment]
[previous] buttons there if youre wondering 
![Screen Shot 2021-08-16 at 1 39 42 PM](https://user-images.githubusercontent.com/73923883/129736109-9fcec7ca-130c-433e-8462-ea9065afb3b8.png)

**Comment by TagoDR** [comment]
I can't replicate your error. Try updating the script and browser

**Comment by Pancakes0** [comment]
> I can't replicate your error. Try updating the script and browser

its back now, i read solo leveling till 162 (without button) but now its back i just checked. dont know what happened 
![Screen Shot 2021-08-17 at 10 36 33 PM](https://user-images.githubusercontent.com/73923883/129746206-f629fd0e-f90b-4dc2-b63a-0da3790e545f.png)
reading "I Grow Stronger By Eating! Chapter 2" and its fine  
thank you
