### ISSUE TITLE
work just great before update, after update, not working anymore

### ISSUE THREAD

**Issue by explore01** [TagoDR/MangaOnlineViewer#20]
your script has made my life much more easier for reading manga online. really appreciate your hardwork on this! but recently i found issues:

issues:
before the update of the script, it works just fine to me, both MOV and MOV-AS
found the older version script for MOV, rolled it back and it works again, until now (i set the update to off since then).
just now i experience the same thing with MOV-AS
been tryin on nhentai, pururin, hentai2read.. not working
i tried to roll back the version but i just can't find the older script

been exploring around, and found that you might need me to post what showed on console, so here they are
Direction is now 2 combined.d06901050de2.js:3:16741
Switching to page 1 combined.d06901050de2.js:3:19233
Preloading page 2 combined.d06901050de2.js:3:17374
Preloading page 3 combined.d06901050de2.js:3:17374
Preloading page 4 combined.d06901050de2.js:3:17374
MangaOnlineViewer: Starting Manga OnlineViewer Adult 13.16.1 on Firefox 47 with Greasemonkey 3.11 Manga_OnlineViewer_Adult.user.js:43:39
MangaOnlineViewer: 12 Known Manga Sites Manga_OnlineViewer_Adult.user.js:43:39
MangaOnlineViewer: Looking for a match... Manga_OnlineViewer_Adult.user.js:43:39
MangaOnlineViewer: Site Found: Object { name: "nHentai", url: /https?:\/\/(www.)?nhentai.net\/g\/.+\/.+/, homepage: "https://nhentai.net/", language: Array[1], category: "hentai", run: run() } Manga_OnlineViewer_Adult.user.js:43:39
MangaOnlineViewer: Found 17 pages Manga_OnlineViewer_Adult.user.js:43:39
Inventory responded with Object { name: "popcash", delta: 21390112 } combined.d06901050de2.js:3:14176

i hope you can find the fix, thanks a lot!
Riz

**Comment by TagoDR** [comment]
I need more information, what is it you see that is not working.
When I test it works just fine. And from the console log you posted it should be working.

One thing thou, Greasemonkey may have become incompatible with my script, I cant pinpoint where/when. Please migrate to Tampermonkey

**Comment by explore01** [comment]
thanks for kind reply,
okay then, greasemonkey terminated, and tampermonkey is on the stage :D

here is the console then
Direction is now 2 combined.d06901050de2.js:3:16741
Switching to page 1 combined.d06901050de2.js:3:19233
TypeError: Da is not a function
 %20line%201%20%3E%20Function:67:148
Preloading page 2 combined.d06901050de2.js:3:17374
Preloading page 3 combined.d06901050de2.js:3:17374
Preloading page 4 combined.d06901050de2.js:3:17374

what i see is the page didn;t pop anything (like showing if we want to load MOV or cancel it, given like 3 seconds of time to choose.). Website interface didn't change at all as if we visit the web without any script.
i tried to read the script, and pretty soon i gave up, can;t understand the program /script language *lol*

looking forward to some direction, thank you!

**Comment by TagoDR** [comment]
the script is not triggering on the url you are trying it on, please link me the url you are tring to read, and try on other sites as well.

**Comment by explore01** [comment]
okay, here some page i tried just now

http://www.hbrowse.com/20434/c00001
https://nhentai.net/g/210328/1/
http://pururin.us/read/31568/01/fuko-no-konsui-rape-seicho-kiroku-father-daughter-unconscious-rape-the-development-records
https://doujins.com/rjwuu88z

each one of them showing that a script is running on the page, here screenshot
https://ibb.co/cid7vb

**Comment by TagoDR** [comment]
Tampermonkey isnt even starting it could mean one of your browser extensions may be conflicting with it.
Try Disabling everything but Tampermonkey, also try forcing it to update.

**Comment by explore01** [comment]
solved, updated firefox, and tampermonkey automaticly updated as well, and then viola your script is coming back to rockin!
thanks a lot for your patience and kind guidance :D

**Comment by explore01** [comment]
solved, updated firefox, and tampermonkey automaticly updated as well, and then viola your script is coming back to rockin!
thanks a lot for your patience and kind guidance :D
