### ISSUE TITLE
Mangadex not Working

### ISSUE THREAD

**Issue by Shem13** [TagoDR/MangaOnlineViewer#203]
The script is no longer working on mangadex.

**Comment by TagoDR** [comment]
Fixed

**Comment by Shem13** [comment]
It doesn't seem to work on all chapters for example this https://mangadex.org/chapter/d8f3171a-0d58-4e36-b8c0-79c8fdbb8f5e

**Comment by TagoDR** [comment]
Please force update the script, it should be working.

**Comment by Shem13** [comment]
I just tested it and it seems you need to set the reader to long strip mode for the script to work. Also the return to chapter list is not working.
