### ISSUE TITLE
[nsfw] exhentai.org

### ISSUE THREAD

**Issue by underthes** [TagoDR/MangaOnlineViewer#21]
The class name to get the list of images on the exhentai is "gdtl", while for e-hentai is "gdtm". But in the script for exentai and e-hentai use same class "gdtm" that causes exentai failed to load.

**Comment by TagoDR** [comment]
I was not able to confirm it, I didn't find "gdtl" used in any of the sites.

**Comment by underthes** [comment]
I have tried to open exhentai with this script, but the view is still the same even after 10 minutes. I'm still sure the problem is the gdtm class in exhentai. I've tried to modify the script by splitting the script between "exentai" with "e-hentai" and the result works fine. 

`  var exhentai = {
    name: 'ExHentai',
    url: /https?:\/\/exhentai.org\/g\/.+\/.+/,
    homepage: 'https://exhentai.org/',
    language: ['English'],
    obs: 'May get your IP Banned, use with moderation',
    category: 'hentai',
    run() {
      return {
        title: $('#gn').text().trim(),
        series: '#',
        quant: $('.gdtl a').get().length,
        prev: $('.ptt td:first a').attr('href'),
        next: $('.ptt td:last a').attr('href'),
        listPages: $('.gdtl a').get().map(item => $(item).attr('href')),
        img: '#img',
        timer: 3000
      };
    }
  };

  var e_hentai = {
    name: 'e-Hentai',
    url: /https?:\/\/(g.)?e-hentai.org\/g\/.+\/.+/,
    homepage: 'https://e-hentai.org/',
    language: ['English'],
    obs: 'May get your IP Banned, use with moderation',
    category: 'hentai',
    run() {
      return {
        title: $('#gn').text().trim(),
        series: '#',
        quant: $('.gdtm a').get().length,
        prev: $('.ptt td:first a').attr('href'),
        next: $('.ptt td:last a').attr('href'),
        listPages: $('.gdtm a').get().map(item => $(item).attr('href')),
        img: '#img',
        timer: 3000
      };
    }
  };

  var sites = [doujinmoe, exhentai, e_hentai,
    hbrowse, hentai2read, hentaifox, hentaihere, hitomi, luscious, nhentai, pururin, simplyhentai, tsumino
  ];
`
i do not know where I should change the script in this git, so i put it here.

**Comment by underthes** [comment]
When I use this script in opera, it work just fine, but not in firefox. I have tried to open exhentai with this script, but the view is still the same even after 10 minutes. I've tried to modify the script by splitting the script between exhentai with e-hentai and it's work. I don't know why, but look like exhentai return gdtl class in firefox browser.

```
 var exhentai = {
    name: 'ExHentai',
    url: /https?:\/\/exhentai.org\/g\/.+\/.+/,
    homepage: 'https://exhentai.org/',
    language: ['English'],
    obs: 'May get your IP Banned, use with moderation',
    category: 'hentai',
    run() {
      return {
        title: $('#gn').text().trim(),
        series: '#',
        quant: $('.gdtl a').get().length,
        prev: $('.ptt td:first a').attr('href'),
        next: $('.ptt td:last a').attr('href'),
        listPages: $('.gdtl a').get().map(item => $(item).attr('href')),
        img: '#img',
        timer: 3000
      };
    }
  };

  var e_hentai = {
    name: 'e-Hentai',
    url: /https?:\/\/(g.)?e-hentai.org\/g\/.+\/.+/,
    homepage: 'https://e-hentai.org/',
    language: ['English'],
    obs: 'May get your IP Banned, use with moderation',
    category: 'hentai',
    run() {
      return {
        title: $('#gn').text().trim(),
        series: '#',
        quant: $('.gdtm a').get().length,
        prev: $('.ptt td:first a').attr('href'),
        next: $('.ptt td:last a').attr('href'),
        listPages: $('.gdtm a').get().map(item => $(item).attr('href')),
        img: '#img',
        timer: 3000
      };
    }
  };

  var sites = [doujinmoe, exhentai, e_hentai,
    hbrowse, hentai2read, hentaifox, hentaihere, hitomi, luscious, nhentai, pururin, simplyhentai, tsumino
  ];

```

**Comment by TagoDR** [comment]
I'm still not able to confirm it, but it does not hurt to add the class to the script, if you still having problems after updating just reopen this issue.

**Comment by underthes** [comment]
your solution is better. I did not expect that just adding a gdtl class was enough
