### ISSUE TITLE
Uncaught (in promise) ReferenceError: _inherits is not defined

### ISSUE THREAD

**Issue by RootAndroid58** [TagoDR/MangaOnlineViewer#212]
I have included the log hope it helps 
`// @version 20.20.0`

What I tried:
1) remove the Adult Script and install it again ( but for some reason it says reinstall IDK why there are no other instance of if script and i did check there are no other manga readers )  
2) tried overwriting the script by reinstalling same version 

[hentai2read.com-1639314703948.log](https://github.com/TagoDR/MangaOnlineViewer/files/7698777/hentai2read.com-1639314703948.log)

**Comment by RootAndroid58** [comment]
the script worked perfectly till last version

**Comment by TagoDR** [comment]
please update and try again, should be fine now
