### ISSUE TITLE
Is there anyway to manually add websites on your own?

### ISSUE THREAD

**Issue by VoDanh777** [TagoDR/MangaOnlineViewer#213]
It would be much easier if I can just do it on my own everytime a site change its domain or add a completely new one

**Comment by TagoDR** [comment]
Every site has their own way to hide the information needed to grab the images, You will need to learn how to code JavaScript. In doing so you can submit new sites, the script is modular and simple to just add new stuff, the hard part is study each site go garb what is needed.
