### ISSUE TITLE
hentaifox.com broken

### ISSUE THREAD

**Issue by himouto** [TagoDR/MangaOnlineViewer#219]
starts the loader but just shows small grey boxes for the pages 
![Screenshot 2022-04-27 095954](https://user-images.githubusercontent.com/14362301/165423203-049b8a26-02f5-48cb-92d1-ba98429a9229.png)

**Comment by himouto** [comment]
inb4 others say just use nhentai or sadpanda/exhentai

there are some really good stuffs on hentaifox that can't be found or got expunged on those two other sites

**Comment by TagoDR** [comment]
Should be Fixed now
