### ISSUE TITLE
Problem with load image on E-hentai site

### ISSUE THREAD

**Issue by Beji-kun** [TagoDR/MangaOnlineViewer#221]
When I open and click on OK
![image](https://user-images.githubusercontent.com/63636174/167741785-d3f051f6-a48c-424d-934d-e5256ec6fcd3.png)
and I have only one page load other not :/
![image](https://user-images.githubusercontent.com/63636174/167741823-d64a2d85-8d5f-4476-b55b-09a2dddef8c8.png)

**Comment by TagoDR** [comment]
Should be Fine now

**Comment by Beji-kun** [comment]
I still have problem. Where update__? Still not work :(
