### ISSUE TITLE
next butten doesn't show up on asurascans.com 

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#224]
![_](https://user-images.githubusercontent.com/100969549/172160550-4660ad53-401a-42fe-b807-0cf732750751.png)
![__](https://user-images.githubusercontent.com/100969549/172160575-3ea8d2a9-c5f1-44bd-bd9e-e4637ce9de3d.png)

Crome version
Version 102.0.5005.61 (Developer Build, ungoogled-chromium) (64-Bit)

**Comment by TagoDR** [comment]
I was not able to reproduce your problem, however I found a bug while investigating this my be the cause for you, please force update and try again.
