### ISSUE TITLE
Suggestion about file extension in downloading 

### ISSUE THREAD

**Issue by Naivra** [TagoDR/MangaOnlineViewer#23]
when i tried to save 1 image using right click it was saved as JPEG, but when i download it using the script it saved as PNG.  The PNG files somehow cannot be opened using my preferred image viewer. Then i tried to change it to JPEG after that my preferred image viewer able to open it.

maybe you could do some detection if the image is JPEG or PNG then download it as the detected extension, rather than make all of it PNG.

i hope you could consider my suggestion.

**Comment by TagoDR** [comment]
Should be Fixed now
