### ISSUE TITLE
Possibility to add an auto-zoom for widescreen pages

### ISSUE THREAD

**Issue by thanatossystem** [TagoDR/MangaOnlineViewer#231]
Most manga pages are horizontal and it's easy to set a decent zoom level before starting to read something without having to manually zoom in on every page individually but occasional widescreen pages break the flow since they're usually smaller and harder to read so I have to adjust the zoom for those pages specifically, which for a manga or two doesn't seem like an issue but builds up to be an annoyance over time. Can you add a feature (if it's not too much trouble) that checks if pages are double-pages or widescreen images to set a different zoom level, possibly with an adjustable setting? For example, base zoom is 125% (+10/20/30%) extra zoom for wide images. Sounds like a good idea in my head but I'll let you be the judge of that. Small sidenote, I appreciate what you do. Thanks for maintaining this awesome script!

**Comment by TagoDR** [comment]
This one is hard, today images can be huge(1400x7000px) or very small if they are old(500x700px). Judging when an image is double is not simple on the same manga there may be pages with different resolutions, specially height,  some webcomics have filler pages that are just a blank strip 10x800px, and almost all chapters have a banner or Ad that is odd sized.
Some sites or series name double pages differently but is very rare, I can't count on it.
I'm open to ideas, but for now I don't see a way.

**Comment by thanatossystem** [comment]
Fair enough, how about instead of using pixels as a measurement for them, you use the % of space on a page that's unoccupied, like this https://i.imgur.com/7fmIiXa.png ? If there's less % free space compared to the majority of pages zoom in a level or w/e

**Comment by TagoDR** [comment]
I've added a Min width for pages, check it out.

**Comment by thanatossystem** [comment]
That's great, it works as-is, doesn't seem to break anything but it doesn't

**Comment by thanatossystem** [comment]
Wrong button, my bad. It doesn't ignore normal pages. My idea was widescreen pages get the width adjustment if the height % is less than the width of normal pages
