### ISSUE TITLE
doesnt load the images 

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#238]
https://flamescans.org/1657252861-omniscient-readers-viewpoint-chapter-69/ 
And all cheapters after this point.  
(The images does load but only 5 / 40 )

**Comment by TagoDR** [comment]
They are splitting images in half vertically and horizontally, just to make things harder.
I made it work for now with a duck take solution.
If you notice the images are split, Change to Left-To-Right Mode, and it should be fine
