### ISSUE TITLE
next + Home butten doesnt work on https://flamescans.org/

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#239]
https://flamescans.org/plundering-the-heavens-chapter-0/ 
https://flamescans.org/series/plundering-the-heavens/ 
try to click on mext or home butten redects you to the same chapter

**Comment by TagoDR** [comment]
This series Chapter Zero seems to be scuffed, it's giving faulty information. I was not able to find this issue anywhere else there.
I shouldn't make a workaround for a one-off problem, There is nothing for me to fix.
