### ISSUE TITLE
Mozilla Firefox Updated, script no longer load images

### ISSUE THREAD

**Issue by explore01** [TagoDR/MangaOnlineViewer#24]
Hi there again Tago DR,
just today i got my firefox updated (automaticaly)..
since then, i found that the script still make response to the manga reader website, but it just show the number of pages, with no images loaded..
so far i tried to reinstall the script, remove and install new script...
still not working, then i remove tampermonkey as well, and reinstall it, and the script as well,
still no more progress shown other than the number of pages.. vertically.
progress bar on the top of firefox window, only move a little bit.. like less than 10% of window length...

i wonder if you had noticed this as well..
i'm looking forward to some update or any solution from you again..
thanks TagoDR!
regards,
Rizky

**Comment by TagoDR** [comment]
There is a known conflict : Ad blockers may block manga pages for some sites, and my script can't force loading them.
Other than that I can't find anything wrong, its working just fine. You may try forcing update everything, If the error continues open the console with F12 and show me what its says after you try reading chapter

**Comment by explore01** [comment]
ok, i turn off that ad blocker, still no images loaded..
i tried this page: http://www.readmanga.today/karate-shoukoushi-kohinata-minoru/447/1
so here the console says:

supertag v3.0
supertag.js:1:15047
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.
[Learn More]
1
Loading failed for the <script> with source “http://uat-net.technoratimedia.com/00/87/18/adserv_51887.js?ad_size=160x600&referrer=http%3A//www.readmanga.today/karate-shoukoushi-kohinata-minoru/447/1&nsafe=general&reftype=none&disp=none&tmiv=1&tcb=0.25128887716933923&abv=ATF”.
1:1025
Loading failed for the <script> with source “http://uat-net.technoratimedia.com/00/87/18/adserv_51887.js?ad_size=160x600&referrer=http%3A//www.readmanga.today/karate-shoukoushi-kohinata-minoru/447/1&nsafe=general&reftype=none&disp=none&tmiv=1&tcb=0.2547437259769021&abv=ATF”.
1:1031
Loading failed for the <script> with source “http://uat-net.technoratimedia.com/00/87/18/adserv_51887.js?ad_size=300x250&referrer=http%3A//www.readmanga.today/karate-shoukoushi-kohinata-minoru/447/1&nsafe=general&reftype=none&disp=none&tmiv=1&tcb=0.743587464915584&abv=BTF”.
1:1060
Loading failed for the <script> with source “http://uat-net.technoratimedia.com/00/87/18/adserv_51887.js?ad_size=300x250&referrer=http%3A//www.readmanga.today/karate-shoukoushi-kohinata-minoru/447/1&nsafe=general&reftype=none&disp=none&tmiv=1&tcb=0.7079183030818704&abv=BTF”.
1:1071
Loading failed for the <script> with source “http://uat-net.technoratimedia.com/00/87/18/adserv_51887.js?ad_size=300x250&referrer=http%3A//www.readmanga.today/karate-shoukoushi-kohinata-minoru/447/1&nsafe=general&reftype=none&disp=none&tmiv=1&tcb=0.050616496775990893&abv=BTF”.
1:1083
carouFredSel: No element found for ".slides ul".
jquery.carouFredSel-6.2.1-packed-ck.js:12:16494
MangaOnlineViewer: Starting Manga OnlineViewer 13.17.0 on Firefox 57 with Tampermonkey 4.5.5590
1%20line%203%20%3E%20Function:106:39
MangaOnlineViewer: 27 Known Manga Sites
1%20line%203%20%3E%20Function:106:39
MangaOnlineViewer: Looking for a match...
1%20line%203%20%3E%20Function:106:39
MangaOnlineViewer: Site Found: 
Object { name: "ReadManga.Today", url: /https?:\/\/(www.)?readmanga.today\/.+\/[0-9]+/, homepage: "http://www.readmanga.today/", language: […], category: "manga", run: run() }
1%20line%203%20%3E%20Function:106:39
MangaOnlineViewer: Found 21 pages
1%20line%203%20%3E%20Function:106:39
SweetAlert2: Unknown parameter "closeOnConfirm"
1%20line%203%20%3E%20Function:27:16261
MangaOnlineViewer: Progress: 0%
1%20line%203%20%3E%20Function:106:39
MangaOnlineViewer: Site rebuild done
1%20line%203%20%3E%20Function:106:39
MangaOnlineViewer: Loading Images
1%20line%203%20%3E%20Function:106:39
MangaOnlineViewer: Intervals: 1000
1%20line%203%20%3E%20Function:106:39
MangaOnlineViewer: Method: Brute Force
1%20line%203%20%3E%20Function:106:39
MangaOnlineViewer: Getting page: http://www.readmanga.today/karate-shoukoushi-kohinata-minoru/447/1/all-pages
1%20line%203%20%3E%20Function:106:39
MangaOnlineViewer: Retrying Getting page: http://www.readmanga.today/karate-shoukoushi-kohinata-minoru/447/1/all-pages
1%20line%203%20%3E%20Function:106:39
MangaOnlineViewer: Progress: 0%
1%20line%203%20%3E%20Function:106:39
MangaOnlineViewer: Retrying Getting page: http://www.readmanga.today/karate-shoukoushi-kohinata-minoru/447/1/all-pages
1%20line%203%20%3E%20Function:106:39
MangaOnlineViewer: Progress: 0%
1%20line%203%20%3E%20Function:106:39
MangaOnlineViewer: Retrying Getting page: http://www.readmanga.today/karate-shoukoushi-kohinata-minoru/447/1/all-pages
1%20line%203%20%3E%20Function:106:39
MangaOnlineViewer: Progress: 0%
1%20line%203%20%3E%20Function:106:39
MangaOnlineViewer: Progress: 0%
1%20line%203%20%3E%20Function:106:39
MangaOnlineViewer: Progress: 0%

**Comment by explore01** [comment]
update:
ad block on, and i open this page https://mangastream.com/r/neverland/064/4712/1
and i found the script is working just fine!
and sense scan reader as well.. working good with mangadoom as well..
so i think it just won't work with readmanga.today

**Comment by TagoDR** [comment]
There was really as problem with Readmanga.Today it should be fixed now.

**Comment by explore01** [comment]
woah, cool!
thanks a lot for the update!
