### ISSUE TITLE
add realmscans.com

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#240]
https://realmscans.com/ 
(have a very simple cdn for pic)  
example 
https://cdn.realmscans.com/2022/07/i-became-invincible-after-descending-chapter-9-1.webp
https://cdn.realmscans.com/2022/07/i-became-invincible-after-descending-chapter-9-2.webp

**Comment by TagoDR** [comment]
Added it, same structure as Asura/Flame Scans, Enjoy
