### ISSUE TITLE
add https://www.webtoons.com/ (very hard cdn network) 

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#241]
has viewing protection 
examples
https://webtoon-phinf.pstatic.net/20220709_10/1657319755407R41mo_JPEG/1657319755383451828.jpg?type=q90 
https://webtoon-phinf.pstatic.net/20220629_231/1656451008998YCW52_JPEG/1656451008989451820.jpg?type=q90  
https://webtoon-phinf.pstatic.net/20220629_146/1656451011059AQoiS_JPEG/1656451011045451821.jpg?type=q90

**Comment by TagoDR** [comment]
Added
