### ISSUE TITLE
add new websites (hard cdn network) 

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#242]
when you are bored add this sites 
manhuaplus.com
mangabuddy.com
mangadex.org 
shimadascans.com

**Comment by TagoDR** [comment]
1-Mandadex is supported since the beginning, must open chapter in new tab.
2-Fixed/Added manhuaplus with Madara
3- Added shimadascans
4- Added mangabuddy

**Comment by big-cat-loaf** [comment]
thanks
