### ISSUE TITLE
[Bug] mangapark.net prev/next chapter button isn't working as intended 

### ISSUE THREAD

**Issue by Jacosci** [TagoDR/MangaOnlineViewer#246]
System info:

- OS : Windows 10 Pro Version 10.0.19044 Build 19044 (64-bit)
- Browser : Chromium Version 103.0.5060.114 (64-bit)
- Userscript extension : Tampermonkey v4.16.1

Description of bug:
Pressing prev/next chapter button yield "Not Found" page.
![image](https://user-images.githubusercontent.com/10607576/181746547-8806d4a0-a0e6-4317-9a83-66c82b11e875.png)

**Comment by TagoDR** [comment]
Fixed
