### ISSUE TITLE
Large→Normal？

### ISSUE THREAD

**Issue by lhj5426** [TagoDR/MangaOnlineViewer#248]
https://user-images.githubusercontent.com/30548000/183793488-c03e97ff-331b-4bbf-b9be-962ddff22aa1.mp4

**Comment by TagoDR** [comment]
Fixed it, when using large it will be slower to load because it will need to get double the amount of blocks of images.

**Comment by lhj5426** [comment]
> Fixed it, when using large it will be slower to load because it will need to get double the amount of blocks of images.

Can the settings be modified?

I don't really care about the speed, it's just the big picture preview is convenient

now after each run

It will become a small picture, which is very inconvenient when looking at the next gallery.
