### ISSUE TITLE
can load all at once

### ISSUE THREAD

**Issue by lhj5426** [TagoDR/MangaOnlineViewer#249]
Now it loads more than ten pages and twenty pages, it stops loading
Need to manually scroll to a loaded page to continue loading
Can be set or how to set the script to load all at once
 without pause

**Comment by lhj5426** [comment]
Now it's loading a little, then stop
Must scroll manually before continuing to load
I don't want this, I want to open the page and load it a little by myself
No need to manually scroll to load

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/184495000-21eeb9cb-4c2b-4ab6-ab29-ce48f0489d7b.png)
So if I don't scroll down the page, this 100% will never be 100% even if I put it there to load for 1 day
Is it possible to slowly autoload to 100%?

**Comment by TagoDR** [comment]
ExHentai and e-Hentai are sites with huge galleries, many times 500+ images.
I've heard that they will ip ban you if you open too many images too fast, so I try to protect my users by making lazy required in these sites.
If you want to take the risk, you have 2 options:
1- In the settings, increase the Minimum pages to load before lazy loading starts. Default is 50, you can double that.
2- open the code, search for ExHentai and change "lazy: true" to false, around line 165. This would need to be changed after every update.

**Comment by lhj5426** [comment]
> ExHentai and e-Hentai are sites with huge galleries, many times 500+ images. I've heard that they will ip ban you if you open too many images too fast, so I try to protect my users by making lazy required in these sites. If you want to take the risk, you have 2 options: 1- In the settings, increase the Minimum pages to load before lazy loading starts. Default is 50, you can double that. 2- open the code, search for ExHentai and change "lazy: true" to false, around line 165. This would need to be changed after every update.

yes i will try

**Comment by lhj5426** [comment]
The effect is very good, as long as you switch to the tab, it will keep loading, no longer like before the feedback, each tab has to manually scroll the page to continue loading

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/184522460-218af6d2-4830-49f9-bb15-bd7d2c852393.png)

https://user-images.githubusercontent.com/30548000/184522466-b55cbad8-d050-49f0-9e66-815d13bcf39c.mp4

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/184522529-8751b576-0c13-4d9f-b581-cf0430845956.png)
MTHML is also easy to read. Open directly is to use the script loaded scroll reading method to open directly in the browser

**Comment by TagoDR** [comment]
Browsers do not agree on how mhtml(mht) should work yet, some don't support it even with extensions.
The script has a download feature you can use it, if after downloading you need a reader for zip images I recommend https://github.com/luejerry/html-mangareader

**Comment by lhj5426** [comment]
> Browsers do not agree on how mhtml(mht) should work yet, some don't support it even with extensions. The script has a_ download _feature you can use it, if after downloading you need a reader for zip images I recommend https://github.com/luejerry/html-mangareader

Chrome and various modified versions can open MHTML without any obstacles
 this. . There should be no problem with opening it. I hope developers can consider adding a webpage to automatically or manually save it as mhtml

In fact, the main problem is not to view the problem, but to consume GB for download and not to consume GB for online viewing.

After loading is equal to downloading, save it as mhtml for easy viewing

Although the viewer you recommend is very good, consider that the download needs to consume GB

I still hope that developers can consider adding an mhtml download function.
