### ISSUE TITLE
[Chrome, Tampermonkey] New update (v13.19.0) broke the script

### ISSUE THREAD

**Issue by el0d** [TagoDR/MangaOnlineViewer#25]
The script was working fine before, the issue started happening after the update.
The script starts up as per usual and the usual interface is there but the pages/images never load.

I've tested the script on 5 websites. 4 of them(batoto, kissmanga, mangareader, foolslide) had the issue above, but at the 5th website, readmanga.today the pages actually loaded. 
So I am guessing the script only works at readmanga.today and nowhere else.

I hope you'll look into the issue, thanks.

**Comment by TagoDR** [comment]
Thank you, I fixed somethings earlier and broke another. It should be fine now.
