### ISSUE TITLE
Default View Mode Doesn't work 

### ISSUE THREAD

**Issue by polt515** [TagoDR/MangaOnlineViewer#250]
When I change the default viewer mode, nothing happens

**Comment by TagoDR** [comment]
I've restored it

**Comment by polt515** [comment]
I'm still having the same problems as before with the new update .

**Comment by TagoDR** [comment]
What do you mean by default view mode then? The settings are not saving?
Now the default view mode is Web comic, if you want the gab between pages again you need to change the settings to Vertical.

**Comment by polt515** [comment]
The problem is that my default view is set to right-to-left view but it will always stay in the Comic View by default

**Comment by polt515** [comment]
![image](https://user-images.githubusercontent.com/107204156/185631518-572797a3-1321-411e-b4a1-9006c50f2463.png)

**Comment by TagoDR** [comment]
I see it now, Should be Fix now
