### ISSUE TITLE
Setting Scroll

### ISSUE THREAD

**Issue by Pancakes0** [TagoDR/MangaOnlineViewer#251]
i cant seem scroll down on settings
![screenshot](https://user-images.githubusercontent.com/73923883/185778584-132a8cbc-bfa5-40af-9057-9415cd1c9284.png)
s

**Comment by TagoDR** [comment]
Should be Fixed now

**Comment by TagoDR** [comment]
Which site did it not work on? did you check after there was indeed a next chapter?
Try other keys for next chapter like 'D', 'Numpad6' or 'period'.

**Comment by Pancakes0** [comment]
setsuscans.com, there was a next chapter because i was able to click the next button using the cursor and it works. 
i did try arrows, a-d, number, and ,-. but got no results

**Comment by Pancakes0** [comment]
oh nvm, forget it, i dont know what happened but i think its my device? yesterday i shut it down and now when i try to go next it works? idk if it was because if the laptop or that i quit the browser. sorry for taking your time
