### ISSUE TITLE
Fit height button also stretching width of image (adult)

### ISSUE THREAD

**Issue by CoLdAs1cE** [TagoDR/MangaOnlineViewer#255]
I just noticed this now because somehow my old script wouldn't update but when i did i noticed it (i updated it yesterday)
new gives also gives with when you do fit height, old i think only gave u height (or kept it proportional when fit height)😢  
this is old script
![image](https://user-images.githubusercontent.com/1981573/189521109-901e5ded-12a2-4f5b-862e-9fb556eaa622.png)
this is new script
![image](https://user-images.githubusercontent.com/1981573/189521140-1bad17c9-3e6d-4d39-8bab-41de61cb3d4a.png)
something is wrong as you can see 😢 
Ofc i tried to find what did it 😄 
seems like reponsive thing
```
#MangaOnlineViewer .PageContent .PageImg {
  min-width: 50vw;
}
```
css over did it  i think

**Comment by TagoDR** [comment]
I've found a small math error that would make the height 4 px too short.
But the difference in width I don't see it, please try going into the setting and resetting it. See if it still has this problem

**Comment by TagoDR** [comment]
May have fixed it please try

**Comment by CoLdAs1cE** [comment]
Sorry for late replay but that worked 😄 it gave it a some width :)
