### ISSUE TITLE
Old UI feature request

### ISSUE THREAD

**Issue by Pancakes0** [TagoDR/MangaOnlineViewer#257]
HI, There was once a feature from the old UI version where at the bottom of the screen there is a bar and when you hover on the bar it expands into viewing every chapters. 
Question, Is the feature removed or (if it isnt) is there a way to toggle it back on? if it is removed, i would like to make a request of that feature being optional (in the settings) if possible. 
Thank you!!

**Comment by TagoDR** [comment]
You mean the thumbnails at the bottom? They are still there, go to the settings and reset it.
It is only hidden by default if your screen is too small

**Comment by Pancakes0** [comment]
> You mean the thumbnails at the bottom? They are still there, go to the settings and reset it. It is only hidden by default if your screen is too small

Resetting works, Thank you very much!!!! ✨
i dont know, maybe it is because my laptop screen is small (13" laptop) since the new ui update it was missing and i just came to accept it until yesterday (cant handle without it 💀).
