### ISSUE TITLE
Asura Scans Stopped Working

### ISSUE THREAD

**Issue by ShinRwiz** [TagoDR/MangaOnlineViewer#258]
Script stopped working on :  https://asurascans.com/
Maybe it's related to the domain name recent change.
The new address is : https://asura.gg

**Comment by ShinRwiz** [comment]
started working  after i added  the domain name.
Modified line 23 and 72 and added the new homepage.

Line 23
`// @include /https?:\/\/(www.)?(asurascans|asura|flamescans|realmscans|alpha-scans).(com|org|gg)\/.+/`

Line 72 and homepage ( i copied from 69 )
`    // == AsuraScans and FlameScans ====================================================================
    var asurasflamecans = {
        name: ['Asura Scans', 'Flame Scans', 'Realm Scans', 'Alpha-scans'],
        url: /https?:\/\/(www.)?(asurascans|asura|flamescans|realmscans|alpha-scans).(com|org|gg)\/.+/,
        homepage: [
            'https://www.asurascans.com/',
            'https://asurascans.com/',
            'https://flamescans.org/',
            'https://realmscans.com/',
            'https://alpha-scans.org/',
        ],`

I added those just to help ppl that want it working as fast as possible and don't know what to change.
Also i don't know how to use github for now, will need to look around a bit.

**Comment by TagoDR** [comment]
Its fixed
