### ISSUE TITLE
[Chrome, Tampermonkey] Issue with "Pages/Second" setting

### ISSUE THREAD

**Issue by el0d** [TagoDR/MangaOnlineViewer#26]
There is no issue until you change the "Pages/Second" setting, the setting stays at "01" by default
But if you try changing it, regardless of what you choose it becomes fixed at "0.3", and it always changes back to "0.3" no matter how many times you try to change it.

**Comment by TagoDR** [comment]
I was not able to reproduce your error. However I was able to find a bug else where because i was searching, thank you.
Please try updating everything.

**Comment by el0d** [comment]
The issue is still present. But after doing further testing it seems I've misunderstood the issue.
Only the display is fixed at "0.3", the setting itself changes properly. Except for "0.3", for which you need to first change the fixed "0,3" to something else and back to "0,3" again, only then does it really change to 0,3.

So there's that. I could post the console log if you want but I don't think anything useful is printed there, the  only thing that seemed relevant was "MangaOnlineViewer: Intervals:" which was how I confirmed that the setting was actually changing properly.

**Comment by TagoDR** [comment]
And with this information I was able to find it. It should work just fine now

**Comment by el0d** [comment]
Yes, it's fixed now.
Thanks.
