### ISSUE TITLE
Can you set up multiple languages?

### ISSUE THREAD

**Issue by lhj5426** [TagoDR/MangaOnlineViewer#269]
![image](https://user-images.githubusercontent.com/30548000/197402068-98957caa-1c62-4f88-8a73-454aef425d7d.png)
Hello dear developer
I am now doing language translation directly in the code
Can I set up multiple languages?
In this way, you don't need to go to the code to set it again after the update.

**Comment by TagoDR** [comment]
Sure I can do it, give me some time

**Comment by lhj5426** [comment]
Hello dear developer

**Comment by TagoDR** [comment]
Done, look inside src/locale. You welcome to submit a translation.
