### ISSUE TITLE
Submit translation Simplified Chinese

### ISSUE THREAD

**Issue by lhj5426** [TagoDR/MangaOnlineViewer#270]
Thanks to the developers to add the multi-language settings, I have translated, now submitted to you to translate, hope to be added to the new version
![image](https://user-images.githubusercontent.com/30548000/197470114-0444e3ab-a1ed-4d82-a934-fbf5144ec411.png)
[chinese.txt](https://github.com/TagoDR/MangaOnlineViewer/files/9849603/chinese.txt)

**Comment by lhj5426** [comment]
And this part? No in TXT above
![image](https://user-images.githubusercontent.com/30548000/197473466-a44bcad2-827c-4452-bb4f-2a4308ae0507.png)
[Chinese001.txt](https://github.com/TagoDR/MangaOnlineViewer/files/9849715/Chinese001.txt)
![222347](https://user-images.githubusercontent.com/30548000/197473522-2e026b00-1db5-4b50-aa44-c8efa10b963e.gif)

**Comment by TagoDR** [comment]
You are correct, I missed those.
I've added them, please check.
There are some new strings that need translation.

**Comment by lhj5426** [comment]
I'm sorry that I forgot it yesterday. Please update the text here again
![image](https://user-images.githubusercontent.com/30548000/197697044-6c6670d3-12ea-40df-854d-a93cb3074200.png)
Newly added translation content
![image](https://user-images.githubusercontent.com/30548000/197698693-5b9f2369-4810-42e5-8689-c5f86ba1b6a6.png)
![image](https://user-images.githubusercontent.com/30548000/197698846-bba30226-8c6d-49e8-a3a8-ff14458d69e9.png)

[chinese0003.txt](https://github.com/TagoDR/M
[keybinds.txt](https://github.com/TagoDR/MangaOnlineViewer/files/9857655/keybinds.txt)
angaOnlineViewer/files/9857580/chinese0003.txt)
![image](https://user-images.githubusercontent.com/30548000/197698995-3a8e6896-7c5a-4199-b21d-7a297a537e42.png)
    const listBookmarks = () => {
        if (isEmpty(useSettings().bookmarks))
            return ['没有收藏书签'];

**Comment by lhj5426** [comment]
Thank you.

**Comment by TagoDR** [comment]
Hopefuly everything is translated new, please spell check.

**Comment by lhj5426** [comment]
[chinese0005.txt](https://github.com/TagoDR/MangaOnlineViewer/files/9866942/chinese0005.txt)
Fixed some translation positions
Because of my carelessness, this is the last one
![image](https://user-images.githubusercontent.com/30548000/197956735-99f90081-9104-44d2-8a79-3e3baa3ee685.png)
![image](https://user-images.githubusercontent.com/30548000/197956779-ec63711c-84d0-44f1-a2de-ca02cfb8e098.png)

    
    <div class="ControlLabel DefaultZoom">${getLocaleString('DEFAULT_ZOOM')}:
      <select id="DefaultZoom">
        <option value="50" ${useSettings().zoom === 50 ? 'selected' : ''}>50%</option>
        <option value="75" ${useSettings().zoom === 75 ? 'selected' : ''}>75%</option>
        <option value="100" ${useSettings().zoom === 100 ? 'selected' : ''}>100%</option>
        <option value="125" ${useSettings().zoom === 125 ? 'selected' : ''}>125%</option>
        <option value="150" ${useSettings().zoom === 150 ? 'selected' : ''}>150%</option>
        <option value="175" ${useSettings().zoom === 175 ? 'selected' : ''}>175%</option>
        <option value="200" ${useSettings().zoom === 200 ? 'selected' : ''}>200%</option>
        <option value="1000" ${useSettings().zoom === 1000 ? 'selected' : ''}>合适宽度</option>
        <option value="-1000" ${useSettings().zoom === -1000 ? 'selected' : ''}>适合高度</option>
      </select>
    </div>
    
    Thank you very much indeed

**Comment by lhj5426** [comment]
This is the current final version Thank you very much for your help these days

**Comment by TagoDR** [comment]
Your welcome.
