### ISSUE TITLE
This bookmark click can not be closed is a bug

### ISSUE THREAD

**Issue by lhj5426** [TagoDR/MangaOnlineViewer#271]
This bookmark click can not be closed is a bug？
look
![222346](https://user-images.githubusercontent.com/30548000/197472227-1fac1425-6646-4a8b-b89d-8056d029e535.gif)

**Comment by TagoDR** [comment]
I'm not able to reproduce it.
What site is this?
You may have tied to translate some object id by mistake.

**Comment by lhj5426** [comment]
I'm sorry this was caused by the browser version

https://user-images.githubusercontent.com/30548000/197699349-04a4259a-fd5c-4015-90a4-2e6d298cbc6b.mp4



https://user-images.githubusercontent.com/30548000/197699414-7dd49ec8-c373-41df-a9e6-1688dd041d2e.mp4

**Comment by lhj5426** [comment]
It's not a bug but a low browser version
