### ISSUE TITLE
https://mangabuddy.com/ site not loading 

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#275]
https://mangabuddy.com/ site not loading because the site is strangly loading It make a infinty loob 
![Screenshot 2022-11-14 220602](https://user-images.githubusercontent.com/100969549/201765459-6758dd32-b614-47d3-9758-9acc0c1b3774.png)

**Comment by TagoDR** [comment]
Should be Fixed
