### ISSUE TITLE
Viewer auto scrolls to the middle of the page

### ISSUE THREAD

**Issue by goombus** [TagoDR/MangaOnlineViewer#276]
Not sure if it's browser setting dependent or the script's behavior. Sometimes when using arrow keys to scroll up or down it'll scroll to a certain point on the next page on its own. Happens in both Chrome and Firefox.

**Comment by TagoDR** [comment]
I need more information, witch sites? did you use fit height? if you mess with the zoom what happens?

**Comment by goombus** [comment]
I'm seeing it happen on nhentai, but haven't tried other sites. It happens on various zoom settings (50%, 100%, fit width, etc...) If I recall, it used to not do this, but I'm not sure when it started doing it.
