### ISSUE TITLE
Minor breakage on MyHentaiGallery

### ISSUE THREAD

**Issue by walgadon** [TagoDR/MangaOnlineViewer#278]
The script only seems to work on the last few pages and misses the last few pages in the gallery.
The following change seems to mostly fix it, replacing this:
```
const num = parseInt(document.querySelector('.pagination ul li:nth-last-child(3)')?.textContent || '', 10);
```

With this:
```
const nth = document.querySelector('.pagination ul li:last-child a.active') !== null ? 1 : 2;
const num = parseInt(document.querySelector(`.pagination ul li:nth-last-child(${nth})`)?.textContent || '', 10);
```

The extra check to see if the active page is the last page is there because otherwise you would skip the last image when starting out on the last page.

**Comment by TagoDR** [comment]
Should be fixed now

**Comment by walgadon** [comment]
Almost, `js__pagination__next` does not exist on the last page so it will not trigger when you open a gallery on the last page. I will admit that this is a very minor nitpick.
