### ISSUE TITLE
 notable to in install

### ISSUE THREAD

**Issue by swathigrate** [TagoDR/MangaOnlineViewer#28]
hello sir 

Adult Script  is  notable to in install  with new grasemonkey ...
plz fix it 

thanks you

**Comment by explore01** [comment]
please try tampermonkey, sir TagoDR said that greasemonkey somehow not pretty much compatible with the script as lately...

**Comment by TagoDR** [comment]
grasemonkey and tampermonly are currently changing the inner workings, util both are compatible with one another I'll will only support tampermonky, give it a try I find it is better than grasemonkey.

**Comment by swathigrate** [comment]
ohhh..  thanks .. ....
