### ISSUE TITLE
Buttons to anchor? (prev and next)

### ISSUE THREAD

**Issue by CoLdAs1cE** [TagoDR/MangaOnlineViewer#280]
I tried to use next and prev buttons but it replaces and does not open new tab (and sometimes i used to drag anchor to create new tab).
Is it possible to either replicate this with buttons or change back to anchor tags?
And if im reading a manga from the start, i like to use next button (old behavior since it was an anchor) to preload manga so i dont have to wait for everything to view next chapter. And sometimes event prev (in new tab) when i didnt read something and and got the lastest chapter

**Comment by TagoDR** [comment]
Sure, done.

**Comment by TagoDR** [comment]
Which site dos this happens? I can't reproduce it.

**Comment by CoLdAs1cE** [comment]
on asura

**Comment by TagoDR** [comment]
Still can't reproduce it, please check if something else interferes with the page.

**Comment by CoLdAs1cE** [comment]
Strange... well its not a big deal ;)

**Comment by CoLdAs1cE** [comment]
I see the problem, i was toying around (cuz i tought it was something i had installed as well) and took pictures of that :/
So the new picture is wrong
![image](https://user-images.githubusercontent.com/1981573/205176531-7c7a2b9d-0f17-4037-994d-570939ff140b.png)
As u can see it has more height than the old one

**Comment by CoLdAs1cE** [comment]
I think might have seen something that wasn't there :O
