### ISSUE TITLE
https://realmscans.com/ only half loading

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#281]
![Screenshot 2022-11-28 172737](https://user-images.githubusercontent.com/100969549/204329883-dcce4eb9-6039-4875-9fe7-fe47928fec5d.png)

**Comment by TagoDR** [comment]
That's a connection issue, on end or theirs.
Enable the control, if they are off, and use them to refresh the specific page.

**Comment by CoLdAs1cE** [comment]
This is true, realm is using another attribute for images

**Comment by CoLdAs1cE** [comment]
data-lazy-src

**Comment by big-cat-loaf** [comment]
@CoLdAs1cE thanke you that is not just me that thinks that is a bug.
 And yes I think too that it has something to do with data-lazy-src

**Comment by TagoDR** [comment]
Fixed

**Comment by CoLdAs1cE** [comment]
Had the same problem since i use realm as well
