### ISSUE TITLE
Next and Prev not hiding when starting or ending

### ISSUE THREAD

**Issue by CoLdAs1cE** [TagoDR/MangaOnlineViewer#282]
I just noticed when i was reading something new on asura. That when reaching last released chapter next "button" is still there :(.
Because i set both prev and next to undefined and it used the last released  on both prev and next "buttons" :(
https://asura.gg/life-of-a-magic-academy-mage-chapter-17/ will go chap (which is current) 17 on next instead of hiding it
https://asura.gg/life-of-a-magic-academy-mage-chapter-1/ will go to 1 (which is current) when hovering over prev

**Comment by TagoDR** [comment]
Fixed
