### ISSUE TITLE
reaperscans.com e

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#283]
Next Chapter, Previous Chapter doesnt exist 
example  https://reaperscans.com/comics/7868-return-of-the-frozen-player
                https://reaperscans.com/comics/7868-return-of-the-frozen-player/chapters/96137993-chapter-54
![Screenshot 2022-12-07 211221](https://user-images.githubusercontent.com/100969549/206285883-5aaa6a53-c288-4958-a8a6-60b901363f0a.png)
![Screenshot 2022-12-07 211436](https://user-images.githubusercontent.com/100969549/206286191-f8566e90-1957-40c2-872a-44748a6c8784.png)

**Comment by TagoDR** [comment]
Fixed
