### ISSUE TITLE
Mangahub.io not working properly

### ISSUE THREAD

**Issue by CoLdAs1cE** [TagoDR/MangaOnlineViewer#285]
Some times it works, sometimes it dont
Failed when it tried to load script twice, when it tries 1 time it works
MangaOnlineViewer:  Starting Manga OnlineViewer 2022.12.01 on Firefox 107 with Tampermonkey Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  41 Known Manga Sites, Looking for a match... Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Found site: MangaHub Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Waiting for Element #select-chapter =  null Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Starting Manga OnlineViewer 2022.12.01 on Firefox 107 with Tampermonkey Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  41 Known Manga Sites, Looking for a match... Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Found site: MangaHub Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Waiting for Element #select-chapter =  null 9 Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Found Pages: 8 Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Rebuilding Site Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Found Pages: 8 Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Rebuilding Site Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Loading Images Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Intervals: 1000 Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Lazy: true, Starting from: 50 Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Method: Images: 
Array(8) [ "https://img.mghubcdn.com/file/imghub/the-god-of-death/122/1.jpg", "https://img.mghubcdn.com/file/imghub/the-god-of-death/122/2.jpg", "https://img.mghubcdn.com/file/imghub/the-god-of-death/122/3.jpg", "https://img.mghubcdn.com/file/imghub/the-god-of-death/122/4.jpg", "https://img.mghubcdn.com/file/imghub/the-god-of-death/122/5.jpg", "https://img.mghubcdn.com/file/imghub/the-god-of-death/122/6.jpg", "https://img.mghubcdn.com/file/imghub/the-god-of-death/122/7.jpg", "https://img.mghubcdn.com/file/imghub/the-god-of-death/122/8.jpg" ]
Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Loaded Image: 1 Source: https://img.mghubcdn.com/file/imghub/the-god-of-death/122/1.jpg Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Progress: 12% Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Loading Images Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Intervals: 1000 Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Lazy: true, Starting from: 50 Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Method: Images: 
Array(8) [ "https://img.mghubcdn.com/file/imghub/the-god-of-death/122/1.jpg", "https://img.mghubcdn.com/file/imghub/the-god-of-death/122/2.jpg", "https://img.mghubcdn.com/file/imghub/the-god-of-death/122/3.jpg", "https://img.mghubcdn.com/file/imghub/the-god-of-death/122/4.jpg", "https://img.mghubcdn.com/file/imghub/the-god-of-death/122/5.jpg", "https://img.mghubcdn.com/file/imghub/the-god-of-death/122/6.jpg", "https://img.mghubcdn.com/file/imghub/the-god-of-death/122/7.jpg", "https://img.mghubcdn.com/file/imghub/the-god-of-death/122/8.jpg" ]
Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Loaded Image: 1 Source: https://img.mghubcdn.com/file/imghub/the-god-of-death/122/1.jpg Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Progress: 12% Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Loaded Image: 2 Source: https://img.mghubcdn.com/file/imghub/the-god-of-death/122/2.jpg Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Progress: 25% Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Loaded Image: 2 Source: https://img.mghubcdn.com/file/imghub/the-god-of-death/122/2.jpg Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Progress: 25% Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Loaded Image: 3 Source: https://img.mghubcdn.com/file/imghub/the-god-of-death/122/3.jpg Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Progress: 37% Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Loaded Image: 3 Source: https://img.mghubcdn.com/file/imghub/the-god-of-death/122/3.jpg Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Progress: 37% Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Loaded Image: 4 Source: https://img.mghubcdn.com/file/imghub/the-god-of-death/122/4.jpg Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Progress: 50% Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Loaded Image: 4 Source: https://img.mghubcdn.com/file/imghub/the-god-of-death/122/4.jpg Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Progress: 50% Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Loaded Image: 5 Source: https://img.mghubcdn.com/file/imghub/the-god-of-death/122/5.jpg Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Progress: 62% Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Loaded Image: 5 Source: https://img.mghubcdn.com/file/imghub/the-god-of-death/122/5.jpg Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Progress: 62% Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Loaded Image: 6 Source: https://img.mghubcdn.com/file/imghub/the-god-of-death/122/6.jpg Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Progress: 75% Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Loaded Image: 6 Source: https://img.mghubcdn.com/file/imghub/the-god-of-death/122/6.jpg Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Progress: 75% Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Loaded Image: 7 Source: https://img.mghubcdn.com/file/imghub/the-god-of-death/122/7.jpg Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Progress: 87% Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Loaded Image: 7 Source: https://img.mghubcdn.com/file/imghub/the-god-of-death/122/7.jpg Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Progress: 87% Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Loaded Image: 8 Source: https://img.mghubcdn.com/file/imghub/the-god-of-death/122/8.jpg Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Progress: 100% Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Images Loading Complete Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Loaded Image: 8 Source: https://img.mghubcdn.com/file/imghub/the-god-of-death/122/8.jpg Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Progress: 100% Manga OnlineViewer.user.js:1575:17
MangaOnlineViewer:  Images Loading Complete Manga OnlineViewer.user.js:1575:17

**Comment by TagoDR** [comment]
Fixed it, an iframe was running the script too
