### ISSUE TITLE
Can more percentage scaling be added

### ISSUE THREAD

**Issue by lhj5426** [TagoDR/MangaOnlineViewer#287]
![image](https://user-images.githubusercontent.com/30548000/206824607-13f0827d-c98c-459f-81b1-4dbc6d7e448f.png)
        <option value="10" ${useSettings().zoom === 10 ? 'selected' : ''}>10%</option>
        <option value="15" ${useSettings().zoom === 15 ? 'selected' : ''}>15%</option>
        <option value="20" ${useSettings().zoom === 20 ? 'selected' : ''}>20%</option>
        <option value="25" ${useSettings().zoom === 25 ? 'selected' : ''}>25%</option>
        <option value="30" ${useSettings().zoom === 30 ? 'selected' : ''}>30%</option>
        <option value="35" ${useSettings().zoom === 35 ? 'selected' : ''}>35%</option>
        <option value="40" ${useSettings().zoom === 40 ? 'selected' : ''}>40%</option>
        <option value="45" ${useSettings().zoom === 45 ? 'selected' : ''}>45%</option>
        <option value="50" ${useSettings().zoom === 50 ? 'selected' : ''}>50%</option>
        <option value="55" ${useSettings().zoom === 55 ? 'selected' : ''}>55%</option>
        <option value="60" ${useSettings().zoom === 60 ? 'selected' : ''}>60%</option>
        <option value="65" ${useSettings().zoom === 65 ? 'selected' : ''}>65%</option>
        <option value="70" ${useSettings().zoom === 70 ? 'selected' : ''}>70%</option>
        <option value="75" ${useSettings().zoom === 75 ? 'selected' : ''}>75%</option>
        <option value="80" ${useSettings().zoom === 80 ? 'selected' : ''}>80%</option>
        <option value="85" ${useSettings().zoom === 85 ? 'selected' : ''}>85%</option>
        <option value="90" ${useSettings().zoom === 90 ? 'selected' : ''}>90%</option>
        <option value="95" ${useSettings().zoom === 95 ? 'selected' : ''}>95%</option>
        Because some pictures are 50% and they are still too large to be fully displayed
        Although you can use the shortcut key E to adjust the size
But it is a bit inconvenient to press many times
In this way, it is suitable to add more resolutions and percentages.
More convenient
Can the developer add more resolution percentages, thanks

**Comment by lhj5426** [comment]
The display is 1080X1920
Pictures are sometimes 4K or even 8K
Even zoomed to 50% it's still huge
So request to add this more percentage display zoom
thanks

**Comment by TagoDR** [comment]
Added, please test it

**Comment by lhj5426** [comment]
> Added, please test it

![image](https://user-images.githubusercontent.com/30548000/206861523-3a7e0bd8-31eb-4fd9-baaf-a547e2e7f102.png)
reinstalled the script

did not see?

**Comment by TagoDR** [comment]
sorry, forgot to push it.
Should be avaliable now

**Comment by lhj5426** [comment]
https://user-images.githubusercontent.com/30548000/206870757-68f06994-0dec-48e5-8799-9af4ac4fdf9c.mp4

It's a horrible experience with this slider
Not as good as the original Direct Accurate Select
Very bad! !
Thanks for your response

But this time the setup is bad
For example, if I want to change from 75% to 80% or 85%, the original can be directly adjusted to
Now the slider is difficult to control precisely
From 75% to 100% in one go
it's too bad

**Comment by lhj5426** [comment]
It is better to directly add 10-95% on the original basis
Because every update has to be added manually, several versions have been added
Feeling a bit troublesome to post
I implore the developer to add the built-in

But such a changed operating experience
really too bad
can you change it back

sorry it doesn't work

**Comment by lhj5426** [comment]
https://user-images.githubusercontent.com/30548000/206871394-440aa653-81c8-4db3-a3eb-5fb0b3cbeb89.mp4
Sliders are not synced in real time on the web
Instead, you need to release the mouse to see the size change after sliding once
Instead of dragging the slider in real time to see the changes in the software
So setting the percentage here with a slider is really not as convenient as the original menu selection

**Comment by TagoDR** [comment]
Added new Zoom controls, check it out.

**Comment by lhj5426** [comment]
very smooth

thank you very much

https://user-images.githubusercontent.com/30548000/206883410-9bc87591-93a4-47f5-87eb-257b3b6c3b65.mp4


very easy to use

this is amazing! ! !

Perfect！！！
