### ISSUE TITLE
Can it be increased from how much to how much start page number and end page number

### ISSUE THREAD

**Issue by lhj5426** [TagoDR/MangaOnlineViewer#289]
At startup, select the start page and end page
![image](https://user-images.githubusercontent.com/30548000/212127792-d5264cc1-0475-4b34-890f-9e133da56164.png)
Can it be increased from how much to how much
start page number and end page number

![image](https://user-images.githubusercontent.com/30548000/212127950-e45f8c2a-9462-42f0-bfea-f02393f795e0.png)
I'm not afraid of your jokes

There are many advertisements in Chinese

If you can set the loading start page number and end page number
you can exclude this part of the ad

This saves quota

I don't know if the developer can increase this setting？

And it can automatically remember how many pages have been reduced by the end page
For example, the manga has 37 pages
Among them, 7 pages of advertising pages are not loaded
And then the script automatically remembers 7 pages
At the next startup, by default, the total number of pages will be reduced by 7 pages
In this way, if the second book you read still has advertisements, you don’t need to manually adjust

Thank you for adding this feature

These ads are illegal and illegal so you don't have to worry 

The website itself is not self-supervised, which has caused these advertisements to take advantage of loopholes, so I beg you to
Add a function to set the start page number and end page number

**Comment by TagoDR** [comment]
I've added the page range choice in the beginning, however I think it's not wise to save a default number of pages to cut off.

**Comment by lhj5426** [comment]
> I've added the page range choice in the beginning, however I think it's not wise to save a default number of pages to cut off.

![image](https://user-images.githubusercontent.com/30548000/212526406-f953b2b7-e95d-48fb-8ece-a87292a5e73d.png)
thank you very much

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/212527563-647235bd-119a-4540-a757-741c1b471fbe.png)
https://add0n.com/open-in.html?from=firefox#faq26
Actually it is like this

I found a browser extension

It can be opened by calling other browsers according to the domain name

So what I mentioned is to keep the last selected page number

It's a request from this extension, I know it's selfish

What do I think if the developer added your script to remember to fix automatically to reduce the number of fixed pages

Then when I encounter this kind of book with advertisements, I can use the browser extension found above
to open this manga in other browsers and when the new browser loads with your script, it can start auto-run because it remembers the reduced number of pages

As for normal comics without advertisements, I still use a normal browser to read them without enabling the function of automatically remembering the number of pages.

I came up with this idea

Is it possible to automatically remember the last reduced number of pages? This requirement

After you read my statement, you can consider

Can you add this function?

I admit that this function is selfish
but really hope to add this feature

Thank you very much
