### ISSUE TITLE
not working on some site

### ISSUE THREAD

**Issue by explore01** [TagoDR/MangaOnlineViewer#29]
hi again TagoDR,
i found some problem with the script, which is seems not working with some sites
i fount it happen in these sites:
- readmanga,today (been like a week or more, but readmanga.today now provide an option to read a full chapter in one page.. even so i still prefer your script better, easier on saving it on my pc as well..)
- https://jaiminisbox.com/ i tried to access some manga just now, and i found the image loaded said crawler detected, all pages showing the same images..
looking to hear from you again,

thanks Tago,

regards,
Rizky

**Comment by TagoDR** [comment]
readmanga,today change more than its url I need time to study it, jaiminisbox I'll have to find a way to bypass the DRM witch I'll will need time.
I'm on vacation right now, I cant focus on this issues right now. when I return I'll look into them, for now please read on one of the others supported sites.

**Comment by explore01** [comment]
okay TagoDR, glad to hear from you..
take your time!
thanks!

**Comment by TagoDR** [comment]
For now Readmanga.today should be working.

**Comment by explore01** [comment]
great, just updated it, and it works, thanks a lot TagoDR!

**Comment by medientu** [comment]
Can you support mangarock.com? Thanks

**Comment by TagoDR** [comment]
MangaRock is very different form the other sites, it would require big changes to the script if I don't find a simple way around html5 canvas. I'm willing but its not coming soon.

**Comment by DonCardamon** [comment]
Can you support hentai.cafe? Version 11.20 supports it already except the "Return to Chapter List" button, which doesn't work.

**Comment by TagoDR** [comment]
Fixed jaiminibox.
Added hentaicafe.
And so far mangarock is not possible, I need to study more
