### ISSUE TITLE
Can it automatically detect the current page number at startup

### ISSUE THREAD

**Issue by lhj5426** [TagoDR/MangaOnlineViewer#291]
https://user-images.githubusercontent.com/30548000/214305854-8b87bc08-aef3-4f0c-9694-14ec35ad4ea7.mp4

Dear developer
Hello
Can it automatically detect the current page number at startup?
Automatic judgment
instead of starting from 1 ？
Thanks♪(･ω･)ﾉ

**Comment by TagoDR** [comment]
For now, I've added only the site you showed

**Comment by lhj5426** [comment]
https://user-images.githubusercontent.com/30548000/214488029-47652484-1c52-4227-8111-fab0b190fecc.mp4

Dear developer

Thank you very much！！
