### ISSUE TITLE
(Site Request) INKR Alternate Site

### ISSUE THREAD

**Issue by omodia** [TagoDR/MangaOnlineViewer#296]
### Thank you very much for adding the INKR site the previous day. 
- [This is their old site](https://inkr.com/explore/Fantasy), but it is still working. Please add this too.
- To access the site [click here](https://inkr.com/explore/Fantasy) and follow the steps in video.
- If you reload the page, it will be redirected to the [new site](https://comics.inkr.com/).
- The entire site can be accessed without reloading the page.
- The images here are not masked. The image links start with **blob:https://**. 

https://user-images.githubusercontent.com/116664905/216519194-d2c0402d-bd4e-4464-a82d-0ec247c03a24.mp4

- The .webp images hosted in their old site are of higher quality and less size than .jpg images used in their new site.
- Check out the below zip file and you will get what I mean.

[Image Quality And Size Difference.zip](https://github.com/TagoDR/MangaOnlineViewer/files/10575689/Image.Quality.And.Size.Difference.zip)

**Comment by TagoDR** [comment]
I've added this 'old' site, it's just an alias it seems.
It's not clear how to get the webp image, but it should work, I'm not limiting it to jpg

**Comment by TagoDR** [comment]
Then unfortunately the script will never trigger, there is nothing I can do.
