### ISSUE TITLE
(Site Request) BilibiliComics

### ISSUE THREAD

**Issue by omodia** [TagoDR/MangaOnlineViewer#297]
Website - [BilibiliComics](https://www.bilibilicomics.com/)
Example Chapter - [Target: 100 Million Points!](https://www.bilibilicomics.com/mc39/16820)
There are three types of quality settings and all images are .webp format.
Please add this site.

https://user-images.githubusercontent.com/116664905/216766545-b929ffe9-a1f2-4c83-bab1-c7d2b36bebf9.mp4

**Comment by TagoDR** [comment]
Added
