### ISSUE TITLE
(Site Request) WebNovel

### ISSUE THREAD

**Issue by omodia** [TagoDR/MangaOnlineViewer#298]
Site - [WebNovel](https://www.webnovel.com/)
Example Manhua - [Battle Through The Heavens](https://www.webnovel.com/comic/battle-through-the-heavens_13741824806105701)

**Comment by TagoDR** [comment]
Added

**Comment by TagoDR** [comment]
It's working for me, press f12, look at the console

**Comment by TagoDR** [comment]
The script is waiting for the variable g_data to be created, so it can extract information from it, something is blocking it, check your ad blocker or other script you have enabled in this page

**Comment by TagoDR** [comment]
I see now, the problem is with Violentmonkey in Firefox, it doesn't allow for this method yet. It's been sometime, I might just drop support for it entirely
Please switch to Tampermonkey.
