### ISSUE TITLE
manhwatop.com don't load proprelly.

### ISSUE THREAD

**Issue by ShinRwiz** [TagoDR/MangaOnlineViewer#304]
Site: https://manhwatop.com
Issue: Show loading gif instead of image (https://manhwatop.com/loader.svg)
Extra Info: 
- I noticed that if i scroll down fast to let images load, the script show whatever was loaded, the rest is  "loader.svg"
- last image load without any problem every times and is the same in all chapters (https://manhwatop.com/3.1.jpg) 
- Tried to use the slowest load speed just in case

**Comment by TagoDR** [comment]
Fixed
