### ISSUE TITLE
is it possible to change Keybindings?

### ISSUE THREAD

**Issue by Pancakes0** [TagoDR/MangaOnlineViewer#305]
sorry, i dont know where else to reach you unless here, i have a question. is it possible to change keybinds? thanks you

**Comment by big-cat-loaf** [comment]
Im not the creator but to your Qustion: No you can't change the Keybindings. 
@TagoDR Can you add it?

**Comment by Pancakes0** [comment]
ah i see, thank you for your reply!

**Comment by TagoDR** [comment]
Yes I tried a solution for it, I have pushed it to branch 'develop', please test it.

**Comment by TagoDR** [comment]
Released
