### ISSUE TITLE
need to  update 

### ISSUE THREAD

**Issue by swathigrate** [TagoDR/MangaOnlineViewer#31]
hello sir ,,, 
   thanks for   grate  script ..  working  is  fine ... but i'm facing  a  little bit   problem with  adult script ... 
i[https://e-hentai.org](url) in this  site ...  if  any  comix  was opened  the  script is  showing   below  type of  popup ... nice one 
![fdfer](https://user-images.githubusercontent.com/14991260/33755458-dc6b6580-dc16-11e7-9db6-c7408f1e1420.jpg)
i cancelled iit    and   selected 14 pic ... but  our  script is  not working from selected pics ... it's  working only starting  time ... 
 hope   u  understood my prolbem 

plz fix it   ... thanks you

**Comment by TagoDR** [comment]
I believe I understood your problem but I cant reproduce it.
You can very well cancel loading and then select an individual image to see normally.

**Comment by swathigrate** [comment]
so ... we can not  start from  a  particular image 
eg: 19

**Comment by TagoDR** [comment]
There is a Bookmark feature, save the page with the start icon and the script will start from it next time, but on e-hentai each block of images counts as a chapter
