### ISSUE TITLE
Can it be changed to manual input here?

### ISSUE THREAD

**Issue by lhj5426** [TagoDR/MangaOnlineViewer#311]
Hello, dear developer
Well, I found a browser at night
Can perfectly support the script you develop
https://lemurbrowser.com
![image](https://user-images.githubusercontent.com/30548000/228358919-62001108-8f90-4127-bc7d-4c59a9018288.png)

![image](https://user-images.githubusercontent.com/30548000/228359232-55d3fe54-8bc8-4092-8208-40967f4bcc79.png)
![image](https://user-images.githubusercontent.com/30548000/228359555-6b651291-30cf-4883-a86b-8e61754df6f8.png)

Can perfectly run the scripts you develop on Android phones

But there is a small problem, please see the demo
![GIF2](https://user-images.githubusercontent.com/30548000/228361028-d79f95cb-feec-4629-b34d-73aab5935fed.gif)
as you can see in the demo

On mobile phones, this slider adjustment is not accurate enough
And it's not easy to adjust
When adjusting, the screen is also moving
so
Can I ask you to adapt the phone

No major changes are required, just put
![image](https://user-images.githubusercontent.com/30548000/228361448-78445444-e997-4d49-adf8-5fe386fada4d.png)
Change the position here to the state where you can manually fill in the numbers, and you can easily use the precise adjustment page on your mobile phone

Can you please make some changes to adapt to mobile phone use

very very thank you

my respected developer

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/228365685-3d7f5dc3-b8f1-41cb-9a08-33e3e8e41f67.png)
Actually, I asked GPT, but I don’t have a code base. I copied and pasted the code it gave me, and it didn’t work.

So, I can only trouble you, the developer.

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/228372586-4b33ec60-d1af-494f-912a-5704bb0edddd.png)

![image](https://user-images.githubusercontent.com/30548000/228372345-10f00350-d5be-4c7b-b8d6-c678f37bd288.png)

![image](https://user-images.githubusercontent.com/30548000/228372270-b773abc6-a00a-4f37-93c9-567b73f63c15.png)

After continuous trial and error with GPT
Finally changed it. . . .

Below is the code that GPT gave me

async function lateStart(site, begin = 1) {
  const manga = await site.run();
  logScript("LateStart");
  let beginPage = begin || 1;
  let endPage = manga.pages;
  const options = {
    title: getLocaleString("STARTING"),
    html: `
      <p style='font-size: 16px; margin-bottom: 8px;'>${getLocaleString("CHOOSE_BEGINNING")}</p>
      <p>
        <input type='text' id='beginPageInput' value='${beginPage}' style=' width: 50px; font-size: 16px; padding: 8px;'> 
        &nbsp;-&nbsp; 
        <input type='text' id='endPageInput' value='${endPage}' style='width: 50px; font-size: 16px; padding: 8px;'>
      </p>
    `,
    showCancelButton: true,
    cancelButtonColor: "#d33",
    reverseButtons: true,
    icon: "question"
  };
  Swal.fire(options).then((result) => {
    if (result.value) {
      logScript(`Choice: ${beginPage} - ${endPage}`);
      beginPage = parseInt(document.getElementById("beginPageInput").value);
      endPage = parseInt(document.getElementById("endPageInput").value);
      manga.begin = beginPage;
      manga.pages = endPage;
      display(manga);
    } else {
      logScript(result.dismiss);
    }
  });
}

function createLateStartButton(site, beginning) {
  const button = document.createElement("button");
  button.innerText = getLocaleString("BUTTON_START");
  button.id = "StartMOV";
  button.onclick = () => {
    lateStart(site, beginning);
  };
  document.body.appendChild(button);
  const style = document.createElement("style");
  style.appendChild(document.createTextNode(startButton));
  document.head.appendChild(style);
  logScript("Start Button added to page", button);
}

function showWaitPopup(site, manga) {
  Swal.fire({
    title: getLocaleString("STARTING"),
    html: `${manga.begin > 1 ? `${getLocaleString("RESUME")}${manga.begin}.<br/>` : ""}${getLocaleString("WAITING")}`,
    showCancelButton: true,
    cancelButtonColor: "#d33",
    reverseButtons: true,
    timer: 3e3
  }).then((result) => {
    if (result.value || result.dismiss === Swal.DismissReason.timer) {
      display(manga);
    } else {
      createLateStartButton(site, manga.begin);
      logScript(result.dismiss);
    }
  });
}

**Comment by TagoDR** [comment]
Interesting, but still far from perfect.
The problem with manual input is that they need to always be validated.
I've added it, test it please.

**Comment by lhj5426** [comment]
> Interesting, but still far from perfect. The problem with manual input is that they need to always be validated. I've added it, test it please.
![image](https://user-images.githubusercontent.com/30548000/228446209-d7e9db63-12ea-4513-9ac0-a39597ed8c71.png)

Thank you so much this is great

In fact, if the automatic loading is turned on, it will have no effect.

Manually loaded just to adjust not to load ads

Thank you very much for your update

Now mobile phones and computers are very easy to use

really thank you again

I found out yesterday that your plug-in works perfectly on my phone, I'm super happy

Can't run on safari of IOS16

Yesterday my mother got a new mobile phone
Retired old android phone for me

i heard android browser is very powerful

Just try it, the browser on Android is really powerful

Works flawlessly on my favorite

**Comment by lhj5426** [comment]
![GIF8](https://user-images.githubusercontent.com/30548000/228453287-0fea7a28-0911-4da7-a0b4-32c056cb9d55.gif)
Encountered a BUG on the mobile phone
Delete the blank, automatically fill in the maximum value and cannot delete or fill in a new one
Always delete Always automatically fill the maximum value

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/228455762-1f98279a-6b75-446b-bdfb-d025b84cf6be.png)

Then there is an input box, it is better to be bigger, and it can display 4 digits.

You see, this kind of over a hundred pages can only display 2 digits
![image](https://user-images.githubusercontent.com/30548000/228456313-3933ffaa-35b8-4eb6-b226-810352dac6c1.png)

This kind of more than a thousand pages is even more incomplete.

Therefore, the input box can be made to display 4 digits

**Comment by TagoDR** [comment]
Everything should be ok now

**Comment by lhj5426** [comment]
thank you very much

everything is fine now
