### ISSUE TITLE
Ksk moe broken pageloader

### ISSUE THREAD

**Issue by kevin01523** [TagoDR/MangaOnlineViewer#313]
![image](https://user-images.githubusercontent.com/8380242/229323665-222c8628-e94d-4759-97be-7875f10b62d3.png)
it seems to just repeat loading the first page it captures

i just enter a manga wait for it to load i even reset settings to default or reinstalled script to see and waited like 10 minutes without doing anything.

**Comment by TagoDR** [comment]
This site is the most peculiar one, I had to brute force it, emulating a user looking at each page and snatching the image url.
I can't reproduce your problem, I need more information:
Are you using Tampermonkey?
What browser?
Is your internet fast/slow?
Disable the script, try navigating of each page, does it work properly?
Any odd message in console (F12)
Are you using a vpn/proxy?
Does it happen only on ksk? or in sukebe too?

**Comment by TagoDR** [comment]
I see, its safer to assume everyone is using incognito, therefore no settings saved.
I've changed it a bit, should be faster and ignore settings.
