### ISSUE TITLE
Tumangaonline - Problem with reading url

### ISSUE THREAD

**Issue by JhulShock** [TagoDR/MangaOnlineViewer#314]
I was adding the new names of the pages so that the extension works, 

(almtechnews|animalslegacy|anisurion|cookernice|dariusmotor|followmanga|gamesxo|lectortmo|motorbakery|otakunice|paleomotor|recetchef|recipescoaching|recipesist|sucrecipes|tmofans).com\/.+\/.+\/(paginated|cascade)/,

but there are cases in which I can not get it to work and I think it is because of this:

  *No problem occurs
     If the url has:               .com/viewer
     Example: 
      https://lectortmo.com/viewer/d59ee9096f2ba50106ff82c427782b0a/cascade

  *The problem occurs when
     If the url has:                .com/news
     Example:  
      https://recipescoaching.com/news/5af656f701374/cascade

I tried changing the words "viewer" to the word "news", but it didn't work.

 
 const tmofans = {
    name: "TuMangaOnline",
    url: /https?:\/\/(www.)?(almtechnews|animalslegacy|anisurion|cookernice|dariusmotor|followmanga|gamesxo|lectortmo|motorbakery|otakunice|paleomotor|recetchef|recipescoaching|recipesist|sucrecipes|tmofans).com\/.+\/.+\/(paginated|cascade)/,
    homepage: "https://lectortmo.com/",
    language: ["Spanish"],
    category: "manga",
    run() {
      const images = [...document.querySelectorAll(".img-container img")];
      const pages = [
        ...document.querySelectorAll(
          "div.container:nth-child(4) select#viewer-pages-select option"
        )
      ];
      const num = images.length > 1 ? images.length : pages.length;
      return {
        title: document.querySelector("title")?.textContent?.trim(),
        series: document.querySelector('a[title="Volver"]')?.getAttribute("href"),
        pages: num,
        prev: document.querySelector(".chapter-prev a")?.getAttribute("href"),
        next: document.querySelector(".chapter-next a")?.getAttribute("href"),
        listPages: images.length > 1 ? null : Array(num).fill(0).map((_, i) => `${window.location.href.replace(/\/\d+$/, "")}/${i + 1}`),
        listImages: images.length > 1 ? images.map((item) => $(item).attr("data-src")) : null,
        img: "#viewer-container img, .viewer-page"
      };
    }
  };

Thank you for your work

**Comment by JhulShock** [comment]
![image](https://user-images.githubusercontent.com/21696690/230736932-f8f751d6-a750-4591-8a42-3deaea4dd822.png)

![image](https://user-images.githubusercontent.com/21696690/230736972-2b4d9fda-aa58-42be-a090-af6d3e25b763.png)

**Comment by TagoDR** [comment]
The 'News' page has a different class names for its structures. It should work now.
I'm trusting these domains you listed, I can't test them all.

**Comment by wernser412** [comment]
The same here, little by little I also added domains.
https://github.com/wernser412/MangaOnlineViewer-Edited
Add the missing domains please.

**Comment by TagoDR** [comment]
I've merged these domains as well, also made it easier to add more if needed.
