### ISSUE TITLE
Is it possible to modify the position of the start button?

### ISSUE THREAD

**Issue by lhj5426** [TagoDR/MangaOnlineViewer#315]
https://user-images.githubusercontent.com/30548000/230853419-2a2d3d8c-ffa8-48fb-a497-8b5f5021bf8c.mp4

Dear developer,

After your last update, the script runs perfectly on my phone. I would like to express my gratitude to you for that. However, I have encountered a problem after using it for some time. As you can see in the video, the size of the phone screen has exceeded the size of the palm of my hand. For single-handed operation, my thumb needs to be fully extended to barely reach the manually clicked start button. Perhaps it is my short fingers that are to blame. Therefore, could you please adjust the position of the start button from the right side to the left side and slightly increase its size? This would make it much easier to operate with my thumb on the phone. Would that be possible? Thank you!

![image](https://user-images.githubusercontent.com/30548000/230853495-da16a567-8ada-4ea2-870d-85cfd35e2ae2.png)

**Comment by TagoDR** [comment]
Thinking about phones, maybe the button is better at the bottom.
The button was supposed to be larger, it's weird, any idea what is the resolution of your phone?

**Comment by lhj5426** [comment]
> Thinking about phones, maybe the button is better at the bottom. The button was supposed to be larger, it's weird, any idea what is the resolution of your phone?

![image](https://user-images.githubusercontent.com/30548000/231186595-f54981e6-6aed-4205-9ee9-b4e2c67519b9.png)

 a more stable solution to accommodate both left and right-handed use would be to have one button on the left and another on the right in this blank space. However, having two identical buttons on the same webpage would look odd. 
 
 hope there can be a better solution. I apologize for the inconvenience caused and express my gratitude for your assistance
