### ISSUE TITLE
Hello, can you add a setting to the toggle button to adjust its position?"

### ISSUE THREAD

**Issue by Avalon913** [TagoDR/MangaOnlineViewer#316]
"Because some works only require the user to click on an image to take a quick glance, rather than viewing the entire content, it may not be necessary to enable the script. Placing a button in the middle may affect the viewing experience, unlike before when it was positioned at the top and did not affect the viewing experience."

**Comment by TagoDR** [comment]
Thinking about phones, maybe the button is better at the bottom.

**Comment by Avalon913** [comment]
Thank you very much. Your script works very well
