### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by User4469** [TagoDR/MangaOnlineViewer#32]
Hey, thanks a lot for building this!

So, on some of these sites when I am checking out a CG from a game for example published as a comic on their site, I would prefer to have another view option to switch from appending all images one below another to be able to see only one image which you can then click next and so on to see all other images. Those images would need to be preloaded in order to display instantly if the user is going through them fast.

The preloading of images can also be added as a standalone feature to all these already supported sites so the site can keep its style and layout but all images will already be requested so they can be again scrolled through much faster, since on some of these sites only a couple if any future images would be requested, which are not always displayed soon enough if the user is scrolling a bit fast.

Overall thanks again on making this, I think just adding another view option would be a little easier than messing with the requests that are being sent for those images from a site, so if you think you could add this anytime soon I would very much appreciate it.

**Comment by TagoDR** [comment]
This script was born exactly to go against seeing just one image at a time, on sites with or without preloading (especially without).
Its not a different view option, its a different engine, Your request is basically disabling my script, most sites just do what you want with my script disabled. They just dont support fast switching of images.

**Comment by User4469** [comment]
Very well, the main point would be for all the images to start loading when you start browsing from any point, but I get that's not within the scope of this. I'll create my own script to preload all the images then, I just asked in case it could be achieved with some minor changes. Thanks
