### ISSUE TITLE
Usage of bookmarks ?

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#323]
How can I use bookmarkes exactly thers is no butten to add bookmarkes and no Keybindings.

**Comment by TagoDR** [comment]
You bookmark the page you want, the next time you open the chapter it will resume from the bookmark

**Comment by big-cat-loaf** [comment]
I dont want to be annoying but how can I bookmark to a  page? Where is the butten to bookmark a page? 
I haven't found it yet or it doesn't exist.

**Comment by big-cat-loaf** [comment]
Sorry I faund it 
thank you for your help!!!
