### ISSUE TITLE
infinity Error spam in console

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#325]
I know not much abaut Programming but I know that 1000+ Errors in console is not normal 
https://www.webtoons.com/en/romance/down-to-earth/s2-episode-109/viewer?title_no=1817&episode_no=109
https://github.com/TagoDR/MangaOnlineViewer/assets/100969549/f1074e07-dc04-4eeb-abfe-7b98c158d75d

**Comment by TagoDR** [comment]
Go to your settings, and reset them.
Then try configuring it again the way you like slowly, to figure out which setting is breaking something

**Comment by big-cat-loaf** [comment]
The settings have nothing to do with it. I tested the sript with Google Chrome, not addons activated, newest Vision of Crome, default script with not changes made but the errors keep appearing

**Comment by big-cat-loaf** [comment]
Logs: 
[www.webtoons.com-1683912710682.log](https://github.com/TagoDR/MangaOnlineViewer/files/11466545/www.webtoons.com-1683912710682.log)

**Comment by big-cat-loaf** [comment]
Could it be that it has to do with www.webtoons.com it appears that the errors are only on this website.

**Comment by TagoDR** [comment]
Found it, it only happens in chrome.
The error is not from my script, it's the website JavaScript that is missing the components I destroyed when changing the page.
You can safely ignore them
