### ISSUE TITLE
Cant Scroll 

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#327]
https://www.webtoons.com/en/challenge/my-blushing-bride/16/viewer?title_no=857440&episode_no=17 

The popup:NOTICE: This series contains adult themes and situations and is recommended for mature audiences. Viewer discretion is advised. Proceed to view content? blocks the scrolling

**Comment by TagoDR** [comment]
Disable the script temporarily and reload, after you accept it once it shouldn't ask again
