### ISSUE TITLE
[Feature] Zip Download name with chapter number

### ISSUE THREAD

**Issue by aerojun** [TagoDR/MangaOnlineViewer#33]
When downloading the chapter as zip, append the chapter number to the zip name.

**Comment by TagoDR** [comment]
The chapter number is not something I have on hand when the script runs, I have e the title though,  witch in many cases contains the chapter number, that is what I use for the zip.

**Comment by aerojun** [comment]
When downloading from batoto, it downloads the zip with the series name.
