### ISSUE TITLE
[Feature request] 100x page loading 

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#332]
please add 100x page loading, 
Its only for people with really good Internet speed. 
Is only needed for large chaper like:
https://www.webtoons.com/en/fantasy/the-tyrant-wants-to-be-good/episode-12/viewer?title_no=5201&episode_no=12 

This is a comparison of both of them. 
https://github.com/TagoDR/MangaOnlineViewer/assets/100969549/60d6a131-a5bb-40ec-8824-da5b0a9f7de9

I add  :

"<option value='10' ${useSettings().throttlePageLoad === 1000 ? "selected" : ""}>
            100(${getLocaleString("EXTREME")}) </option>"

**Comment by TagoDR** [comment]
I've added it, but I don't really recommend, may kill some servers or get your IP marked as DDoS attacker

**Comment by big-cat-loaf** [comment]
Can you put an warning popup like you did by "Enable Lazy Load Images:" butten? (for new user) or would that be to complicated?

**Comment by TagoDR** [comment]
Yes I can
