### ISSUE TITLE
e-hentai & exhentai doesn't work

### ISSUE THREAD

**Issue by seventhsky** [TagoDR/MangaOnlineViewer#333]
update version 2023.06.19
script doesn't work both e-hentai & exhentai

**Comment by big-cat-loaf** [comment]
exhenthai isn't loading and hier is an Error from e- henthai 

MangaOnlineViewer:  RangeError: invalid array length
    run moz-extension://9878d04c-ac4e-4a59-947b-cf42bb70d2c0/userscripts/Manga OnlineViewer Adult.user.js?id=fa9af746-4f6a-4e29-a0a2-5cdde9d5f644:513
    preparePage moz-extension://9878d04c-ac4e-4a59-947b-cf42bb70d2c0/userscripts/Manga OnlineViewer Adult.user.js?id=fa9af746-4f6a-4e29-a0a2-5cdde9d5f644:4160
    waitExec moz-extension://9878d04c-ac4e-4a59-947b-cf42bb70d2c0/userscripts/Manga OnlineViewer Adult.user.js?id=fa9af746-4f6a-4e29-a0a2-5cdde9d5f644:4196
    start moz-extension://9878d04c-ac4e-4a59-947b-cf42bb70d2c0/userscripts/Manga OnlineViewer Adult.user.js?id=fa9af746-4f6a-4e29-a0a2-5cdde9d5f644:4206
    window["__f__lj4x4kuw.zwj"]/</< moz-extension://9878d04c-ac4e-4a59-947b-cf42bb70d2c0/userscripts/Manga OnlineViewer Adult.user.js?id=fa9af746-4f6a-4e29-a0a2-5cdde9d5f644:4212
    window["__f__lj4x4kuw.zwj"]/< moz-extension://9878d04c-ac4e-4a59-947b-cf42bb70d2c0/userscripts/Manga OnlineViewer Adult.user.js?id=fa9af746-4f6a-4e29-a0a2-5cdde9d5f644:4214
    St https://e-hentai.org/s/e776258f09/2586645-2:9
    window["__f__lj4x4kuw.zwj"]/< moz-extension://9878d04c-ac4e-4a59-947b-cf42bb70d2c0/userscripts/Manga OnlineViewer Adult.user.js?id=fa9af746-4f6a-4e29-a0a2-5cdde9d5f644:1
    "__f__lj4x4kuw.zwj" moz-extension://9878d04c-ac4e-4a59-947b-cf42bb70d2c0/userscripts/Manga OnlineViewer Adult.user.js?id=fa9af746-4f6a-4e29-a0a2-5cdde9d5f644:1
    St https://e-hentai.org/s/e776258f09/2586645-2:9
    n https://e-hentai.org/s/e776258f09/2586645-2:71
    <anonymous> https://e-hentai.org/s/e776258f09/2586645-2:74
    g https://e-hentai.org/s/e776258f09/2586645-2:68
Manga OnlineViewer Adult.user.js:1352:13

**Comment by TagoDR** [comment]
Fixed
