### ISSUE TITLE
add manhwafreak.com

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#334]
please add manhwafreak.com 
example: https://manhwafreak.com/v1-the-vampire-lords-greatest-wife-ch-01/
has no lazy load and a very simple cdn structure.

**Comment by TagoDR** [comment]
Added, last image seens to always be a loading one, werd.

**Comment by big-cat-loaf** [comment]
That a bug in the website I don't why but just exclude the last page to be loaded
