### ISSUE TITLE
[bug/enhancement] unreadable color Contrast

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#336]
bug:
![Screenshot 2023-06-30 113558](https://github.com/TagoDR/MangaOnlineViewer/assets/100969549/594c7d3c-26a6-4003-b6bf-71ce4cad0eda)
![Screenshot 2023-06-30 113531](https://github.com/TagoDR/MangaOnlineViewer/assets/100969549/97f1268b-6036-4dc0-bb21-4f999af14e69)
https://reaperscans.com/comics/1167-pick-me-up/chapters/28358959-chapter-48

enhancement:
adding to the already existing dark and white mods 
a dark and white mode to the commands with 
dark backround - white font and 
white backround - dark font 
or you could just be lazy and add the native color Contrast of the website.

**Comment by TagoDR** [comment]
should be better now
