### ISSUE TITLE
asurascans.com comments bypass 

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#339]
The asurascans comments have a policy that blockes the loading of 3rd party source can you bypass that or its a bug of the script. 
Can you fix it?
Error massage: We were unable to load Disqus. If you are a moderator please see our [troubleshooting guide](https://docs.disqus.com/help/83/).

**Comment by TagoDR** [comment]
Reading comments works just fine in Asurascans. 

What do you mean by 'commands' ?  Disqus's settings? I don't edit its settings or even use Disqus directly, I only cut and paste what is already at the site.

Please take a look at your ad blocker, It may have been set to too sensitive. And it's preventing it from loading to begin with, or fast enough for me to retrieve it.

**Comment by big-cat-loaf** [comment]
I found out that I used to modify comments which the have some sorte protection against it because every other site is allows it. 
disqus.com##.reaction-items
disqus.com##.nav-primary.nav
disqus.com##.disqus-footer
disqus.com##.postbox > div > div > div
disqus.com##.compose-wrapper
disqus.com##.nav-secondary.nav
disqus.com##.publisher-anchor-color.comment-policy-refresh
disqus.com###badges-message__container
disqus.com##.thread-likes > div
disqus.com##.spacing-bottom-small.align--center.align.text-bold
(uBlock Origin) 

 commands = camments. Just a writing mistake sorry

**Comment by big-cat-loaf** [comment]
There are 4 3rd party advertising that must be loaded you can block them but the must be loaded to show comments. 
referrer.disqus.com
links.services.disqus.com
static.cloudflareinsights.com
cdn.viglink.com
When you use your srcipt it doesn't laod the advertsers exept static.cloudflareinsights.com.
