### ISSUE TITLE
No longer works on Jaimini's Box

### ISSUE THREAD

**Issue by kah0922** [TagoDR/MangaOnlineViewer#34]
Trying to use the script on Jaiminis' Box [(example URL)](https://jaiminisbox.com/reader/read/tokyo-ghoul-re/en/0/157/page/1) will cause an anti-crawler mechanism to trigger

![Screenshot](https://i.imgur.com/GWTLypU.png)

**Comment by TagoDR** [comment]
Jaiminis has a small collection of mangas, therefor I don't directly support it. I use to work before because it uses FoolSlide.
I'll think about it, if I find a way around this DRM I may implement it.

**Comment by kah0922** [comment]
Worse comes to worse, you could always add it to the exclude list.

**Comment by TagoDR** [comment]
Ok Fixed/Added
