### ISSUE TITLE
add cubari.moe

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#343]
example: https://cubari.moe/read/gist/Z2lzdC9mdW5reWhpcHBvLzFkNDBiZDVkYWUxMWUwM2E2YWYyMGU1YTlhMDMwZDgxL3Jhdy9vcG0uanNvbg/
The wants to activate on this domain but mistakes it as FoOlSlide and  Kireicake and looks for img.open witch it doesn't find. 

![Screenshot 2023-07-23 232341](https://github.com/TagoDR/MangaOnlineViewer/assets/100969549/1c8d14b8-7903-4d65-97a9-7f956b19ff3c)

It could be hard or Impossible to make a script because the images are Private hosted.

**Comment by TagoDR** [comment]
Denied, That is not really a manga site, nothing can be reasonably searched there, someone created a repository for just that manga.
