### ISSUE TITLE
The BUG of random maximum value for input numbers

### ISSUE THREAD

**Issue by lhj5426** [TagoDR/MangaOnlineViewer#344]
https://github.com/TagoDR/MangaOnlineViewer/assets/30548000/83192b26-679d-4838-878a-e7e125faf98d

Hello, esteemed developer,

As you can see in the demonstrated video,
When inputting a number within the maximum value range,
There is a random bug that automatically fills in the maximum value.
Could you please fix it?

**Comment by lhj5426** [comment]
https://github.com/TagoDR/MangaOnlineViewer/assets/30548000/e9f4c318-e0d6-4f9f-a0c5-9f0afc621c27

When entering a number within the maximum value, if it is smaller than or equal to the minimum value, the number in the maximum value field immediately changes to the minimum value. With a slight delay before entering the second number, the content in the maximum value field becomes the maximum value instead of the input.

In the video, I originally intended to input 18, but due to a delay, the number 1 in the maximum value input field changed to 3. Then, when I entered 8, it became 38. As a result, with a maximum value of 22, it automatically reverted back to the maximum value of 22.

**Comment by TagoDR** [comment]
That is actually working as intended.
I may just increase the wait timer for refreshing the range, now it is 300ms, 600ms should be enough and still fell responsive.

**Comment by lhj5426** [comment]
> That is actually working as intended. I may just increase the wait timer for refreshing the range, now it is 300ms, 600ms should be enough and still fell responsive.

Can I ask how to modify this delay in the code, in terms of how many lines of code? I want to increase it because sometimes my physical and mental state can cause my actions to be sluggish. So I would like to adjust this delay as much as possible based on my own condition.

I don't mind adjusting this delay every time.

**Comment by lhj5426** [comment]
> This is the line that controls the delay
> 
> ` const observerEvent = _.debounce(changedInput, 600);`
> 
> searching for "changedInput" should be easy
 const observerEvent = _.debounce(changedInput, 1000);
 I changed it to 1000, and now it feels much more comfortable to use. Thank you very much.
