### ISSUE TITLE
add https://dragontea.ink/ 

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#347]
same cdn Asura Scans, Flame Scans, Realm Scans, Voids-Scans, Luminous Scans, Shimada Scans, Night Scans and ManhwaFreak. 
It has a really weard website that can break easily and hates adblocker or any 3rd party scripts witch could be a issue. 

example: https://dragontea.ink/novel/evolution-begins-with-a-big-tree/chapter-86/

**Comment by TagoDR** [comment]
Added
