### ISSUE TITLE
Script doesn't activate on reaperscans on some/most pages

### ISSUE THREAD

**Issue by kajitdahli** [TagoDR/MangaOnlineViewer#355]
it seems not too long ago reaperscans added a cloudflare challenge t certain chapters, but not for the page itself, rather for the images of the chapter.

It seems the script only loads when one solves this captcha

See attached videos

(Tried with different browsers/script managers same result and tried F5 as well)

### Script activates when there is captcha
https://github.com/TagoDR/MangaOnlineViewer/assets/142594903/0b38d658-2577-4f65-bd58-3d0945795b14

### Script doesn't activate when there is no captcha
https://github.com/TagoDR/MangaOnlineViewer/assets/142594903/ed0e7730-aa48-46a5-9803-10debeb2a19c

**Comment by TagoDR** [comment]
Should be fixed now
