### ISSUE TITLE
Nfsw. Add support to 8muses additional domain 

### ISSUE THREAD

**Issue by swathigrate** [TagoDR/MangaOnlineViewer#357]
Hello sir ,
https://8muses.io/ this is working perfectly....
8muses had another domain ".com" ..they are updating in this domain... please add support to this domain also....
https://comics.8muses.com/
https://comics.8muses.com/comics/
Example: [Example](https://comics.8muses.com/comics/picture/Hentai-and-Manga-English/Kishizuka-Kenji/Bashful-Bunny/3)....]

Another issue is .... It is starting from the first page only... And not starting from our desire clicked image ...
For example .... If u clicked 57th image..... But  it's starting from Frist image...... It's taking extra data ....

Please solve this issues ... thankyou

**Comment by TagoDR** [comment]
Added
if you want it to start from a specific page, cancel it then manually start, so you can pick the pages
