### ISSUE TITLE
Notable to start from specific page

### ISSUE THREAD

**Issue by swathigrate** [TagoDR/MangaOnlineViewer#358]
Added
if you want it to start from a specific page, cancel it then manually start, so you can pick the pages

_Originally posted by @TagoDR in https://github.com/TagoDR/MangaOnlineViewer/issues/357#issuecomment-1694333402_
            

Hello sir , 

I checked in 3-4 sites .(8muses,.https://9hentai.to/g/72029/, e-hental)...not working in manually.... but It's starting from 1st page onwards....
Check onces..

https://9hentai.to/g/72029/

**Comment by TagoDR** [comment]
You mean this is now showing? If you set the script to start immediately, you will never see it.
![image](https://github.com/TagoDR/MangaOnlineViewer/assets/9999209/08a8d2eb-102a-4f3b-8284-95a7f79efac9)

**Comment by swathigrate** [comment]
> You mean this is not showing? If you set the script to start immediately, you will never see it. ![image](https://user-images.githubusercontent.com/9999209/263543542-08a8d2eb-102a-4f3b-8284-95a7f79efac9.png)

Ok ok ....... understood......thanks
