### ISSUE TITLE
lightnovelworld.com error 

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#359]
trys to activate on lightnovelworld.com but it isn't a manga site. 

![Screenshot 2023-08-31 133306](https://github.com/TagoDR/MangaOnlineViewer/assets/100969549/fbca02ae-e330-4974-be96-37dfb24a3744)

**Comment by TagoDR** [comment]
It seems they are using the madara WordPress plugin to host the site.
There shouldn't be a problem, if the script doesn't find any pages it just aborts.
Does it actually activate? If it does, I will blacklist the site.
