### ISSUE TITLE
[Add, Hentai] nhentai.xxx, nhentai.to (fake mirrors, maybe)

### ISSUE THREAD

**Issue by BloodDragooner2** [TagoDR/MangaOnlineViewer#365]
Awesome stuff!!! Is it possible for you to add nhentai.xxx and nhentai.to? net is sadly inaccessible for me :( 
Thank you!

**Comment by TagoDR** [comment]
It already does work with them

**Comment by BloodDragooner2** [comment]
Oh i see! Cheers!
