### ISSUE TITLE
Jaimini's Box still doesn't work

### ISSUE THREAD

**Issue by el0d** [TagoDR/MangaOnlineViewer#37]
I know you've recently tried to fix Jaimini's Box but it still doesn't work for me.
The issue is a bit different now though:
At first the image of the page seems to load correctly for a moment but then it suddenly transforms into futileeffort.jpg and soon after the image disappears entirely, this repeats for every page from first to last and in the you end with no images.

I've got the log too but it's kind of big so I'm hesitant to post it directly. For now I'll just [upload it as a txt here](https://gist.githubusercontent.com/el0d/29578266700b9700b07239f9a19b1493/raw/0bf6a799ba1551a91f0a8337a5a14e571b1cafc8/jaiminisbox.txt)

Thanks for your work on the script.

**Comment by TagoDR** [comment]
I believe I fixed it now

**Comment by el0d** [comment]
Yeah, it's fixed. Thank you
