### ISSUE TITLE
[Bug] comments doesn't work on any website

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#370]
example: https://www.mangageko.com/reader/en/please-stop-summoning-me-chapter-72-eng-li/
https://www.mangageko.com/reader/en/the-case-in-which-streaming-in-another-world-led-to-the-creation-of-a-massive-yandere-following-chapter-1-eng-li/

**Comment by TagoDR** [comment]
Should be fixed now
