### ISSUE TITLE
Asurascans Next Chapter Issue

### ISSUE THREAD

**Issue by machetemike** [TagoDR/MangaOnlineViewer#373]
I have an issue that started happening with the update on the 3rd. 

Previously, it had stopped functioning on Asura, I believe because they changed to Asuratoon - so I edited the sitelist to include Asuratoon and everything was fine. 

However, after the update on the 3rd and also with the update on the 5th I would no longer reliably get the 'Next Chapter' button at the end of a chapter that had another chapter after it.

When the chapter first loads it will display the 'Download' 'Next' and 'Previous' buttons however when I get to the end of the chapter, only the 'Download' button is visible, and if I scroll back up to the top the 'Next' and Previous' buttons that were there previously, are gone. 

This does not happen *all* of the time, but it is happening around 60~70% of the time. Reloading the page and waiting for the plugin again brings the buttons back when this does happen. 

Running Violentmonkey and Firefox 118.0.1

**Comment by TagoDR** [comment]
I've noticed it too, I've reinstated the wait for chapter list, hopefully its twin sites doesn't break.
