### ISSUE TITLE
After setting the language in the script, it is unable to display the corresponding language correctly.

### ISSUE THREAD

**Issue by lhj5426** [TagoDR/MangaOnlineViewer#374]
![image](https://github.com/TagoDR/MangaOnlineViewer/assets/30548000/1a1f81cc-292c-4f54-a986-2a3886d832e9)
Hello developer, today I updated the script to the version released on October 6th. After updating, I ran the script and changed the language just like in the image you saw. However, even though I switched the language, the language on the script's UI did not change accordingly. I did perform a reload after switching the language. I have not encountered this issue before. Could you please help me fix it?

**Comment by TagoDR** [comment]
should be Fixed now

**Comment by lhj5426** [comment]
Thank you so much
