### ISSUE TITLE
looks like imhentai need to add m8 and update the m7 on the findServer function

### ISSUE THREAD

**Issue by martelor** [TagoDR/MangaOnlineViewer#379]
line 485

 function findServer(cId) {
    if (cId > 0 && cId <= 274825) {
      return "m1.imhentai.xxx";
    }
    if (cId > 274825 && cId <= 403818) {
      return "m2.imhentai.xxx";
    }
    if (cId > 403818 && cId <= 527143) {
      return "m3.imhentai.xxx";
    }
    if (cId > 527143 && cId <= 632481) {
      return "m4.imhentai.xxx";
    }
    if (cId > 632481 && cId <= 816010) {
      return "m5.imhentai.xxx";
    }
    if (cId > 816010 && cId <= 970098) {
      return "m6.imhentai.xxx";
    **}
    if (cId > 970098 && cId <= 1121109) {
      return "m7.imhentai.xxx";
    }
    return "m8.imhentai.xxx";**
  }

**Comment by TagoDR** [comment]
Updated
