### ISSUE TITLE
[bug] Image not loading

### ISSUE THREAD

**Issue by kakarisu** [TagoDR/MangaOnlineViewer#380]
Image not loading if i don't start from the first page

https://github.com/TagoDR/MangaOnlineViewer/assets/116163332/243ef085-d51a-4a8a-aa22-5fdee6f90f40

**Comment by TagoDR** [comment]
Lazy load should be fixed.
This site in the only one that starts from the selected page, this was a request from someone a while back. To start from the first page open it directly , or change the loading mode from immediate to normal so you may choose the page manually
