### ISSUE TITLE
Bug with offline files loading

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#383]
I use ungoogle Cromium. 
I have this error when trying to open any file
![Screenshot 2023-11-23 201050](https://github.com/TagoDR/MangaOnlineViewer/assets/100969549/7546bafc-4d85-497b-8d31-3744e1cae502)
and when I tryed to downlaod I just got code and I did manual downloaded form the main branche. 
Did I do anything wrong?

**Comment by TagoDR** [comment]
yes those errors are fine, ignore them, but you need to update the script

**Comment by big-cat-loaf** [comment]
The script is on the newerst version,  last update 13 h ago
 (2023.11.23) 
(the srcipt doesn't work

**Comment by TagoDR** [comment]
I can see in the image that the script was not triggered, try to force reinstall the script.
