### ISSUE TITLE
ex hentai problem  auto start at 3 sec please remove that 

### ISSUE THREAD

**Issue by josh56424** [TagoDR/MangaOnlineViewer#39]
ex hentai problem  auto start at 3 sec please remove that
 
issue
1-i want to start this viewer when i click on image ?
2-why loading only 20 pages on ex hentai please increase is ?

thanks for you hard work

**Comment by CoLdAs1cE** [comment]
there is a setting that start script instant

**Comment by himouto** [comment]
he's probably referring to the issue where the script automatically loads the images even when you haven't click any image on the gallery yet like viewing the gallery thumbs only, also it only loads the first page set of images it doesn't recognize the next set [1] [2] [3]. this only happens in exhentai, other site works fine.

**Comment by josh56424** [comment]
yes you are right hentai cafe works fine

**Comment by josh56424** [comment]
but exhentai is really pain 
if try open artist cg or game cg whole thing is messup the reading 
and page refresh is not working exhentai
currently only script that works is this but incomplete exhentai 
please repair that
