### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by Mpigest** [TagoDR/MangaOnlineViewer#390]
Hi developer, thanks for your work, It was a wonderful experience using your script ! :D
  I noticed that the script doesn't have the 'full-screen expansion' function. I believe adding full-screen expansion can significantly enhance the reading experience. So I hope you can consider incorporating this function in future developments. THX a lot!!!

**Comment by TagoDR** [comment]
Please give more details of what you mean. All browsers have a full screen for web page just press F11, whats different form your vision.

**Comment by Mpigest** [comment]
> Please give more details of what you mean. All browsers have a full screen for web page just press F11, whats different form your vision?

Thanks for the answer! I apologize for my ignorance; I wasn't aware of the full-screen function that comes with the browser. I suggested this function because a script reader I used before had a full-screen button. However, I believe we can still improve user experience by including a text description to help users like me who might not be aware of this feature.

**Comment by Mpigest** [comment]
Sorry for one more question. I just tried using the left-to-right reading mode and noticed that there is always a blank page below, even with adaptive height. I may have missed noticing that the script already has this function, but I believe the reading experience could be improved if the image fills the entire screen. Therefore, I hope we can consider improving the left-to-right reading mode in the subsequent development process to allow the image to fill the entire screen.  :D
<img width="960" alt="PixPin_2023-12-06_12-37-42" src="https://github.com/TagoDR/MangaOnlineViewer/assets/107930642/f1658eb5-98a6-443a-aef6-f0ac5818d19d">
