### ISSUE TITLE
E-hentai images fail to load

### ISSUE THREAD

**Issue by WntFlm** [TagoDR/MangaOnlineViewer#393]
Recently, several images fail to load in the manga viewer.

<img width="419" alt="image" src="https://github.com/TagoDR/MangaOnlineViewer/assets/34620278/0b108de5-eda7-43ab-8e0e-daa7593603d2">

I attempted to resolve the problem. When entering a gallery, the browser initiates a request to the page `https://exhentai.org/s/${startkey}/${gid}-${startpage}` and attempts to load the image URL within `<div id="i3">`. In case the image fails to load, it triggers the `nl(nl_value)` function, redirecting the page to `https://exhentai.org/s/${startkey}/${gid}-${startpage}?nl=${nl_value}`, which contains an alternative source for the image.

The problem is that MangaOnlineViewer will only read and load the image URL in the initial request. So when the first source is unavailable, it fails to attempt a next one and continuously requests the broken URL.

It seems hard for me to edit the codes instantly. Any assistance in fixing this bug would be greatly appreciated.

**Comment by TagoDR** [comment]
Sorry but its a connection problem usually.
This function you mentioned is just there to change the url, the goal is to force getting the image ignoring the cached data.
My script does that already, this is where I got the idea from.

**Comment by WntFlm** [comment]
Could you please provide additional clarification on how this script "ignores the cached data"?

From my observations, when accessing the page `https://exhentai.org/s/${startkey}/${gid}-${startpage}`, it retrieves the source image from the H@H network, denoted as `image_src_0`. However, when navigating to the page `https://exhentai.org/s/${startkey}/${gid}-${startpage}?nl=${nl_value}`, it obtains a different image URL (from another H@H network), referred to as `image_src_1`. The script seems to focus solely on fetching the former page and `image_src_0.

In cases where `image_src_0` becomes unreachable (typically occurring for 1 out of ~20 pages under my network), the script attempts to fetch `${image_src_0}?cache=${repeat_count}`, yet this effort usually proves unsuccessful. The more effective solution would involve retrieving `image_src_1`, which appears to be consistently accessible.

This issue seems to have arisen following a H@H update on [2023-10-27](https://e-hentai.org/news.php#:~:text=with%20many%20pages.-,2023%2D10%2D27,-%2D%20H%40H%20High). Some related tools have addressed and resolved this issue subsequently, such as https://github.com/EhViewer-NekoInverter/EhViewer/commit/5e99c7a954e4f7a12be820becf678f8ad1f86c9b and https://github.com/jiangtian616/JHenTai/commit/f23b97d6c15b9299f953180eef346973a3b39ad8.

I attempted to fix the problem within this script. However, it seems that the current architecture uses a uniform logic for image extraction, loading, and retrying across all sites. Unfortunately, this architecture does not directly support the solution I mentioned above. Maybe we could add a custom `reloadImage` or `onImagesFail` function for a certain sites like E-Hentai, allowing retrieval of `image_src_1` when `image_src_0` fails to load.

**Comment by TagoDR** [comment]
### What this site does is:
When the image fails loading they call a function "nl" that changes the webpage url with dummy data( ?nl=code), that requests a new webpage with a new image url.
```html
<img id="img" src="https://[...].jpg" onerror="this.onerror=null; nl('43035-474070')" >
```
```js
function nl(a) {
  document.location += ( - 1 < (document.location + '').indexOf('?') ? '&' : '?') + 'nl=' + a;
  return !1
}
```
### What my script does(works on any/most sites):
When the image fails loading I call a function that changes the image url with dummy data( ?cache=anything), that makes the browser believe its a different image so it tries to fetch it in full again, instead of just pulling it from its cache data.

### Solution
I would need to create a system to load alternative pages an extract the src in case a image fails. Its not simple, would require I change the core of the script with a fixed solution for a single site. When more often its just a connection issue, or just slowing down the load speed to fix.
I wont pollute the core of the script with single site solutions. However if you really need it , replace the functions below manually:

```js

function reloadImage(img) {
  const src = img.getAttribute('src');
  if (!src) return;
  const alturl = img.getAttribute('alt-url');
  img.removeAttribute('src');
  if (alturl) {
    const selector = img.getAttribute('selector');
    if (selector) {
      getElementAttribute(alturl, selector).then((alt) => {
        if (alt) {
          img.setAttribute('src', alt?.getAttribute('src') ?? '');
          img.setAttribute('alt-src', invalidateImageCache(src, getRepeatValue(src)));
        }
      });
    }
  } else {
    img.setAttribute('src', invalidateImageCache(src, getRepeatValue(src)));
  }
}

async function getElementAttribute(
  url,
  selector,
) {
  return fetchHtml(url).then((doc) => doc.querySelector(selector));
}

function findPage(
  manga,
  index,
  pageUrl,
  lazy,
) {
  return async () => {
    const res = await getElementAttribute(pageUrl, manga.img);
    const src = res?.getAttribute(manga.lazyAttr ?? 'src');
    const alt = res?.getAttribute('onerror')?.match(/nl\('(.+)'\)/)?.[1];
    const img = document.querySelector(`#PageImg${index}`);
    if (src && img) {
      img.style.width = 'auto';
      const imgLoad = imagesLoaded(img.parentElement!);
      imgLoad.on('done', onImagesSuccess);
      imgLoad.on('fail', onImagesFail);
      img.setAttribute('src', src);
      if (alt) {
        img.setAttribute('alt-url', `${pageUrl}?nl=${alt}`);
        img.setAttribute('selector', manga.img);
      }
      logScript(`${lazy && 'Lazy '}Page: `, index, ' Source: ', img.getAttribute('src'));
    }
  };
}

```
