### ISSUE TITLE
BUG The local script has appeared on the navigation page.

### ISSUE THREAD

**Issue by lhj5426** [TagoDR/MangaOnlineViewer#395]
https://github.com/TagoDR/MangaOnlineViewer/assets/30548000/66672fe6-7935-46d6-96bd-0c66fcfb20d8

The script suddenly loaded on the navigation page for some reason. 

Today, when I opened the browser as usual, the navigation page in this video is a local HTML navigation page. But for some reason, the script for reading comics locally suddenly loaded on my local navigation page.

**Comment by TagoDR** [comment]
Should be fixed
