### ISSUE TITLE
[Feature Request] Add this website

### ISSUE THREAD

**Issue by zkisaboss** [TagoDR/MangaOnlineViewer#400]
Can you add support for this manga website?
https://ww7.mangakakalot.tv/chapter/manga-jt987302/chapter-32

**Comment by TagoDR** [comment]
Its a clone of [Mangakakalot](https://mangakakalot.com/)/[MangaNelo](https://www.manganelo.com/)/[MangaNato](https://www.manganato.com/) but I dont know if is good or safe, just use the originals
