### ISSUE TITLE
[Feature request] Add Icon to make userscript look more professional

### ISSUE THREAD

**Issue by zkisaboss** [TagoDR/MangaOnlineViewer#404]
You can pick any icon you want, I like [GraphicLoads](https://www.iconarchive.com/artist/graphicloads.html) icon pack.

**Comment by TagoDR** [comment]
I use [Tabler Icons](https://tabler.io/icons) in the script. They are clearly visible and lightweight.

**Comment by zkisaboss** [comment]
I'm talking about purely [aesthetic icons](https://i.gyazo.com/dd4e09243623c346ebc434dbdb51623f.png). You add these by declaring `// @icon         https://{...}.png`

**Comment by zkisaboss** [comment]
@TagoDR Thank you for making the script, it makes my internet eperience sooo much better

**Comment by TagoDR** [comment]
Found some icons that are nice enough
