### ISSUE TITLE
flamecomics.com only loads the first page and nothing else

### ISSUE THREAD

**Issue by duradara** [TagoDR/MangaOnlineViewer#405]
URL examples: 
https://flamecomics.com/is-this-hero-for-real-chapter-99/ 
https://flamecomics.com/is-this-hero-for-real-chapter-100/  

Image of whats happening:
https://imgur.com/2b72nfa

**Comment by TagoDR** [comment]
I could not reproduce it, please reinstall the script.
Check your add-ons, something else seems to be interfering with formating.
If it persists open the console(F12) see if there is any errors

**Comment by duradara** [comment]
I reinstalled the extension, disable m other extensions and tried other browser and it still doesn't work

Here is the f12 info

![1](https://github.com/TagoDR/MangaOnlineViewer/assets/50158352/7296429c-86fa-45f3-b241-c255b78a249c)
![2](https://github.com/TagoDR/MangaOnlineViewer/assets/50158352/afedc95e-125b-4438-a065-df4d7d0d49af)
![3](https://github.com/TagoDR/MangaOnlineViewer/assets/50158352/b7acb05a-ff42-4f30-8ad4-1c468db3aa61)
![4](https://github.com/TagoDR/MangaOnlineViewer/assets/50158352/d954b51c-32eb-46ce-9ad3-08b9f07de7e3)

**Comment by TagoDR** [comment]
Look for the line "Manga Online Viewer: Method Images: Array(21)" expand this array, I want to see if there is something wrong with the images urls.
The images were blocked by a "Tracking Prevention" feature, maybe your privacy settings are too strict? Try changing it.
If you dont have a ad blocker install one and try.

**Comment by duradara** [comment]
I just woke up and now it works without problems, maybe it was some kind of internet problem on my end.
