### ISSUE TITLE
MangaHub.io seems to broke

### ISSUE THREAD

**Issue by CoLdAs1cE** [TagoDR/MangaOnlineViewer#410]
Seems like mangahub.io has broken

**Comment by laizen** [comment]
Yeah same problem here after the last update

**Comment by TagoDR** [comment]
Fixed

**Comment by CoLdAs1cE** [comment]
Thanks for quick fix :D

**Comment by beaucarigan** [comment]
@TagoDR They changed the URL again, this time it would be to 
` const api = await fetch("https://mangahub.io/api/graphql", options).then(`

**Comment by beaucarigan** [comment]
Could test it finally, works for me, thanks for the swift update  👍
