### ISSUE TITLE
[bug] https://rizzcomic.com can't display comments 

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#411]
Error log: 
[rizzcomic.com-1705674858115.log](https://github.com/TagoDR/MangaOnlineViewer/files/13990504/rizzcomic.com-1705674858115.log)
https://rizzcomic.com

**Comment by big-cat-loaf** [comment]
I want to get a fast loading mode with a 1-second interval. Can you do it, or is it too hard to implement? When you do not, show me what value I must change to achieve it. Thanks

**Comment by TagoDR** [comment]
Should be fine now

**Comment by big-cat-loaf** [comment]
I tested your new script, and for other websites, a new bug occurred since the comments must be loaded to activate the script, but since the same website only loads the comments when you come near the button, you must scroll to the button to activate the script. My fix would be that the script starts in a preacctivate state, scrolls to the bottom, and then acctivates fully.

Url: https://www.mgeko.com/
one example:
https://github.com/TagoDR/MangaOnlineViewer/assets/100969549/1ceacc62-0efe-40d1-a8d6-f61524ed3df8
