### ISSUE TITLE
[Bug] scirpt doesn't load

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#414]
I tested your new script #144, and for other websites, a new bug occurred since the comments must be loaded to activate the script, but since the same website only loads the comments when you come near the button, you must scroll to the button to activate the script. My fix would be that the script starts in a preacctivate state, scrolls to the bottom, and then acctivates fully.
Edit: It seems that https://www.mgeko.com/ doesn't care for the comments specifically but only the bottom of the page, which means that when you just ignore the rule that the website needs the comments to load, it automatically loads when you reach the bottom of the page. same with 

Url: https://www.mgeko.com/ same with #413  https://visortmo.com/ 
one example:
https://github.com/TagoDR/MangaOnlineViewer/assets/100969549/1ceacc62-0efe-40d1-a8d6-f61524ed3df8

**Comment by TagoDR** [comment]
fixed
