### ISSUE TITLE
The bug on the mobile version.

### ISSUE THREAD

**Issue by lhj5426** [TagoDR/MangaOnlineViewer#415]
![image](https://github.com/TagoDR/MangaOnlineViewer/assets/30548000/e706d1bc-dbec-4f04-bdb0-bf872ae90602)
![image](https://github.com/TagoDR/MangaOnlineViewer/assets/30548000/b6293da8-bae7-46f8-9ec6-ba94febe24d1)
Dear developers,
I would like to report a bug to you. This bug only occurs on the mobile version. As shown in the picture, the settings here do not get saved. Every time I refresh or open a new page, this setting is reset to its default value.

**Comment by TagoDR** [comment]
What browser app are you using? Those options should not be available in mobile mode.
Are you in a tablet? Can you check your screen size please?

Did you use the bookmarklet? Settings cant be saved using it.

**Comment by lhj5426** [comment]
> What browser app are you using? Those options should not be available in mobile mode. Are you in a tablet? Can you check your screen size please?
> 
> Did you use the bookmarklet? Settings cant be saved using it.

https://play.google.com/store/search?q=mASK%20BORWser&c=apps

https://play.google.com/store/apps/details?id=com.lemurbrowser.exts&hl=zh&pli=1

https://play.google.com/store/apps/details?id=org.mozilla.firefox&hl=zh

The three browsers you mentioned all support the installation of Tampermonkey, and they all encounter the issue I described.

**Comment by TagoDR** [comment]
I've changed the mobile detection, see if it show different now, some option are supposed to be disabled in mobile devices.

**Comment by lhj5426** [comment]
https://github.com/TagoDR/MangaOnlineViewer/assets/30548000/7d96199a-b88c-4a42-93b8-9c8e251febf3

![image](https://github.com/TagoDR/MangaOnlineViewer/assets/30548000/75d8505e-a46f-4b01-a38f-fe6e9a02f075)

Dear developers,

I've always hoped that the default mode on mobile devices would be Vertical, allowing for gaps between images and icons. Although you've made adaptations for mobile, the default display mode still directly links images without leaving any gaps in between.

Is it possible to set the default mode to Vertical on mobile devices?
Thank you.

**Comment by lhj5426** [comment]
Since it can recognize mobile devices, is it possible to make the startup button adapt to different styles based on the client, for example?


 
 mobile devices
 
  const startButton = "#StartMOV {\n    font-size: 2em;\n    color: #fff;\n    cursor: pointer;\n    margin: 115px auto;\n    padding: 15px 20px;\n    text-align: center;\n    border: none;\n    background-size: 300% 100%;\n    border-radius: 50px;\n    transition: all 0.4s ease-in-out;\n    background-image: linear-gradient(to right, #667eea, #764ba2, #6b8dd6, #8e37d7);\n    box-shadow: 0 4px 15px 0 rgba(116, 79, 168, 0.75);\n    position: fixed;\n    right: 0;\n    left: 0;\n    bottom: 0;\n    z-index: 105000;\n    height: 12em;\n    min-height: 35px;\n    width: 550px;\n}\n\n#StartMOV:hover {\n    background-position: 100% 0;\n    transition: all 0.4s ease-in-out;\n}\n\n#StartMOV:focus {\n    outline: none;\n}\n";
 
![image](https://github.com/TagoDR/MangaOnlineViewer/assets/30548000/6c448971-2607-489e-b0c9-015a75e0be83)

 
 
 PC
 
  const startButton = "#StartMOV {\n    font-size: 1em;\n    color: #fff;\n    cursor: pointer;\n    margin: 49px 1541px;\n    padding: 10px 20px;\n    text-align: center;\n    border: none;\n    background-size: 300% 100%;\n    border-radius: 50px;\n    transition: all 0.4s ease-in-out;\n    background-image: linear-gradient(to right, #667eea, #764ba2, #6b8dd6, #8e37d7);\n    box-shadow: 0 4px 15px 0 rgba(116, 79, 168, 0.75);\n    position: fixed;\n    right: 0;\n    left: 0;\n    bottom: 0;\n    z-index: 105000;\n    height: 8em;\n    min-height: 35px;\n    width: 150px;\n}\n\n#StartMOV:hover {\n    background-position: 100% 0;\n    transition: all 0.4s ease-in-out;\n}\n\n#StartMOV:focus {\n    outline: none;\n}\n";
  
  
![image](https://github.com/TagoDR/MangaOnlineViewer/assets/30548000/ba141643-b8fa-428a-87bd-8b03c3b0fbe8)

On desktop browsers, there's no need to make the button so large. However, on mobile devices, the button should be larger to accommodate both left and right-handed users for easy clicking.

**Comment by TagoDR** [comment]
I tried to improve the start button.
And I'm experimenting allowing to change view mode in mobiles.

**Comment by lhj5426** [comment]
> I tried to improve the start button. And I'm experimenting allowing to change view mode in mobiles.
Thank you
"I sincerely look forward to hearing good news from you."

**Comment by TagoDR** [comment]
Everything should be fine now

**Comment by lhj5426** [comment]
![image](https://github.com/TagoDR/MangaOnlineViewer/assets/30548000/b278283e-a724-47ed-ab5e-fe61febf566f)
Yes, this time there is a gap in the page on the mobile end. Thank you very much.
