### ISSUE TITLE
[bug] https://manhwa-freak.com/

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#416]
1. The (Return to Chapter List) butten link refers to themselves.
2. The next butten link goes to a 404 Error page.
3. (optional) The last page is always a loading icon; it does not need to load (end credits of the website). It can be removed.

example: https://manhwa-freak.com/unbeatable-lv-1-ch-01-ee1a2/

**Comment by TagoDR** [comment]
Fixed it all, hopefully didn't break other similar sites.
