### ISSUE TITLE
[feature request] new dark mode 

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#419]
I would like a design of MangaOnlineViewer with #0a0c10 and #0F0D09 with a name like super dark or extrem dark.

**Comment by TagoDR** [comment]
Themes are designed to be only dependent on a single primary color. And everything else is derived from it paired with the color scheme(light and dark).
There is a custom theme, first option of the list, you can then select witch ever color you prefer.
