### ISSUE TITLE
hitomi.la images not loading

### ISSUE THREAD

**Issue by ujc75573** [TagoDR/MangaOnlineViewer#42]
Hi,

I just want to report that images in hitomi.la will not load in the viewer. As it turns out, the image links in the original page change (e.g., from **https://i.hitomi.la/galleries/xxx/xxx.jpg** to **https://0a.hitomi.la/galleries/xxx/xxx.jpg**). However, the viewer will still get the first link instead of the second one. I noticed this when I used inspector in Firefox v56.

**Comment by TagoDR** [comment]
Should be fixed now
