### ISSUE TITLE
mangahub.io

### ISSUE THREAD

**Issue by CoLdAs1cE** [TagoDR/MangaOnlineViewer#420]
mangahub.io has broken, guess they have changed somethings :D

**Comment by TagoDR** [comment]
Fixed

**Comment by CoLdAs1cE** [comment]
Thanks 😄

**Comment by CoLdAs1cE** [comment]
@TagoDR Seems like it broke again they didnt seem to be done upgrading :)

**Comment by TagoDR** [comment]
Hopefully they are done now.
