### ISSUE TITLE
[Bug] (Return to Chapter List)

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#422]
When you click on (Return to Chapter) on PC with STRG a new and the current tap, return to the chapter selection.
On some sites, like [www.mgeko.com](http://www.mgeko.com/) or https://rizzcomic.com/

https://github.com/TagoDR/MangaOnlineViewer/assets/100969549/9f331bf8-c123-4d01-9e36-c2f05aee304d

**Comment by TagoDR** [comment]
By STRG  you mean CTRL key? If so it should be fixed now.

**Comment by big-cat-loaf** [comment]
Sorry German Keyboard
