### ISSUE TITLE
[Bug] Stop false next butten 

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#425]
Sometimes it shows a next butten, even if the next chapter is not yet released. This butten goes to the previous butten. You could make it so that when the next and previous buttens go to the same webpage, the next butten would not show. 
example: https://rizzcomic.com/chapter/r2311170-all-hail-the-sect-leader-chapter-306

**Comment by TagoDR** [comment]
Should be better now
