### ISSUE TITLE
Mangadex.org missing /chapter/ from address

### ISSUE THREAD

**Issue by CoLdAs1cE** [TagoDR/MangaOnlineViewer#43]
Mangadex.org missing /chapter/ from address

some series not all when going to next chapter

so instead of https://mangadex.org/169087
it should be https://mangadex.org/chapter/169087

test on this link since this is the one i tried my self and got error
https://mangadex.org/chapter/169086

**Comment by TagoDR** [comment]
It should be fine now

**Comment by CoLdAs1cE** [comment]
seems to be working now thanks for updating so fast!
