### ISSUE TITLE
Can you directly add a progress bar in the vertical mode gap?

### ISSUE THREAD

**Issue by lhj5426** [TagoDR/MangaOnlineViewer#430]
![image](https://github.com/TagoDR/MangaOnlineViewer/assets/30548000/f7481290-c5ec-40c2-8392-150876bbf833)

Dear developer, 
Could you add a progress indicator like the one shown in the image between the gaps in this vertical mode to display the progress of flipping through each page, indicating the current page and the total number of pages?
![image](https://github.com/TagoDR/MangaOnlineViewer/assets/30548000/261771be-03b0-4cae-acee-38d7867ad268)
After adding this, it's easy to see the progress and how much has been read. It's very convenient. It can be quite uncomfortable sometimes when there's no total reading progress in the script. Can you please add a progress indicator like the one in the image above?

After adding it, you can easily check how much progress has been made, which is very convenient. It can be quite uncomfortable when the script doesn't have a total reading progress sometimes. Could you please add a progress bar like the one shown in the image above?
Thank you very much.

**Comment by lhj5426** [comment]
I'm very sorry. It seems that I have made an unreasonable and excessive request. I'm really sorry. But this function is indeed very convenient for people with reading anxiety. I wonder if the respected developer can add this function to the script you developed. Your lack of response makes me feel uneasy. I look forward to your reply.

**Comment by TagoDR** [comment]
I wasn't sure it was really needed, But I've added it now
