### ISSUE TITLE
New Site Request (Comic Fans)

### ISSUE THREAD

**Issue by zeoint** [TagoDR/MangaOnlineViewer#433]
Site - [Comic Fans](https://bilibilicomics.net/)

The site downgrades the image to 1000 width and converts them to png in the reader, but the actual images are jpg / webp (depends on the comic viewed) and are very high quality. Please support high quality and the original format of images.

![Image](https://github.com/TagoDR/MangaOnlineViewer/assets/127277950/427fddd3-542e-4d6b-b544-43bdd52e1dde)

**Comment by TagoDR** [comment]
Fixed bilibilicomics.com to .net
