### ISSUE TITLE
[enhancement] auto next

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#440]
When you reach the end of a chapter, you will automatically be redirected to the next chapter. This enhancement should be implemented as an optional feature that can be activated with a button.

**Comment by TagoDR** [comment]
I believe that can be dangerous:

- Some pages may take way longer to read than anticipated, you may be canceling the redirect so often making a moot point trying to make it more convenient.
- Chapters with few pages may get stuck changing all chapters quickly,
- Slow image loading may make the browser believe the images are 1px high, therefore the script believe it has finished instant redirecting.

PS: Appending the next chapter at the bottom is not possible either, most times I need to wait for information on the page to become available first, appending it never does.

**Comment by big-cat-loaf** [comment]
Understandably, I have not thought of your arguments before. Have a nice day
