### ISSUE TITLE
[Bug] disqus.com doesn't load on https://asuratoon.com/

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#441]
example: https://asuratoon.com/8612194254-swordmasters-youngest-son-chapter-16/

**Comment by TagoDR** [comment]
if you use the settings to run the script immediately there isn't any time for the comments to load, either that or you connection is is not working correctly.

**Comment by big-cat-loaf** [comment]
1. The comments can only be loaded in Aways mode. 
3. In the 3 sec. or manual mode, it doesn't work.
5. It does work, but then there is a black screen. Video: 

https://github.com/TagoDR/MangaOnlineViewer/assets/100969549/fcb76a12-8961-4d5f-ba3d-16a0c59e059b

**Comment by big-cat-loaf** [comment]
@TagoDR

**Comment by TagoDR** [comment]
I dont understand why/how the comments would self erase, looks like a issue with disqus it self.
I tried something, I cant see anything else to do. For now just reload and try again.

**Comment by big-cat-loaf** [comment]
I have found a trace of why this could be. Look at this video, where Disqus reloads twice. My current theory is that the script only captures comments the first time, and then the website policy reloads comments a second time, which the script doesn't capture. 


https://github.com/TagoDR/MangaOnlineViewer/assets/100969549/b7616033-2b7d-42e3-9966-fd37fb8b3295
