### ISSUE TITLE
Compatibility with Stay (Userscript Manager) for safari IOS

### ISSUE THREAD

**Issue by Poochy1130** [TagoDR/MangaOnlineViewer#444]
I installed the userscript Manito and when on mangadex (or any other mangasite) stay doesn't read the manga script this is the best userscript manager for ios so giving it support would be awesome

**Comment by Poochy1130** [comment]
![IMG_1235](https://github.com/TagoDR/MangaOnlineViewer/assets/167346032/8973115c-4cec-4a9a-9895-c795ba95ec8d)

**Comment by TagoDR** [comment]
MangaDex is one of the sites that require you to reload the page for the script to start, I've made a small change it shouldn't need it  anymore. Please try again.

I dont own an apple device to test on it.
