### ISSUE TITLE
Take a long time (or its even won't open) to access Anchira.to

### ISSUE THREAD

**Issue by Bubulae** [TagoDR/MangaOnlineViewer#446]
For some reason, its really hard for the scrip running on anchira.to

Sometimes, after open up the pic, the script will open instantly, sometimes it takes a looong time to open and sometimes it wont open at all.

Script running fine on other website on the list, like hentaifox, 9hentai, etc. But just for anchira, its really hard to start the script. Even after refreshing the page several times, script still won't start.

**Comment by TagoDR** [comment]
Their last update broke many things, but it should be a bit better now, download doesn't work any more without some overhaul.
