### ISSUE TITLE
[enhancement] Capture Comments Keybindings

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#449]
Make a keybind for turning comments off and on.

**Comment by TagoDR** [comment]
You mean to open/close comments? 
Its possible, but witch key(s)?
However navigating it purely form the keyboard will most likely conflict with the reader, you will still need a mouse regardless. So it may not be useful in the end.

**Comment by big-cat-loaf** [comment]
No, I mean that setting for activation or deactivating comments is "Capture Comments (When Available)" because on some websites there are many comments and I want to read them, but many do have a comment section but no comments in it, and I want to make the loading faster, so I go every time into the setting and look for "Capture Comments (When Available)" to turn it off.

**Comment by TagoDR** [comment]
I feel that keybindings to change persistent settings may cause confusion, you will probably still need to open settings to check  its current status anyway.
There is a keybind for opening settings quickly already.

**Comment by big-cat-loaf** [comment]
Normaly, you open a setting with "X."  Can you make it that way by clicking X again to close it? That would really help with my problem.

**Comment by TagoDR** [comment]
Yes, that was the initial idea, somehow I didn't check that It wasn't doing that, should be fine now.
