### ISSUE TITLE
readmangatoday 

### ISSUE THREAD

**Issue by CoLdAs1cE** [TagoDR/MangaOnlineViewer#450]
funmanga , mngdoom and mangainn is dead (i think mangainn is dead, i have not used it before and i cannot access with .net or .com)
`// @include       /https?:\/\/(www\.)?(funmanga|mngdoom|readmng|mangainn).(com|net)\/.+\/\d+/`
readmng is only on alive i think but it has changed domain a few times and now the latest is readm.today
https://readm.today
[Chapter link](https://readm.today/manga/gachiakuta/98/all-pages)

**Comment by TagoDR** [comment]
Fixed
