### ISSUE TITLE
fix for imhentai

### ISSUE THREAD

**Issue by martelor** [TagoDR/MangaOnlineViewer#451]
function findServer(cId) {
    if (cId > 0 && cId <= 274825) return "m1.imhentai.xxx";
    if (cId > 274825 && cId <= 403818) return "m2.imhentai.xxx";
    if (cId > 403818 && cId <= 527143) return "m3.imhentai.xxx";
    if (cId > 527143 && cId <= 632481) return "m4.imhentai.xxx";
    if (cId > 632481 && cId <= 816010) return "m5.imhentai.xxx";
    if (cId > 816010 && cId <= 970098) return "m6.imhentai.xxx";
    if (cId > 970098 && cId <= 1121113) return "m7.imhentai.xxx";
    if (cId > 1121113 && cId <= 1259410) return "m8.imhentai.xxx";
    return "m9.imhentai.xxx";
  }

**Comment by TagoDR** [comment]
Done

**Comment by martelor** [comment]
function findServer(cId) {
    const serverRanges = [
      { min: 0, max: 274825, name: "m1" },
      { min: 274826, max: 403818, name: "m2" },
      { min: 403819, max: 527143, name: "m3" },
      { min: 527144, max: 632481, name: "m4" },
      { min: 632482, max: 816010, name: "m5" },
      { min: 816011, max: 970098, name: "m6" },
      { min: 970099, max: 1121113, name: "m7" },
      { min: 1121114, max: 1259410, name: "m8" },
      { min: 1259411, max: 1439024, name: "m9" },
      { min: 1439025, max: Infinity, name: "m10" },
    ];
    return serverRanges.find((server) => cId >= server.min && cId <= server.max)
      ?.name;
  }

**Comment by TagoDR** [comment]
Fixed
