### ISSUE TITLE
[enhancement/question] multi loading

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#456]
This is meant as a long-term project. 
What I mean by mulit loading is to load more than 1 cheapter in go, like there is a field where you put the nummber in and it does load x cheapter in go, so that looks like the cheapter goes on. 
My question is if this is implementable, not that I asked to implement it in the script because even I know that hard.

**Comment by TagoDR** [comment]
I usually just open a couple tabs and read them in order, if I'm on a slow internet I leave the next chapter loading in a new tab while reading. 
I just dont see much value. Can be easily misused to harm the site, so I would force lazy loading. Download would be disabled. Chapter buttons would get confused.

There are many types of sites
1- Some require JavaScript to run before I can do anything - these ones nearly impossible (~50%)
2- Those that require I open each individual page to get the image - possible, but will be harmful to the site(~10%)
3- Sites that use a API - Should be quite easy to do (~10%)
4- Sites that I can just collect the images form the html - Should be simple (~30%)

If you really want to stitch multiple chapters together you can experiment with downloaded chapters(I recommenced from torrents, there are other scripts that specialize in downloading batch of chapters), then locally select to open the parent folder.

**Comment by big-cat-loaf** [comment]
Thank you for your help. What I'm looking for is a way to read "Martial Peak" with 3747 pages, each of which is like 10–30 pages. With so many cheaps and such small amounts of pages, I would open around 50 at a time, and prelonding would take a while. There is not a butten to open the next 50 cheaper, and I didn't ask for something like that. That's my reason for asking this question in the first place. But I will look into the download form cheaper in torrents and hope to find a solution.
