### ISSUE TITLE
please fix this

### ISSUE THREAD

**Issue by kakarisu** [TagoDR/MangaOnlineViewer#458]
In the old version, when I pressed the up and down keys on the keyboard, the screen would not move.
But when I updated the new version today, the screen would move.

old version :
https://github.com/TagoDR/MangaOnlineViewer/assets/116163332/3151b4b3-02be-4904-8776-8ff12527a140

new version : 

https://github.com/TagoDR/MangaOnlineViewer/assets/116163332/44deb906-1426-44e0-9e3c-5ff792e89b55

By the way my old version is v2024.02.14

**Comment by TagoDR** [comment]
Should be fixed now
