### ISSUE TITLE
Add "x-manga.net"

### ISSUE THREAD

**Issue by TheTouffy** [TagoDR/MangaOnlineViewer#459]
https://x-manga.net/

the script seems to work except the save.
THANKS

**Comment by TagoDR** [comment]
What do you mean by "the save", the bookmarks?
Try to reinstall it

**Comment by TheTouffy** [comment]
sorry,
When I click on the download button nothing happens.
and the same for the 'Download Images as Zip Automatically' function

**Comment by TagoDR** [comment]
Some sites just doesn't allow for downloading thru scripts.
I haven't found solution for this, there most likely ins't one
