### ISSUE TITLE
mangago not loading after the first page 

### ISSUE THREAD

**Issue by Momonchii** [TagoDR/MangaOnlineViewer#460]
Hi, I don't know if the issue is with mangago or Firefox nightly (on Android), but it doesn't load the whole chapter: subsequent images show as broken and won't load...
Thank you for your work on this extension and your help!

**Comment by TagoDR** [comment]
Mangago on mobile handles the list of images differently, I've added a redirect for the desktop version of the site, hopefuly that fixes it, having different solutions for desktop and mobile is not nice.

**Comment by Momonchii** [comment]
That fixed it! Thank you so much 😊
