### ISSUE TITLE
[enhancement] 1 pixel picture 

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#462]
A picture should always be bigger than 1x1.
https://www.mgeko.cc/reader/en/the-scholars-reincarnation-chapter-23-eng-li/
https://cdn.mangageko.com/mg1/backup/cdn_mangaraw/the-scholar-s-reincarnation/chapter-23/01.jpg

https://github.com/user-attachments/assets/c7f610a3-d9c2-45fb-aacf-646b64f749c9

**Comment by TagoDR** [comment]
There is a minimal area for each image just in case some image has an irregular size, witch is this case, this image is really 1x1 pixel, it probably got corrupted on upload.

You mean that I should check the image size and remove them/hide if too small? Then how will you know a page is missing/corrupted?

**Comment by big-cat-loaf** [comment]
You could make two buttens where you can hide the last and the first page so that when something comes up that should not be loaded, you can ensure that you avoid any loading from bugged pictures that don't exit #353.
