### ISSUE TITLE
[Bug] The reload image button does not work after being clicked.

### ISSUE THREAD

**Issue by Hayakee** [TagoDR/MangaOnlineViewer#469]
When I browse e-hentai, some images fail to load correctly. I click the reload button at the top right of the image, but it still shows a broken image. I suspect it is not switching to a different H@H for a new request.
![image](https://github.com/user-attachments/assets/841e09c5-1430-4347-bdc7-ed36859aa5e9)
This is the network log from the console after I clicked the reload button:
![image](https://github.com/user-attachments/assets/f1fb967c-79d2-45e8-97cf-c7adbb0a5885)
Strangely, the number at the top right of the page is "199", but the network log shows "198".

**Comment by Hayakee** [comment]
More information:

**Comment by TagoDR** [comment]
I've pushed a possible solution, but its difficult to test, please try it out
