### ISSUE TITLE
reaperscans.com Comments don't work

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#478]
example: https://reaperscans.com/series/level-up-with-skills/chapter-70

**Comment by TagoDR** [comment]
Is a speed connection issue, if it takes too long to load the comments, I skip it.

**Comment by big-cat-loaf** [comment]
No, it isn't. I have really, really fast internet speed. The problem is that your script is overriding the page, and then the page tries to recreate itself and overrides your script, which leads to not leaving the comments.

**Comment by big-cat-loaf** [comment]
I have really really fast connection (100Mbs), so I don't think so?: 

https://github.com/user-attachments/assets/4b46ba87-12ab-4337-a313-7da2f4886490

**Comment by TagoDR** [comment]
I see the problem now, because you set it to immediately start it was not capturing the data correctly. I've pushed a fix, see if it works now.

By the way why do you need to click on tampermonkey for the script to start? It should just start, however reaperscans is one of those sites that needs to be reloaded(f5) for the script to start if you navigate the site normally, opening the chapter in a new tab doesnt need it.

**Comment by big-cat-loaf** [comment]
No, I don't need to click on tampermonkey to start the script. I was checking to see what scripts are loading, and if your script is not loading, I try pressing F5 to reload, as you can see in the video. So it has nothing to do with your script.

**Comment by big-cat-loaf** [comment]
I also found that on this chapter its loading from cache: 
https://reaperscans.com/series/solo-leveling-ragnarok/chapter-1. 
https://media.reaperscans.com/file/4SRBHm/uploads/series/solo-leveling-ragnarok/05e98445-7521-4f53-a9d2-1fa45c4df647/._000_slr.jpg?cache=5

**Comment by TagoDR** [comment]
Its still not working? What other setting do you change from default besides colors?

That "?cache=5" is the script trying to force reload the image, because it failed to load. And indeed the image is broken now, but by the name is seems to be an outro image.

**Comment by big-cat-loaf** [comment]
1. It's working now, was a temperament issue on my side. I was only trying to update your scirpt with the tempermunky update future instate of the offical one. 
2. You think its a outro image. I don't know what the reason of a 0x0 picture there could be, but it shouldn't be loaded by design, in your opinion. We had this problem in the past see #353. For a permanent fix, I would recommend just making a rule that every image URL is checked if cache=5 is load in, when come true to not load it in.
