### ISSUE TITLE
Comick: The specified key does not exist

### ISSUE THREAD

**Issue by ndeerova** [TagoDR/MangaOnlineViewer#480]
Hi, it seems there was a change in comick today. 
Most new chapters don't work, until now all those I put inside the red square, the script can't open the images.
![image](https://github.com/user-attachments/assets/b37aee0f-d87a-4d8f-b06f-44b417cf2e51)
![image](https://github.com/user-attachments/assets/1010de27-290d-4195-bfbd-744daabfe244)
When I change the url from https://meo.comick.pictures/ to https://s3.comick.ink/comick/

Renai no Jugyou: https://comick.io/comic/renai-no-jugyou/nseZfFgq-chapter-1-en
https://s3.comick.ink/comick/0-6ekrahdBeCY2D.jpg
https://meo.comick.pictures/0-6ekrahdBeCY2D.jpg

Instant Regret: https://comick.io/comic/instant-regret/ZT6RYXyM-chapter-15-en
https://meo.comick.pictures/0-QEys3-FLSTeqq.png
https://s3.comick.ink/comick/0-QEys3-FLSTeqq.png

**Comment by TagoDR** [comment]
Should be fine now
