### ISSUE TITLE
Vertical screen issues

### ISSUE THREAD

**Issue by CamperTY** [TagoDR/MangaOnlineViewer#482]
_I'm not a programmer, and I'm not sure if this is the correct way to do things, but here it is._
**The viewer zoom for separate pages kinda bugs out. I included images for reference.**
I have a dual monitor setup, one horizontal and one vertical. The issues are mainly related to the vertical monitor. If relevant, I'm using Firefox on Win11.

The zoom works fine when the window ratio is vertically shorter than the image ratio.
![Screenshot 2024-09-17 151003](https://github.com/user-attachments/assets/2e814bbb-fe91-4805-8899-6f0df3662d11)

However, when the window is longer, the image gets stretched to fill the window instead of having black bars to space pages. 
![Screenshot 2024-09-17 150840](https://github.com/user-attachments/assets/5cae2b40-3726-4094-a9f2-cb42ad304648)

This can cause some really cursed images if the page is a spread lol.
![Screenshot 2024-09-17 151155](https://github.com/user-attachments/assets/d85ec642-0101-4df8-a6a9-cc86f1252f35)

I would also like to say; please let us bind separate keys for "scrolling" and "next page" instead of having both on the same key. Or have that function fixed because PgUp PgDn doesn't work.

**Comment by CamperTY** [comment]
Ah, whoops, disregard that last part. That's an issue for the adult version of the reader. Should I post it there?

**Comment by TagoDR** [comment]
I'm not sure I understand you, give me more details. Below some observations:
-The default view mode is WebComic, without spaces between pages, Vertical is the mode that have spaces.
-By default images cant be wider that the screen, you can disable fit width if oversized
-Zoom only changes the width of the images, the height is always proportional. Its inverted in fit height mode.
-If you use the browser own zoom,instead of the script's, I can't guarantee proportions, use Ctrl+0 to reset it.
-Next/Prev page only works in Fit height mode, any other mode is scroll

**Comment by CamperTY** [comment]
- I mean, I'm using my computer monitor vertically, so the browser window is also vertical, like a phone screen. I'm using webcomic view in MangaReader.
- I'm not using browser zoom. My bad, I should explain more clearly.
- I am aware Next/Prev page only works in Fit height mode.
- I just wanted the Next/Prev page feature usable when using other modes.
- Could you add the feature as a toggle? Or make it so that Fit height mode doesn't distort the image if the window is narrower than the page image but instead displays the next page or extends the vertical view spacer to fill that space?

I've attached some more apparent examples in webcomic fit height mode (looks the same in vertical fit height mode):
![Screenshot 2024-09-17 224943](https://github.com/user-attachments/assets/5d3d3a5d-b4c5-4205-bb2e-8a2a43645001)
![Screenshot 2024-09-17 224954](https://github.com/user-attachments/assets/47f4e10c-f8e9-4021-b1f3-c16c0786e28b)

**Comment by TagoDR** [comment]
I see, you are using fit height with a vertical monitor(extra wide?), this wasn't a use case I predicted.
I made a small fix, on my end it worked like you described should be, single image per visualization, with back space between. try it out

**Comment by CamperTY** [comment]
Yes, your fix worked perfectly! Thank you for your hard work.
