### ISSUE TITLE
Viewing one page at a time

### ISSUE THREAD

**Issue by FunkyJustin** [TagoDR/MangaOnlineViewer#485]
Please add the option to view one page at a time. I prefer seeing just one page at a time and centered on the screen, please add buttons to go to the next page or previous page of the current chapter.

**Comment by TagoDR** [comment]
The "fit height" does that, with up and down buttons

**Comment by FunkyJustin** [comment]
When I press the up and down buttons, the other pages sticks or peeks out because of that scrolling aspect,

I want to get rid of that scrolling and just have the page fixed in the center of the screen.

**Comment by TagoDR** [comment]
Witch site, browser,device? Are you up to date on everything(browser, tampermonky, script)?
