### ISSUE TITLE
mangahere.cc don't load first page and sometimes less

### ISSUE THREAD

**Issue by CoLdAs1cE** [TagoDR/MangaOnlineViewer#49]
mangahere.cc Don't load first page and sometimes less

here is an example of less pages than first,
http://www.mangahere.cc/manga/isekai_mahou_wa_okureteru/c009/

one of many that don't load first page, just go latest releases and pick one.

http://www.mangahere.cc/manga/bokutachi_wa_benkyou_ga_dekinai/c059/

**Comment by TagoDR** [comment]
I fixed the first page problem,  the other ones however I can't, the site doesn't actually have them yet, they are missing.
