### ISSUE TITLE
Not working on exhentai but e-hentai

### ISSUE THREAD

**Issue by ninsuko** [TagoDR/MangaOnlineViewer#491]
script version 2024.10.25
Cannot load image on exhentai as usual
e.g.
https://exhentai.org/g/3101884/9ee38fa392/
thumbnail configuration (default): size = small , rows = 4

![image](https://github.com/user-attachments/assets/90d32a5b-7092-44e4-abeb-9bd8f7c8cb63)

However, images would be loaded if access thru e-hentai frontend
https://e-hentai.org/g/3101884/9ee38fa392/

**Comment by TagoDR** [comment]
Should be fixed now
