### ISSUE TITLE
[NFSW] doesn't work on hentaifox.com anymore 

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#493]
[hentaifox.com-1730923159973.log](https://github.com/user-attachments/files/17652390/hentaifox.com-1730923159973.log)
![Screenshot 2024-11-06 210000](https://github.com/user-attachments/assets/6193c7e4-b7ce-4349-9673-c122eb62e13b)
example: https://hentaifox.com/g/134339/2/

**Comment by TagoDR** [comment]
Fixed
