### ISSUE TITLE
[enhancement] comments edge full black - white 

### ISSUE THREAD

**Issue by big-cat-loaf** [TagoDR/MangaOnlineViewer#494]
Make the edge too white when the comments are white, and make the edge black when the comments are black. Of course, when you make the text "Comments Section," and the right butten also reverses its color. 
Please ignore the text on my picture that is not visible in the comments.

![Screenshot 2024-11-08 203259](https://github.com/user-attachments/assets/9e7ae36a-2dd1-4775-8cb9-453326a24b50)

**Comment by TagoDR** [comment]
Do you mean the color scheme control in settings? The color scheme control in comments is just for that panel because I haven't figured out a way to detect witch background i should use for each site.
![image](https://github.com/user-attachments/assets/e262d802-28e6-4d63-afad-d8d4f516ad9b)

**Comment by big-cat-loaf** [comment]
Yes and no. I meant that when you click this button (see the picture), it should change the edge I circled in the other post to match the color of the comments. Otherwise, it looks a bit off.
![Screenshot 2024-11-09 155454](https://github.com/user-attachments/assets/b3f7d25f-4b00-44e7-99ee-46c753b393bd)
