### ISSUE TITLE
Req for Manhwaread to be added. (NSFW)

### ISSUE THREAD

**Issue by Bubulae** [TagoDR/MangaOnlineViewer#497]
If you can, please add https://manhwaread.com/ 

Thanks..

**Comment by TagoDR** [comment]
Added

**Comment by Bubulae** [comment]
Hello, thanks for accepting the request. But after updating, for some reason, its not working for all site. (including manhwaread that just being added). The script not triggered anymore. The page just open normally without getting triggered.

**Comment by TagoDR** [comment]
update again, should be fine now,
