### ISSUE TITLE
download zip broken

### ISSUE THREAD

**Issue by gmarcher** [TagoDR/MangaOnlineViewer#5]
how am suppose to get downloaded file? 
`http://www.mangatown.com/manga/star_martial_god_technique/c003/`
firefox/chrome+tampermonkey, download option checked

**Comment by TagoDR** [comment]
Fixed It, should be even lighter now, Download only becomes available when everything finish loading, at the bottom of the page

**Comment by gmarcher** [comment]
thanks a lot. And if i remember correctly it can automatic download after finish loading, isn't it?
`http://hentai2read.com/brawling_go/61/` can't download

**Comment by TagoDR** [comment]
Yes, I've just changed the settings to toggle automatic download, otherwise manually will always be avaliable. Also added link on top of the page, will only show after all pages load.
