### ISSUE TITLE
Preload Image after 100 page

### ISSUE THREAD

**Issue by Bubulae** [TagoDR/MangaOnlineViewer#501]
Hello,

I just notice when read manga with 200+ page, this script will preload up to 100 page, and after that, it only preload 2-3 page. 

Im curious, Is there a settings when I reach 100 page, it will continued to preload again about 100, not 2-3 page?

**Comment by TagoDR** [comment]
On desktop you can just disable lazy loading in the settings.
On mobile you can only change the starting point for lazy loading to save mobile data.
Some sites I force lazy loading, because they will ban you for loading images too fast.
