### ISSUE TITLE
new reader on hatigarm, script not working

### ISSUE THREAD

**Issue by explore01** [TagoDR/MangaOnlineViewer#54]
hey there again, Tago!
thanks for the hardwork so far..
i just found that hatigarm just update his web layout, and they got a new reader page
and Manga OnlineViewer script not working there, kinda a pain to read page per page
if you had some time to spare, please look into it..
this is their website address https://www.hatigarmscans.net/
thank you again, Tago!
looking forward to another update XD

**Comment by TagoDR** [comment]
Added
