### ISSUE TITLE
Add a button for user to click to start MOV (or an option auto start MOV)

### ISSUE THREAD

**Issue by My2ndAngelic** [TagoDR/MangaOnlineViewer#6]
As suggested title, I personally think that sometimes I need the addon not to start, but it is not so convenient to start a few click to the scriptmonkey and disable the script.

Instead, I suggest that you can add a button somewhere like "Click to start MangaOnlineViewer" or something like that. It would be amazing since the original page also have the comment section, which I really love.

**Comment by TagoDR** [comment]
My script only starts when you start reading the first page. The way you said makes me think there is a site witch allows for commenting on individual pages, witch is extremely unusual. Every time I've seen commenting it was on the information/summary of the manga where my script doesn't touch.

As of now I don't think is worth it to change the script trigger, witch ever adding you use to install my script, it can always be disabled fully or only my script and then have the web page reloaded so you can comment.
You mentioned scriptmonkey, I believe you meant Greasemonkey, you can just click the monkey face to disable it before opening the page.

**Comment by TagoDR** [comment]
OK, after playing with it, I decided to  implement, it actually will help me when debugging.
