### ISSUE TITLE
A way to exit the script

### ISSUE THREAD

**Issue by hemlok89** [TagoDR/MangaOnlineViewer#65]
Hey, there is an option to return to the chapter list on top & bottom. But is there a way to exit the script while being in the chapter, so the normal page is loaded. I know I can just reload the page & cancel the script load. But for that I have to keep the "Load script automatically" unchecked. It is especially useful for bookmarking a chapter.

**Comment by TagoDR** [comment]
No its not possible, I completely reconstruct the page.
To be sure nothing interferes with the script I erase every thing I can from the page.

**Comment by hemlok89** [comment]
Ok. Thank you for replying. Even with this problem, this is the best manga reader script. :)
