### ISSUE TITLE
Kissmanga second page is not loading.

### ISSUE THREAD

**Issue by hemlok89** [TagoDR/MangaOnlineViewer#69]
Hello, on every manga on kiss, the second page is not loading. Clicking the refresh button does not load the page. Here are some screenshot. 
https://i.imgur.com/0qQAbqu.png
https://i.imgur.com/bHMr58i.png
https://i.imgur.com/kvAH0eq.png

I have re installed the script from Github. I have tried using clearing cache & cookies. I am using Slimjet browser (Chromium 68.0.3440.75), Violentmonkey.

**Comment by TagoDR** [comment]
I was not able to reproduce your error. I downloaded Slimjet with Violentmonkey and still I was not able to reproduce it.

**Comment by hemlok89** [comment]
I am using uBlock Origin. It loads fine with ubo off. I even allowed all 3rd party script but with ubo on, the second page does not load.

**Comment by hemlok89** [comment]
If I click the hide button on page 2 (the eye button), this happens.

https://i.imgur.com/DFN38IE.png

**Comment by TagoDR** [comment]
When you notice it happens again disable everything (Script,Adblocker), and reload the page.
Then press F12 the open the developer panel, look for the console tab, there should be a icon for trashcan or blocksign to clear up the console,
Then type "lstImages" without quotes,  it should show the list of url of all the images of the manga pages, look for the 2nd image in particular should not be suspicious for ublocker to intervene. Paste it here too please.

**Comment by hemlok89** [comment]
Hello, in console, typing lstImages does not return any results. But I have identified the group with this script. Here is a screen with blocking disabled.

https://i.imgur.com/AuiimmI.png

Here is one with blocking enabled.

https://i.imgur.com/T9lqDyP.png

Here is the starting log of the script with ubo off.

https://i.imgur.com/5hCa2DX.png

Here is the starting log of the script with ubo on.

https://i.imgur.com/qKlCkvv.png

Here is a SS of ubo logger.

https://i.imgur.com/jnahPxQ.png

**Comment by hemlok89** [comment]
Sorry for me being dumb, here's the full console output in a file
[kissmanga.com-1542480769057.log](https://github.com/TagoDR/MangaOnlineViewer/files/2592142/kissmanga.com-1542480769057.log)

**Comment by TagoDR** [comment]
I use uBlock myself, and I cant find any reason for it to block any of those images, it is very strange it always blocks the 2nd page (image 001.jpg).
For my part, in the script, there is nothing I can really do. You must look into your ublock, your filter lists and rules.

**Comment by hemlok89** [comment]
I have tracked down the culprit. I use another script called MAL Sync (formerly KissAnime List), to prevent some breakage in the script, the dev provided a filter for ubo to unbreak mini MAL. Disabling this script, resolves the problem.

https://raw.githubusercontent.com/Karmesinrot/Anifiltrs/master/Anifltrs.txt

Can you check if I can remove any lines to make both of them work??

**Comment by hemlok89** [comment]
Hello, this was due to a problem in Violent monkey. I opened an issue in Anifiltrs repo & @Karmesinrot found a solution Karmesinrot/Anifiltrs#3 and it is working now.
