### ISSUE TITLE
not always auto download

### ISSUE THREAD

**Issue by gmarcher** [TagoDR/MangaOnlineViewer#7]
i'm facing problem http://www.mangatown.com/manga/re_birth_2_the_life_taker/c002/#download
auto download not start (reload not fix it) and from web console getting loop
`..Page 007.png Added to Zip as Base64 Image %20line%203%20%3E%20Function:574:33..`
and the problem occur randomly maybe another chapter.  Thanks

firefox55/chrome60 +tampermonkey

**Comment by TagoDR** [comment]
I was not able to reproduce your error.
On tampermonky dashboard go to edit the script, then on the script's settings tab look for XHR security, verify if the site domain is not blacklisted.

**Comment by TagoDR** [comment]
OK I Found it, should be fine now
