### ISSUE TITLE
mangafox new version broke script

### ISSUE THREAD

**Issue by CoLdAs1cE** [TagoDR/MangaOnlineViewer#70]
http://fanfox.net/manga/berserk_of_gluttony/c008/1.html

the updated their layout so script is broken now 

`MangaOnlineViewer: Starting Manga OnlineViewer 13.53.0 on Firefox 63 with Tampermonkey 4.8.5847 userscript.html:120:5

MangaOnlineViewer: 33 Known Manga Sites userscript.html:120:5

MangaOnlineViewer: Looking for a match... userscript.html:120:5

MangaOnlineViewer: Site Found: 

Object { name: "MangaFox", url: /https?:\/\/(www.)?(mangafox.la|fanfox.net)\/manga\/.+\/.+\//, homepage: "http://mangafox.la/", language: (1) […], category: "manga", run: run()
 }

userscript.html:120:5
ERROR: Execution of script 'Manga OnlineViewer' failed! invalid array length userscript.html:4:392
run@moz-extension://7328d16f-dc65-4706-a80a-a3d317aaae63/userscript.html?id=6a9b959b-b60d-4655-b00c-00dfd74b83b1:1010:24
waitExec@moz-extension://7328d16f-dc65-4706-a80a-a3d317aaae63/userscript.html?id=6a9b959b-b60d-4655-b00c-00dfd74b83b1:825:18
O@moz-extension://7328d16f-dc65-4706-a80a-a3d317aaae63/userscript.html?id=6a9b959b-b60d-4655-b00c-00dfd74b83b1:49:2923
tms_6a9b959b_b60d_4655_b00c_00dfd74b83b1/</le<@moz-extension://7328d16f-dc65-4706-a80a-a3d317aaae63/userscript.html?id=6a9b959b-b60d-4655-b00c-00dfd74b83b1:49:31435
D/<@moz-extension://7328d16f-dc65-4706-a80a-a3d317aaae63/userscript.html?id=6a9b959b-b60d-4655-b00c-00dfd74b83b1:49:6182
n/<@moz-extension://7328d16f-dc65-4706-a80a-a3d317aaae63/userscript.html?id=6a9b959b-b60d-4655-b00c-00dfd74b83b1:49:4981
n@moz-extension://7328d16f-dc65-4706-a80a-a3d317aaae63/userscript.html?id=6a9b959b-b60d-4655-b00c-00dfd74b83b1:49:4835
_/<@moz-extension://7328d16f-dc65-4706-a80a-a3d317aaae63/userscript.html?id=6a9b959b-b60d-4655-b00c-00dfd74b83b1:49:3232
r/<@moz-extension://7328d16f-dc65-4706-a80a-a3d317aaae63/userscript.html?id=6a9b959b-b60d-4655-b00c-00dfd74b83b1:49:308
start@moz-extension://7328d16f-dc65-4706-a80a-a3d317aaae63/userscript.html?id=6a9b959b-b60d-4655-b00c-00dfd74b83b1:829:5
tms_6a9b959b_b60d_4655_b00c_00dfd74b83b1/<@moz-extension://7328d16f-dc65-4706-a80a-a3d317aaae63/userscript.html?id=6a9b959b-b60d-4655-b00c-00dfd74b83b1:1598:3
tms_6a9b959b_b60d_4655_b00c_00dfd74b83b1@moz-extension://7328d16f-dc65-4706-a80a-a3d317aaae63/userscript.html?id=6a9b959b-b60d-4655-b00c-00dfd74b83b1:114:2
g</<@eval:2:479
anonymous/<@moz-extension://7328d16f-dc65-4706-a80a-a3d317aaae63/userscript.html?id=6a9b959b-b60d-4655-b00c-00dfd74b83b1:4:1
anonymous/<@moz-extension://7328d16f-dc65-4706-a80a-a3d317aaae63/userscript.html?id=6a9b959b-b60d-4655-b00c-00dfd74b83b1:3:55
anonymous@moz-extension://7328d16f-dc65-4706-a80a-a3d317aaae63/userscript.html?id=6a9b959b-b60d-4655-b00c-00dfd74b83b1:3:2
g</<@eval:2:479
E_c@eval:3:293
ka@eval line 1 > Function:61:378
create@eval line 1 > Function:72:334
e@eval line 1 > Function:16:154`

**Comment by TagoDR** [comment]
Fixed It

**Comment by CoLdAs1cE** [comment]
noticed
    url: /https?:\/\/(www.)?|fanfox.net\/manga\/.+\/.+\//,

should remove | or it wont work

**Comment by TagoDR** [comment]
should be ok now
