### ISSUE TITLE
kiss manga title

### ISSUE THREAD

**Issue by CoLdAs1cE** [TagoDR/MangaOnlineViewer#71]
i noticed it only gave the series name not the chapter and volume info if it had it.
so i fixed mine with this

$('.selectChapter:first option:selected').text()

though im not sure if that was what was intended and u missed it ;)

**Comment by TagoDR** [comment]
OK, I`ve adjusted it, however kissmanga is terrible site, I don't recommend it.

**Comment by CoLdAs1cE** [comment]
i know. but some times i have to use it ;(
