### ISSUE TITLE
Mangarock.com did not auto start after 3 seconds

### ISSUE THREAD

**Issue by KratosvsEzio** [TagoDR/MangaOnlineViewer#72]

**Comment by KratosvsEzio** [comment]
Mangarock.com did not auto start after 3 seconds. i think we should have option whether to select auto start or not after 3 seconds.

**Comment by TagoDR** [comment]
Try reloading the page, mangarock can be finicky

**Comment by KratosvsEzio** [comment]
i did several times but it did not start. it was working few days ago.But
now its not working.

**Comment by TagoDR** [comment]
It should be fixed now.
