### ISSUE TITLE
Next, Previous, and Return to chapter list

### ISSUE THREAD

**Issue by Naivra** [TagoDR/MangaOnlineViewer#8]
i have updated the script to v12.12

for tenmanga => next and previous is working correctly now. but return to chapter list still not redirect to chapter list correctly.

for mangapark => if i click next/previous for 1st time after the script loaded, its indeed go to next/previous chapter, but it also automatically change the load image selection to all images that cause the script to load only the first image. 
for return to chapter list, its sometimes works correctly but sometimes its not (i didn't know what causing it), and if its didn't work correctly, it also automatically change the load image selection to all images that cause the script to load only the first image. 

sorry for the long explanation, i hope you could fix them.

**Comment by TagoDR** [comment]
Fixed, I believe every thing is fine now.
