### ISSUE TITLE
New update broke the script

### ISSUE THREAD

**Issue by My2ndAngelic** [TagoDR/MangaOnlineViewer#82]
Hi there,

I have recently update your adult script from 13.77.0 to 13.78.0. I have seen that you changed some in the @require part and it kinda breaks everything. I have tested on Chrome, Firefox and Waterfox and almost every site I used to read like KissManga, nhentai, mangadex, etc. is unreadable, no image load.

However, if I revert back to version 13.77.0, everything works again. Please check if there is something that breaks your script. At this point I think reverting back the @require part to 13.77.0 is a good idea for now.

**Comment by TagoDR** [comment]
Fixed it, too many scripts with similar names, I updated one required script to the wrong one.
