### ISSUE TITLE
https://mangaplus.shueisha.co.jp 

### ISSUE THREAD

**Issue by CoLdAs1cE** [TagoDR/MangaOnlineViewer#84]
can u add https://mangaplus.shueisha.co.jp . it an official site. would be awsome! :D

**Comment by TagoDR** [comment]
That is a difficult request, they definitely went 10 extra miles to make the site super contrived and complicated to fetch information.

**Comment by CoLdAs1cE** [comment]
ah, damn ;((((((((( okey. thanks

**Comment by CoLdAs1cE** [comment]
after testing some things i see what you mean LOL! u need to be an expert hacker for that shit

**Comment by TagoDR** [comment]
The API response is encrypted, decoding it into useful information is not simple, there seems to be a lot of nested stuff.

**Comment by CoLdAs1cE** [comment]
yeah and they are using vue and webpack shit to encrypt and obfscurate it even more

> 
> 
> The API response is encrypted, decoding it into useful information is not simple, there seems to be a lot of nested stuff.
