### ISSUE TITLE
mangarock title is wrong

### ISSUE THREAD

**Issue by CoLdAs1cE** [TagoDR/MangaOnlineViewer#85]
it just displays manga reader. it think they moved title to meta tags
$("meta[name='twitter:title']").attr('content').trim()

to get the correct title i think :)

**Comment by TagoDR** [comment]
This Twitter:title is not always present.
The title is more reliable, even thou you may not always give it enough time to load

**Comment by CoLdAs1cE** [comment]
i see. mby i have to fast network for title to load 😄
