### ISSUE TITLE
Start loading at a specific page

### ISSUE THREAD

**Issue by drkui** [TagoDR/MangaOnlineViewer#87]
There are certain manga sites that lists thumbnails of all the pages of the chapter. So, if I want to start reading at page 40 instead of page 1, the script would load all of the images starting from page 1 instead of starting at page 40. This isn't preferable since I not only have to wait for the previous images to load to get to where I want, but it's bad if I'm on a mobile connection and it's taking up a lot of bandwidth.

These sites will have:

/*number here*

Usually at the end of the URL. It would be pretty nice to have this as a feature.

**Comment by TagoDR** [comment]
I had planned a feature like that, But I eventually forgot.
I may look into adding it.

**Comment by TagoDR** [comment]
Added it, just don't let it start automatically, and you may choose
Check it out.

**Comment by drkui** [comment]
I like the new option where it doesn't load the chapter automatically and there's now a button to start it manually. One thing that would be a good addition to the new feature is to have the slider start on the page the user selected.

For example if I'm on page 5 (/005, #5, etc), the 'Choose the Page to start from:' slider will automatically be on 5 and all I would need to do is just click 'OK'.

**Comment by TagoDR** [comment]
I does auto select bookmarked pages.
However to auto select the open page, it would need to identify witch it is every each site, it would require reviewing every site script.

**Comment by drkui** [comment]
I see, I'm guessing that's why there's a slider? Otherwise now that I think about it, it would make sense to open the viewer on the selected page after clicking the 'Start MangaOnlineViewer' button (without the slider).

Anyway, thank you for adding the feature, any improvement is appreciated. 😊
