### ISSUE TITLE
Add a setting limit pages loading.

### ISSUE THREAD

**Issue by Salin1810** [TagoDR/MangaOnlineViewer#89]
Some manga, uploader combine more chapters in one chapter. That makes sometimes overload ram consume. Can you make a setting limit pages pre-loading about 20?
And is there have set can skip 3s waiting?
Thank you for reading!

**Comment by TagoDR** [comment]
I'll look for way. 
For skiping the 3 sec look for the load mode in the settings.

**Comment by TagoDR** [comment]
I have added an option for Lazy Loading the Images, check it out.
If the problem is bandwidth/memory, disable Thumbnails as well.

**Comment by Salin1810** [comment]
Everything working well, tks you for hard work !
