### ISSUE TITLE
Stopped working on KissManga

### ISSUE THREAD

**Issue by hemlok89** [TagoDR/MangaOnlineViewer#90]
Here is the console output. 
[kissmanga.com-1566126368713.log](https://github.com/TagoDR/MangaOnlineViewer/files/3512924/kissmanga.com-1566126368713.log)

Working fine on other sites.

**Comment by TagoDR** [comment]
Should be fine now, keep the console closed on this site, they have some broken code and is triggering debug mode.

**Comment by hemlok89** [comment]
Still having same problem. I manually updated the script from Github. [Screenshot](https://i.imgur.com/7kEY4V0.png)

**Comment by TagoDR** [comment]
I don't recognize the browser you are using, it probably does not have the Javascript features I`m using

**Comment by hemlok89** [comment]
This is CentBrowser, based on Chromium. I tried on Firefox & it was working fine, then suddenly stopped working just now.
![image](https://user-images.githubusercontent.com/39864104/63253896-5c3b9a80-c290-11e9-818c-b5c5fef58f0a.png)

**Comment by hemlok89** [comment]
This is frustrating. It started working again. I did not do anything to the script or cookies. I think it is something on Kissmanga end. I am going to close this as I do not think the script has any errors.

**Comment by hemlok89** [comment]
Hello. The problem is still happenning forr last ten days. I have disabled all unnecessary add ons & scripts & captured both console loog & ubo log.

[kissmanga.com-1567421315110.log](https://github.com/TagoDR/MangaOnlineViewer/files/3565703/kissmanga.com-1567421315110.log)
[ubo_kissmanga.com-1567421315110.txt](https://github.com/TagoDR/MangaOnlineViewer/files/3565704/ubo_kissmanga.com-1567421315110.txt)

**Comment by TagoDR** [comment]
Your browser doesn't seems to have the function 'console.clear'.
I've added a fix for it, check if it is working now.

**Comment by hemlok89** [comment]
Thank you!! It is working now. Also this is [CentBrowser](https://www.centbrowser.com/). Just a modified Chromium. Right now it is on version 74. Should have everything that Chrome has.
