### ISSUE TITLE
Ctrl+S on loaded page no longer working on my pc

### ISSUE THREAD

**Issue by explore01** [TagoDR/MangaOnlineViewer#91]
hey there TagoDR
been a while

lately i find that saving a whole page as complete html can't be done with Ctrl+S in my firefox anymore..
when i press Ctrl+S, it just activate scrolling down the page
i don't know where did i go wrong, or did i touch some key that make these thing happen?
i can still saving the page, through file menu / save as...
i wonder if you know something about this,
thank you TagoDR!

old fans of your work!
Rizky

**Comment by TagoDR** [comment]
It should be fine now
