### ISSUE TITLE
Lazy loading uses placehold.it

### ISSUE THREAD

**Issue by Mathnerd314** [TagoDR/MangaOnlineViewer#92]
The script loads `http://placehold.it/1000x500` as a placeholder when lazy loading is enabled.
I guess there are two issues:
* This gives a mixed content warning on manga sites using HTTPS, since `placehold.it` doesn't support HTTPS.
* `placehold.it` is in hpHosts's blacklist, meaning uBlock Origin prevents the image from loading at all (which breaks the script)

Apparently `https://via.placeholder.com/1000x500` works and isn't blacklisted, but I would suggest just setting the width and height temporarily in `addImg`:
```js
      $("#PageImg".concat(index)).attr('data-src', url).unveil({
        offset: 500,
        throttle: 500
      }).width(1000).height(500).on('loading.unveil', () => {
        $("#PageImg".concat(index)).width('initial').height('initial');
      }).on('loaded.unveil', () => {
        logScript('Unveiled Image:', index, 'Source:', url);
      }).parent().slideToggle();
```

**Comment by TagoDR** [comment]
I have removed the external site, it should be fine now

**Comment by Mathnerd314** [comment]
There is already a tiny GIF placeholder included in unveil: https://github.com/nabble/unveil2/blob/develop/src/jquery.unveil2.js#L67
```
placeholder: 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
```

I don't think you need the png one at all.

**Comment by TagoDR** [comment]
You are correct.
Everything looks fine now.
