### ISSUE TITLE
Is there a way to use the script for mobile (using Bookmark)?

### ISSUE THREAD

**Issue by tj3n123** [TagoDR/MangaOnlineViewer#96]
Hi, as the title said, is there anyway to use this on mobile chrome like [Manga Loader](https://greasyfork.org/en/scripts/692-manga-loader)? I really like the script and this is the only missing feature right now :D Hope you can find some time to add it, thanks.

**Comment by TagoDR** [comment]
It does work, you just have to "Request Desktop Site" in most sites. I have it working just fine in Firefox mobile with tampermonkey

**Comment by tj3n123** [comment]
Thanks for your reply, sadly I'm using iOS and it doesn't seems to support extension :( i think the only way to make it works for both operation is via bookmark javascript

**Comment by TagoDR** [comment]
The bookmarklet should be this:

``javascript:(function(){['https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js', 'https://cdn.jsdelivr.net/npm/ramda@latest/dist/ramda.min.js', 'https://cdn.jsdelivr.net/gh/TagoDR/MangaOnlineViewer@latest/Manga_OnlineViewer.user.min.js'].map( s => document.body.appendChild(document.createElement('script')).src=s)})();``

**However I need to fix a few things on the script first so it may work without tampermonkey.**

**Comment by tj3n123** [comment]
Thank you 😁 sound great, can't wait to have it working

**Comment by TagoDR** [comment]
Should be fine now, use the bookmarklet in the readme page.

**Comment by tj3n123** [comment]
Awesome, I tried it, works great for some sites but not all, probably due to mobile pages use different code. 

It would be super great if you could have it support for NSFW too. Many thanks! 😍

**Comment by TagoDR** [comment]
Use 'Request for Desktop Page' function of your browser before activation the bookmarklet
