### ISSUE TITLE
Support for tmohentai.com

### ISSUE THREAD

**Issue by wernser412** [TagoDR/MangaOnlineViewer#97]
please add for this site.

**Comment by TagoDR** [comment]
Added it enjoy

**Comment by wernser412** [comment]
no see imagen in the page 10 - 20 and 30

https://tmohentai.com/reader/5dc22dd78be99/paginated/2?image-width=normal-width

![Sin título](https://user-images.githubusercontent.com/53667212/68275286-34f79c80-0039-11ea-999d-e7bad4719b10.png)

![Sin título](https://user-images.githubusercontent.com/53667212/68275369-6ec8a300-0039-11ea-9fb5-8da1fb279289.png)

**Comment by wernser412** [comment]
de la pagina 10 para arriba no corresponden  al original

**Comment by wernser412** [comment]
@TagoDR the images from 10 up do not correspond
