### ISSUE TITLE
Right-to-left mode and left-to-right mode don't seem to work

### ISSUE THREAD

**Issue by volcbs** [TagoDR/MangaOnlineViewer#98]
Just like the title says, they don't work for some reasons. 
I'm using Chromium Edge (Chromium build v79.0.287.2) anyway if that's relevant.

**Comment by TagoDR** [comment]
I cant think of any reason for it to not work, any chromium browser should have support for 'direction: rtl'.
Try other sites, an look at the log

**Comment by volcbs** [comment]
Try it in mangahere and mangadex, and it doesn't seem to work. I'm trying to download chromium v79 and yeah, it doesn't seem to work there either.

**Comment by volcbs** [comment]
Just found out why they don't work. Apparently you the feature would work when you zoom out the site. Then again it's kinda weird that it becomes like this after it's zoomed out. Well unless that's what your intention though. Anyway I'm installing firefox 62.0.2 and producing the same result.

![Annotation 2019-10-05 165554](https://user-images.githubusercontent.com/12575216/66253361-58f16500-e791-11e9-9861-83769ca1172a.jpg)

**Comment by TagoDR** [comment]
Yes if the image is too large it has no effect on it, think about the double pages.
