### ISSUE TITLE
Problem on KissManga

### ISSUE THREAD

**Issue by hemlok89** [TagoDR/MangaOnlineViewer#99]
After the recent update, the script stopped working on KissManga. I have set it on manual mode. When I click on Start MangaOnlineViewer, the page scrolls to bottom. At the bottom left, the page selector window is visible partially. [Screenshot](https://i.imgur.com/JcWyVMw.png).

Tested on Chrome & Firefox.

**Comment by TagoDR** [comment]
It is only happening with kissmanga, on automatic or always mode it works just fine.
I can only guess something is blocking/conflicting with the message box.

**Comment by hemlok89** [comment]
This problem is still persisting.
